#!/usr/bin/env bash
set -euxo pipefail

# link so we can debug cephadm
ln -s -f /cephadm/cephadm $CEPHADM_PATH
chmod +x $CEPHADM_PATH

tail -f /var/log/ceph/cephadm.log 1>&2 &

EXTRA_ARGS=()
if [[ -n "${SHARED_CEPH_FOLDER-}" ]]; then
    EXTRA_ARGS+=(--shared_ceph_folder "$SHARED_CEPH_FOLDER")
fi

docker load < /cephadm/box/docker/ceph/image/quay.ceph.image.tar

# cephadm guid error because it sometimes tries to use quay.ceph.io/ceph-ci/ceph:<none>
# instead of master's tag
export CEPHADM_IMAGE=quay.ceph.io/ceph-ci/ceph:master
echo "export CEPHADM_IMAGE=quay.ceph.io/ceph-ci/ceph:master" >> ~/.bashrc

if [[ -n "$CEPHADM_IMAGE" ]]; then
	EXTRA_ARGS+=--skip-pull
fi

export CEPH_SOURCE_FOLDER=/ceph
$CEPHADM_PATH --verbose bootstrap \
  --mon-ip "$(hostname -i)" \
  --allow-fqdn-hostname \
  --initial-dashboard-password admin \
  --dashboard-password-noupdate \
  --shared_ceph_folder /ceph \
  "${EXTRA_ARGS[@]}"

# make sure vg and lvs are visible
vgchange --refresh
for((i=0;i<$NUM_OSDS;i++)); do
	echo "Creating osd.${i}"
	# create osd folder
	$CEPHADM_PATH ceph-volume --shared_ceph_folder /ceph lvm create --bluestore --no-tmpfs --data "/dev/vg1/lv${i}" --no-systemd
	echo "Deploying osd.${i}..."
	# deploy osd with osd data folder
	$CEPHADM_PATH deploy --name "osd.${i}"
	echo "osd.${i} deployed!"
done;
