import logging
from textwrap import dedent
from ceph_volume import decorators
from ceph_volume.util import dmcrypt_rotation
from typing import List, Optional

logger = logging.getLogger(__name__)


class RotateDmcryptKey(object):

    help = "Rotate the dmcrypt (LUKS) passphrase of an encrypted OSD"

    sub_command_help = dedent("""
    Rotate the dmcrypt (LUKS) passphrase of an OSD deployed with
    `ceph-volume lvm prepare --dmcrypt`, in place and while the OSD is
    running. All LUKS devices of the OSD (block/db/wal) are rotated as a
    set.

    By default the new passphrase is generated by ceph-volume and stored
    back on the monitors at dm-crypt/osd/{fsid}/luks, which requires
    credentials with "config-key set" caps on that key (see --name and
    --keyring).

    When the passphrase is owned by an external system (e.g. Rook), pass the
    passphrase your store holds now via CEPH_VOLUME_DMCRYPT_SECRET and the
    new passphrase via CEPH_VOLUME_NEW_DMCRYPT_SECRET, and use the two-phase
    flow:

        export CEPH_VOLUME_DMCRYPT_SECRET=<passphrase in your store>
        export CEPH_VOLUME_NEW_DMCRYPT_SECRET=<new passphrase>
        ceph-volume lvm rotate-dmcrypt-key --osd-id 0 \\
            --key-store external --phase stage

        <store the new passphrase in your key store and verify it>

        export CEPH_VOLUME_DMCRYPT_SECRET=<new passphrase>
        ceph-volume lvm rotate-dmcrypt-key --osd-id 0 \\
            --key-store external --phase finish

    If the lockbox cephx secret was also rotated (ceph auth rotate
    client.osd-lockbox.{fsid}), pass the new secret via
    CEPH_VOLUME_CEPHX_LOCKBOX_SECRET so the LV tags and the lockbox
    keyring are updated as well:

        export CEPH_VOLUME_CEPHX_LOCKBOX_SECRET=<new lockbox secret>
        ceph-volume lvm rotate-dmcrypt-key --osd-id 0 \\
            --name client.admin --keyring /etc/ceph/ceph.client.admin.keyring

    The OSD is named with either --osd-id or --osd-fsid.
    """)

    def __init__(self, argv: Optional[List[str]] = None) -> None:
        self.argv = argv

    @decorators.needs_root
    def rotate(self) -> None:
        dmcrypt_rotation.rotate_from_args(self.args, 'lvm')

    def main(self) -> None:
        parser = dmcrypt_rotation.make_parser(
            'ceph-volume lvm rotate-dmcrypt-key',
            self.sub_command_help,
            'lvm',
        )
        if self.argv is None:
            self.argv = []
        if len(self.argv) == 0:
            print(self.sub_command_help)
            return
        self.args = parser.parse_args(self.argv)
        self.rotate()
