.TH CCLSINFO 8
.SH NAME
cclsinfo \- show class object information
.SH SYNOPSIS
.B cclsinfo
[ \fIoptions\fR ] ... \fIfilename\fR 
.SH DESCRIPTION
.B cclsinfo
can show name, version, and architecture information about a specific class object.
.SH OPTIONS
.TP
\fB\-n\fP, \fB\-\-name\fP
Shows the class name
.TP
\fB\-v\fP, \fB\-\-version\fP
Shows the class version
.TP
\fB\-a\fP, \fB\-\-arch\fP
Shows the class architecture
.SH AVAILABILITY
.B cclsinfo
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR cclass (8)
.BR ceph (8)
