.TH  "ceph_selinux"  "8"  "16-02-11" "ceph" "SELinux Policy ceph"
.SH "NAME"
ceph_selinux \- Security Enhanced Linux Policy for the ceph processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ceph processes via flexible mandatory access control.

The ceph processes execute with the ceph_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep ceph_t


.SH "ENTRYPOINTS"

The ceph_t SELinux type can be entered via the \fBceph_exec_t\fP file type.

The default entrypoint paths for the ceph_t domain are the following:

/usr/bin/radosgw, /usr/bin/ceph-mon, /usr/bin/ceph-mds, /usr/bin/ceph-osd
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux ceph policy is very flexible allowing users to setup their ceph processes in as secure a method as possible.
.PP
The following process types are defined for ceph:

.EX
.B ceph_t
.EE
.PP
Note:
.B semanage permissive -a ceph_t
can be used to make the process type ceph_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  ceph policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ceph with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to allow all daemons to write corefiles to /, you must turn on the daemons_dump_core boolean. Disabled by default.

.EX
.B setsebool -P daemons_dump_core 1

.EE

.PP
If you want to enable cluster mode for daemons, you must turn on the daemons_enable_cluster_mode boolean. Disabled by default.

.EX
.B setsebool -P daemons_enable_cluster_mode 1

.EE

.PP
If you want to allow all daemons to use tcp wrappers, you must turn on the daemons_use_tcp_wrapper boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tcp_wrapper 1

.EE

.PP
If you want to allow all daemons the ability to read/write terminals, you must turn on the daemons_use_tty boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tty 1

.EE

.PP
If you want to deny any process from ptracing or debugging any other processes, you must turn on the deny_ptrace boolean. Disabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Enabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the ceph_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the ceph_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type ceph_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B ceph_log_t

	/var/log/ceph(/.*)?
.br
	/var/log/radosgw(/.*)?
.br

.br
.B ceph_var_lib_t

	/var/lib/ceph(/.*)?
.br

.br
.B ceph_var_run_t

	/var/run/ceph(/.*)?
.br

.br
.B cluster_conf_t

	/etc/cluster(/.*)?
.br

.br
.B cluster_var_lib_t

	/var/lib/pcsd(/.*)?
.br
	/var/lib/cluster(/.*)?
.br
	/var/lib/openais(/.*)?
.br
	/var/lib/pengine(/.*)?
.br
	/var/lib/corosync(/.*)?
.br
	/usr/lib/heartbeat(/.*)?
.br
	/var/lib/heartbeat(/.*)?
.br
	/var/lib/pacemaker(/.*)?
.br

.br
.B cluster_var_run_t

	/var/run/crm(/.*)?
.br
	/var/run/cman_.*
.br
	/var/run/rsctmp(/.*)?
.br
	/var/run/aisexec.*
.br
	/var/run/heartbeat(/.*)?
.br
	/var/run/cpglockd\.pid
.br
	/var/run/corosync\.pid
.br
	/var/run/rgmanager\.pid
.br
	/var/run/cluster/rgmanager\.sk
.br

.br
.B fsadm_var_run_t

	/var/run/blkid(/.*)?
.br

.br
.B initrc_tmp_t


.br
.B mnt_t

	/mnt(/[^/]*)?
.br
	/mnt(/[^/]*)?
.br
	/rhev(/[^/]*)?
.br
	/media(/[^/]*)?
.br
	/media(/[^/]*)?
.br
	/media/\.hal-.*
.br
	/var/run/media(/[^/]*)?
.br
	/net
.br
	/afs
.br
	/rhev
.br
	/misc
.br

.br
.B root_t

	/
.br
	/initrd
.br

.br
.B tmp_t

	/sandbox(/.*)?
.br
	/tmp
.br
	/usr/tmp
.br
	/var/tmp
.br
	/tmp-inst
.br
	/var/tmp-inst
.br
	/var/tmp/vi\.recover
.br

.br
.B var_run_t

	/run/.*
.br
	/var/run/.*
.br
	/run
.br
	/var/run
.br
	/var/run
.br
	/var/spool/postfix/pid
.br

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux ceph policy is very flexible allowing users to setup their ceph processes in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the ceph, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t ceph_exec_t '/srv/ceph/content(/.*)?'
.br
.B restorecon -R -v /srv/myceph_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for ceph:


.EX
.PP
.B ceph_exec_t
.EE

- Set files with the ceph_exec_t type, if you want to transition an executable to the ceph_t domain.

.br
.TP 5
Paths:
/usr/bin/radosgw, /usr/bin/ceph-mon, /usr/bin/ceph-mds, /usr/bin/ceph-osd

.EX
.PP
.B ceph_initrc_exec_t
.EE

- Set files with the ceph_initrc_exec_t type, if you want to transition an executable to the ceph_initrc_t domain.

.br
.TP 5
Paths:
/etc/rc\.d/init\.d/ceph, /etc/rc\.d/init\.d/radosgw

.EX
.PP
.B ceph_log_t
.EE

- Set files with the ceph_log_t type, if you want to treat the data as ceph log data, usually stored under the /var/log directory.

.br
.TP 5
Paths:
/var/log/ceph(/.*)?, /var/log/radosgw(/.*)?

.EX
.PP
.B ceph_var_lib_t
.EE

- Set files with the ceph_var_lib_t type, if you want to store the ceph files under the /var/lib directory.


.EX
.PP
.B ceph_var_run_t
.EE

- Set files with the ceph_var_run_t type, if you want to store the ceph files under the /run or /var/run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage".

.SH "SEE ALSO"
selinux(8), ceph(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)
