.TH CMDS 8
.SH NAME
cmds \- ceph metadata server daemon
.SH SYNOPSIS
.B cmds
\fB\-i \fIname\fR
[[ \fB\-\-hot-standby\fI [rank]\fR ]|[\fB\-\-journal_check\fI rank\fR]]

.SH DESCRIPTION
.B cmds
is the metadata server daemon for the Ceph distributed file system.
One or more instances of \fBcmds\fP collectively manage the file system
namespace, coordinating access to the shared OSD cluster.
.PP
Each 
.B cmds
daemon instance should have a unique \fIname\fP.  The name is used
to identify daemon instances in the \fIceph.conf\fP.
.PP
Once the daemon has started, the monitor cluster will normally assign it
a logical rank, or put it in a standby pool to take over for another daemon
that crashes. Some of the specified options can cause other behaviors.
.PP
If you specify hot-standby or journal-check, you must either specify the rank
on the command line, or specify one of the mds_standby_for_[rank|name]
parameters in the config. The command line specification overrides the config,
and specifying the rank overrides specifying the name.

.SH OPTIONS
.TP
\fB\-f\fP, \fB\-\-foreground\fP
Foreground: do not daemonize after startup (run in foreground).
Do not generate a pid file. Useful when run via crun (8).
.TP
\fB\-d\fP
Debug mode: like -f, but also send all log output to stderr.
.TP
\fB\-c\fI ceph.conf\fR, \fB\-\-conf=\fIceph.conf\fR
Use \fIceph.conf\fP configuration file instead of the default \fI/etc/ceph/ceph.conf\fP
to determine monitor addresses during startup.
.TP
\fB\-m\fI monaddress[:port]\fR
Connect to specified monitor (instead of looking through \fIceph.conf\fR).
.SH AVAILABILITY
.B cmon
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR ceph (8),
.BR cmon (8),
.BR cosd (8)
