.TH CMON 8
.SH NAME
cmon \- ceph monitor daemon
.SH SYNOPSIS
.B cmon
\fB\-i \fImonid\fR
[ \fB\-\-mon\-data mondatapath\fR ]
.SH DESCRIPTION
.B cmon
is the cluster monitor daemon for the Ceph distributed file system.
One or more instances
of \fBcmon\fP form a Paxos part-time parliament cluster that provides
extremely reliable and durable storage of cluster membership, configuration,
and state.
.PP
The \fImondatapath\fP refers to a directory on a local file system
storing monitor data.  It is normally specified via the "mon data" option
in the configuration file.
.SH OPTIONS
.TP
\fB\-f\fP, \fB\-\-foreground\f
Foreground: do not daemonize after startup (run in foreground).
Do not generate a pid file. Useful when run via crun (8).
.TP
\fB\-d\fP, \fB\-\-debug\f
Debug mode: like -f, but also send all log output to stderr.
.TP
\fB\-c\fI ceph.conf\fR, \fB\-\-conf=\fIceph.conf\fR
Use \fIceph.conf\fP configuration file instead of the default \fI/etc/ceph/ceph.conf\fP
to determine monitor addresses during startup.
.SH AVAILABILITY
.B cmon
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR ceph (8),
.BR cmds (8),
.BR cosd (8)
