.TH LIBRADOS-CONFIG 8
.SH NAME
librados-config \- display information about librados
.SH SYNOPSIS
.B librados-config
[ \fB\--version\fR ]
[ \fB\--vernum\fR ]

.SH DESCRIPTION
.B librados-config
is a utility that displays information about the installed librados.
.SH OPTIONS
.TP
\fB\-\-version\fR
Display librados version
.TP
\fB\-\-vernum\fR
Display the librados version code
.SH AVAILABILITY
.B librados-config
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR ceph (8), rados (8)
