.TH MKMONFS 8
.SH NAME
mkmonfs \- create a ceph monitor data store
.SH SYNOPSIS
.B mkmonfs
\fIdatadir\fR
\fB\-i \fImonid\fR
\fB\-\-monmap \fImonmapfile\fR
\fB\-\-osdmap \fIosdmapfile\fR
[ \fB\-\-clobber\fR ]
.SH DESCRIPTION
.B mkmonfs
will create a fresh monitor data directory in \fIdatadir\fP for
monitor \fImonid\fP based on the specified \fImonmap\fP and
\fIosdmap\fP.  It will refuse to overwrite any existing data unless
\fB\-\-clobber\fP is specified.
.SH AVAILABILITY
.B mkmonfs
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR osdmaptool (8),
.BR monmaptool (8),
.BR mkcephfs (8)
