.TH RGW 8
.SH NAME
rgw \- rados REST gateway
.SH SYNOPSIS
.B rgw
.SH DESCRIPTION
.B rgw
is an HTTP REST gateway for the RADOS object store, a part of the Ceph
distributed storage system.  It is implemented as a FastCGI module using
libfcgi, and can be used in conjunction any FastCGI capable web server.
.SH OPTIONS
.TP
\fB\-c\fI ceph.conf\fR, \fB\-\-conf=\fIceph.conf\fR
Use \fIceph.conf\fP configuration file instead of the default \fI/etc/ceph/ceph.conf\fP
to determine monitor addresses during startup.
.TP
\fB\-m\fI monaddress[:port]\fR
Connect to specified monitor (instead of looking through \fIceph.conf\fR).
.SH EXAMPLES
To grab a copy of the current OSD map:
.IP
ceph -m 1.2.3.4:6789 osd getmap -o osdmap
.PP
To get a dump of placement group (PG) state:
.IP
ceph pg dump -o pg.txt
.SH AVAILABILITY
.B rgw
is part of the Ceph distributed file system.  Please refer to the Ceph wiki at
http://ceph.newdream.net/wiki for more information.
.SH SEE ALSO
.BR ceph (8)
