diff --git a/fs/Kconfig b/fs/Kconfig
index abccb5d..b4097a7 100644
--- a/fs/Kconfig
+++ b/fs/Kconfig
@@ -1803,6 +1803,20 @@ config RPCSEC_GSS_SPKM3
 
 	  If unsure, say N.
 
+config CEPH_FS
+        tristate "Ceph distributed file system (EXPERIMENTAL)"
+	depends on INET && EXPERIMENTAL
+	select LIBCRC32C
+	help
+	  Choose Y or M here to include support for mounting the
+	  experimental Ceph distributed file system.  Ceph is an extremely
+	  scalable file system designed to provide high performance,
+	  reliable access to petabytes of storage.
+
+	  More information at http://ceph.newdream.net/.
+
+	  If unsure, say N.
+
 config SMB_FS
 	tristate "SMB file system support (OBSOLETE, please use CIFS)"
 	depends on INET
diff --git a/fs/Makefile b/fs/Makefile
index a1482a5..549e129 100644
--- a/fs/Makefile
+++ b/fs/Makefile
@@ -122,3 +122,4 @@ obj-$(CONFIG_HPPFS)		+= hppfs/
 obj-$(CONFIG_DEBUG_FS)		+= debugfs/
 obj-$(CONFIG_OCFS2_FS)		+= ocfs2/
 obj-$(CONFIG_GFS2_FS)           += gfs2/
+obj-$(CONFIG_CEPH_FS)           += ceph/
