teuthology:
  postmerge:
  - |
    -- Tracker #76780: Drop this entire branch. 
    -- FUSE upgrade testing is being moved to a separate dedicated job.
    reject()
tasks:
- ceph-fuse:
    client.0:
      mounted: false
- print: "**** done unmount client.0"
- install.upgrade:
    client.0:
- print: "**** done install.upgrade on client.0"
- ceph.healthy:
- ceph-fuse:
    client.0:
- print: "**** done remount client.0"
