[tox]
envlist = lint, rstcheck, mypy, py3, check-black
skip_missing_interpreters = true

[testenv:py3]
deps=
    -rrequirements.txt
    -c{toxinidir}/../mypy-constrains.txt
commands=
    pytest --doctest-modules ceph/deployment/service_spec.py ceph/utils.py
    pytest {posargs}

[testenv:mypy]
deps=
    -rrequirements.txt
    -c{toxinidir}/../mypy-constrains.txt
    types-grpcio
    types-grpcio-reflection
commands=
    mypy --config-file=../mypy.ini -p ceph

[tool:pytest]
norecursedirs = .* _* virtualenv

[flake8]
max-line-length = 100
exclude =
    __pycache__

[testenv:lint]
deps =
    flake8
commands =
    flake8 {posargs:ceph}

[testenv:rstcheck]
deps =
    rstcheck
commands =
    rstcheck --report-level info  README.rst


# OPT-IN formatting with 'black'
#  add your module to the modules list below to use automated formatting
[black]
deps = black>=23,<25
options = -l78 -t py36 --skip-string-normalization
modules = ceph/cephadm ceph/cryptotools ceph/fs ceph/utils.py ceph/smb

[testenv:check-black]
deps = {[black]deps}
commands =
    black --check -q {[black]options} {[black]modules}

[testenv:format-black]
deps = {[black]deps}
commands =
    black {[black]options} {[black]modules}


# OPT-IN import style formatting with 'isort'
#  add your module to the modules list below to use automated import sorting
[isortcfg]
deps = isort
modules = ceph/smb

[isort]
profile = black
line_length = 78
known_first_party = ceph,rados,rbd,cephfs,mgr
known_typing = typing
sections = FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER

[testenv:check-isort]
deps = {[isortcfg]deps}
commands =
    isort --check-only {[isortcfg]modules}

[testenv:format-isort]
deps = {[isortcfg]deps}
commands =
    isort {[isortcfg]modules}
