#!/usr/bin/perl

# hi there
{
    '_sleep' => 3,
    
    'nummds' => 1,
    'numosd' => 8, #[8],#10,14,16],
    'numclient' => 40, #[10*16],
    '_n' => 32,
        
    '_start' => 20,
    '_end' => 50,
    '_kill_after' => 190,
    
    '_subst' => ['size'],
    'size' => [4096, 
#	       8*1024,
	       16*1024, 
#	       32*1024,
	       64*1024, 
#	       128*1024,
	       256*1024,
	       #					 512*1024,
	       1024*1024
#						 2*1024*1024,
	       #4*1024*1024,
	       ],
    
    'osd_pg_bits' => [4, 6],
    
    '_custom' => '--syn until 55 --syn createobjects 1000000 $size 5',
    
    #'custom' => '--tcp_skip_rank0',
    
    '_comb' => {
	'x' => 'size',
	'vars' => [ 'osd.c_wrb' ]
	}
};
