#!/usr/bin/perl

# hi there
{
    '_sleep' => 3,
    
    'nummds' => 1,
    'numosd' => 16, #[8],#10,14,16],
    'numclient' => 32,#,4,10,20,40], #[10*16],
    '_n' => 32,
        
    '_start' => 15,
    '_end' => 45,
    '_kill_after' => 190,
    
    'osd_pg_bits' => [4, 6],
    'osd_auto_weight' => [0,1],
    'file_layout_pg_size' => [1,2],

    '_custom' => '--syn createobjects 1000000 1048576 2',
    
    '_comb' => {
	'x' => 'osd_pg_bits',
	'vars' => [ 'osd.c_wrb' ]
	}
};
