ARG DISTRO='quay.io/centos/centos:stream8'
FROM $DISTRO

ARG JENKINS_HOME

ARG JENKINS_USER=jenkins
ARG JENKINS_USER_ID=1110
ARG JENKINS_USER_GID=100


SHELL ["bash", "-x", "-c"]

COPY ./ ./
ARG FOR_MAKE_CHECK=1
RUN source run-make-check.sh && prepare
RUN dnf clean all && rm -rf /var/cache/dnf/*

RUN useradd --uid ${JENKINS_USER_ID} --gid ${JENKINS_USER_GID} --create-home ${JENKINS_USER}

USER ${JENKINS_USER}
