#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => 1,
	'numosd' => [8],#10,14,16],
	'numclient' => [10*16],
	'n' => 15,

	'fs' => 'ebofs',

	'start' => 60,
	'end' => 90,
	'until' => 90,  
	'kill_after' => 190,
	
	'writefile' => 1,
	'writefile_size' => [4096, 
						 8*1024,
						 16*1024, 
						 32*1024,
						 64*1024, 
						 128*1024,
						 256*1024,
	#					 512*1024,
#						 4*1024*1024,
#						 2*1024*1024,
#						 1024*1024
],
	'writefile_mb' => 10000,

	'file_layout_num_rep' => 1,
	'file_layout_ssize' => 4*1024*1024,
	'file_layout_osize' => 4*1024*1024,

	'osd_pg_bits' => 12,

#	'ebofs_freelist' => [0, 1080, 65400],

	'custom' => '--objecter_buffer_uncommitted 0',

		#'custom' => '--tcp_skip_rank0',

	'comb' => {
		'x' => 'writefile_size',
		'vars' => [ 'osd.c_wrb', 'cl.wrlat' ]
	}
};
