from threading import Lock
from typing import Any, Dict, Protocol, runtime_checkable


@runtime_checkable
class SystemBackend(Protocol):
    def get_memory(self) -> Dict[str, Any]: ...

    def get_network(self) -> Dict[str, Any]: ...

    def get_storage(self) -> Dict[str, Any]: ...

    def get_processors(self) -> Dict[str, Any]: ...

    def get_power(self) -> Dict[str, Any]: ...

    def get_fans(self) -> Dict[str, Any]: ...

    def get_firmwares(self) -> Dict[str, Any]: ...

    def get_led(self) -> Dict[str, Any]: ...

    def set_led(self, data: Dict[str, str]) -> int: ...

    def get_chassis_led(self) -> Dict[str, Any]: ...

    def chassis_led_on(self) -> int: ...

    def chassis_led_off(self) -> int: ...

    def get_device_led(self, device: str) -> Dict[str, Any]: ...

    def device_led_on(self, device: str) -> int: ...

    def device_led_off(self, device: str) -> int: ...

    def shutdown_host(self, force: bool = False) -> int: ...

    def powercycle(self) -> int: ...

    def flush(self) -> None: ...

    def start(self) -> None: ...

    def shutdown(self) -> None: ...


@runtime_checkable
class SystemForReporter(Protocol):
    lock: Lock
    data_ready: bool
    pending_shutdown: bool
    previous_data: Dict[str, Any]

    def get_system(self) -> Dict[str, Any]: ...
