{
 "title": "Ceph - Filesystem Overview",
 "description": "Ceph CephFS overview for official Ceph Prometheus plugin.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(ceph_fs_metadata, name)"
    }
   },
   {
    "name": "mds_servers",
    "label": "MDS Server",
    "query": "label_values(ceph_mds_inodes{cluster=~\"$cluster\", }, ceph_daemon)"
   },
   {
    "name": "mdatapool",
    "label": "metadata pool",
    "query": {
     "query": "label_values(ceph_fs_metadata{name=~\"$name\"}, metadata_pool)"
    }
   },
   {
    "name": "datapool",
    "label": "data pool",
    "query": {
     "query": "label_values(ceph_fs_metadata{name=~\"$name\"}, data_pools)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active MDS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)"
    }
   ]
  },
  {
   "title": "Metadata Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{pool_id=~\"$mdatapool\"})"
    }
   ]
  },
  {
   "title": "Metadata Bandwidth Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{pool_id=~\"$datapool\"})"
    }
   ]
  },
  {
   "title": "Data Bandwidth Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_server_handle_client_request[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_sessions_session_count * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "MDS Inodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_inodes * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "Metadata Bandwidth Write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data Bandwidth Write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Metadata Used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(ceph_pool_max_avail{pool_id=~\"$mdatapool\"}) / (sum(ceph_pool_bytes_used{pool_id=~\"$mdatapool\"}) + sum(ceph_pool_max_avail{pool_id=~\"$mdatapool\"})))) * 100",
     "legendFormat": "Metadata Used"
    }
   ]
  },
  {
   "title": "Metadata IOPS Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd{pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data Used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(ceph_pool_max_avail{pool_id=~\"$datapool\"}) / (sum(ceph_pool_bytes_used{pool_id=~\"$datapool\"}) + sum(ceph_pool_max_avail{pool_id=~\"$datapool\"})))) * 100",
     "legendFormat": "Data Used"
    }
   ]
  },
  {
   "title": "Data IOPS Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd{pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Forward Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_forward[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "Reply Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ceph_mds_reply_latency_sum[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)) / sum(increase(ceph_mds_reply_latency_count[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "MDS Caps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mds_caps * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))"
    }
   ]
  },
  {
   "title": "Metadata IOPS Write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{pool_id=~\"$mdatapool\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data IOPS Write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{pool_id=~\"$datapool\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "MDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_server_handle_client_request[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Forward Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_forward[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Slave Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_server_handle_slave_request[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_sessions_session_count * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Reply Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (increase(ceph_mds_reply_latency_sum[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)) / sum by (ceph_daemon) (increase(ceph_mds_reply_latency_count[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata))",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "MDS Workload - $mds_servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_objecter_op_r{ceph_daemon=~\"($mds_servers).*\", cluster=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(ceph_objecter_op_w{ceph_daemon=~\"($mds_servers).*\", cluster=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "Write Ops"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Log Submit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_mds_log_evadd{}[$__rate_interval]) * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_log_ev * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Log Segments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_mds_log_seg * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 } }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_mem_ino * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Exported Inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_exported_inodes * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Imported Inodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_imported_inodes * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Dentries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_mem_dn * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    },
    {
     "title": "Caps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_mds_caps * on(ceph_daemon) (ceph_fs_metadata{name=~\"$name\"} * on(fs_id) group_left(ceph_daemon) ceph_mds_metadata)",
       "legendFormat": "{{ ceph_daemon }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Storage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ceph_pool_max_avail{pool_id=~\"^$mdatapool$\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "ceph_pool_bytes_used{pool_id=~\"^$mdatapool$\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "ceph_pool_bytes_used{pool_id=~\"^$mdatapool$\"} + ceph_pool_max_avail{pool_id=~\"^$mdatapool$\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "ceph_pool_raw_bytes_used{pool_id=~\"^$mdatapool$\"}",
       "legendFormat": "Raw Used"
      }
     ]
    },
    {
     "title": "Objects in Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_pool_objects{pool_id=~\"$mdatapool\"}",
       "legendFormat": "Objects"
      },
      {
       "expr": "ceph_pool_dirty{pool_id=~\"$mdatapool\"}",
       "legendFormat": "Dirty Objects"
      },
      {
       "expr": "ceph_pool_quota_objects{pool_id=~\"$mdatapool\"}",
       "legendFormat": "Quota Objects"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceph_pool_bytes_used{pool_id=\"$mdatapool\"} / (ceph_pool_bytes_used{pool_id=\"$mdatapool\"} + ceph_pool_max_avail{pool_id=\"$mdatapool\"})"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ceph_pool_rd{pool_id=~\"$mdatapool\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(ceph_pool_wr{pool_id=~\"$mdatapool\"}[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(ceph_pool_rd_bytes{pool_id=~\"$mdatapool\"}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(ceph_pool_wr_bytes{pool_id=~\"$mdatapool\"}[$__rate_interval])",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Storage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ceph_pool_max_avail{pool_id=~\"^$datapool$\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "ceph_pool_bytes_used{pool_id=~\"^$datapool$\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "ceph_pool_bytes_used{pool_id=~\"^$datapool$\"} + ceph_pool_max_avail{pool_id=~\"^$mdatapool$\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "ceph_pool_raw_bytes_used{pool_id=~\"^$datapool$\"}",
       "legendFormat": "Raw Used"
      }
     ]
    },
    {
     "title": "Objects in Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_pool_objects{pool_id=~\"$datapool\"}",
       "legendFormat": "Objects"
      },
      {
       "expr": "ceph_pool_dirty{pool_id=~\"$datapool\"}",
       "legendFormat": "Dirty Objects"
      },
      {
       "expr": "ceph_pool_quota_objects{pool_id=~\"$datapool\"}",
       "legendFormat": "Quota Objects"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceph_pool_bytes_used{pool_id=\"$datapool\"} / (ceph_pool_bytes_used{pool_id=\"$datapool\"} + ceph_pool_max_avail{pool_id=\"$datapool\"})"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ceph_pool_rd{pool_id=~\"$datapool\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(ceph_pool_wr{pool_id=~\"$datapool\"}[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(ceph_pool_rd_bytes{pool_id=~\"$datapool\"}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(ceph_pool_wr_bytes{pool_id=~\"$datapool\"}[$__rate_interval])",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  }
 ]
}