{
 "title": "Ceph NVMe-oF Gateways",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "gateway",
    "label": "Gateway Hostname",
    "query": {
     "query": "label_values(ceph_nvmeof_gateway_info,hostname)"
    }
   },
   {
    "name": "subsystem",
    "label": "Subsystem NQN",
    "query": {
     "query": "label_values(ceph_nvmeof_subsystem_metadata,nqn)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_gateway_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reactors per Gateway",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(count by(instance) (ceph_nvmeof_reactor_seconds_total{mode=\"busy\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystems",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(nqn) (ceph_nvmeof_subsystem_metadata))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystem Security",
   "type": "stat",
   "description": "WARNING if any subsystem is defined with open/no security",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_subsystem_metadata{allow_any_host=\"yes\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(bdev_name) (ceph_nvmeof_bdev_metadata))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Exported",
   "type": "stat",
   "description": "The sum of capacity from all namespaces defined to subsystems",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,sum by(instance) (ceph_nvmeof_bdev_capacity_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IOPS",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(ceph_nvmeof_bdev_reads_completed_total[30s]) + rate(ceph_nvmeof_bdev_writes_completed_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(ceph_nvmeof_bdev_read_bytes_total[30s]) + rate(ceph_nvmeof_bdev_written_bytes_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busiest Gateway CPU",
   "type": "gauge",
   "description": "Shows the highest average CPU on a gateway within the gateway group",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode=\"busy\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "(ceph_nvmeof_gateway_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top 5 Subsystems by Namespace",
   "type": "bargauge",
   "description": "Show the subsystems by the count of namespaces they present to the client",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, (count by(nqn) (count by(bdev_name, nqn) (ceph_nvmeof_subsystem_namespace_metadata))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Namespace by ANA Group",
   "type": "barchart",
   "description": "Shows the distribution of namespaces by ANA group. Ideally, the namespaces should be evenly distributed across ANA groups.",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(anagrpid) ((count by(anagrpid,bdev_name) (ceph_nvmeof_subsystem_namespace_metadata)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients Connected by Gateway",
   "type": "piechart",
   "description": "Even segments show clients are connected across the gateways in a uniform manner.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(instance) (sum by(instance,host_nqn) (ceph_nvmeof_host_connection_state == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "AVG Reactor CPU Usage by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode=\"busy\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reactor Threads CPU Usage : $gateway",
   "type": "timeseries",
   "description": "Reactor thread CPU busy comes from the SPDK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ceph_nvmeof_reactor_seconds_total{mode=\"busy\", instance=~\"$gateway.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AVG I/O Latency",
   "type": "timeseries",
   "description": "I/O latency as determined by the SPDK ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_read_seconds_total[30s]) / rate(ceph_nvmeof_bdev_reads_completed_total[30s])) > 0)",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_write_seconds_total[30s]) / rate(ceph_nvmeof_bdev_writes_completed_total[30s])) > 0)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "IOPS by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_reads_completed_total[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "\nsum by(nqn) ((rate(ceph_nvmeof_bdev_reads_completed_total[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 5 - IOPS by device for '$subsystem'",
   "type": "timeseries",
   "description": "Shows the busiest rbd images (namespaces) within a given subsystem",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(5, (sum by(pool_name, rbd_name) (((rate(ceph_nvmeof_bdev_reads_completed_total[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_bdev_metadata) * on(instance, bdev_name) group_left(nqn) ceph_nvmeof_subsystem_namespace_metadata{nqn=\"$subsystem\"})))",
     "legendFormat": "{{pool_name}}/{{rbd_name}}"
    }
   ]
  },
  {
   "title": "Throughput by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_read_bytes_total[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "\nsum by(nqn) ((rate(ceph_nvmeof_bdev_read_bytes_total[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 5 - Throughput by device for '$subsystem'",
   "type": "timeseries",
   "description": "Shows the rbd images (namespaces) with the highest throughput in a given subsystem",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, (sum by(pool_name, rbd_name) (((rate(ceph_nvmeof_bdev_read_bytes_total[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_bdev_metadata) * on(instance, bdev_name) group_left(nqn) ceph_nvmeof_subsystem_namespace_metadata{nqn=\"$subsystem\"})))",
     "legendFormat": "{{pool_name}}/{{rbd_name}}"
    }
   ]
  }
 ]
}