{
 "title": "RGW Instance Detail",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{cluster=~\"$cluster\", }, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Host Detail : $rgw_servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_op_get_obj_lat_sum{cluster=~\"$cluster\", }[$__rate_interval]) /\n    rate(ceph_rgw_op_get_obj_lat_count{cluster=~\"$cluster\", }[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "GET {{ceph_daemon}}"
    },
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_op_put_obj_lat_sum{cluster=~\"$cluster\", }[$__rate_interval]) /\n    rate(ceph_rgw_op_put_obj_lat_count{cluster=~\"$cluster\", }[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "PUT {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_op_get_obj_bytes{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_op_put_obj_bytes{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "Requests Failed {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{cluster=~\"$cluster\", }[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{cluster=~\"$cluster\", }[$__rate_interval]) +\n        rate(ceph_rgw_put{cluster=~\"$cluster\", }[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "Other {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "Failures {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{cluster=~\"$cluster\", }[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{cluster=~\"$cluster\", }[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{cluster=~\"$cluster\", }[$__rate_interval]) +\n        rate(ceph_rgw_put{cluster=~\"$cluster\", }[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{ceph_daemon=~\"$rgw_servers\", cluster=~\"$cluster\", }\n",
     "legendFormat": "Other (DELETE,LIST) {{ceph_daemon}}"
    }
   ]
  }
 ]
}