{
 "title": "SMB Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "hostname",
    "query": "label_values(smb_metrics_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "SMB metrics status",
   "type": "stat",
   "description": "SMB metrics health state. \n1 = OK  \n0 = Failed",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(smb_metrics_status{instance=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB active sessions",
   "type": "stat",
   "description": "Number of active SMB sessions, number of users logged in",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(smb_sessions_total{instance=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB ingress throughtput",
   "type": "stat",
   "description": "Current total throughput, bytes going in per second",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_inbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB ingress throughtput - duplicate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_inbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB shares activity",
   "type": "stat",
   "description": "Number of remote machines using a share",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "sum(smb_share_activity{instance=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB latency",
   "type": "stat",
   "description": "Current total request time for the sum of all runing operations",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB egress throughtput",
   "type": "stat",
   "description": "Current total egress throughput, bytes going out per second",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_outbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMB throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_inbytes{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "Inbytes.{{instance}}.{{operation}}"
    },
    {
     "expr": "rate(smb_smb2_request_outbytes{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "Outbytes.{{instance}}.{{operation}}"
    }
   ]
  },
  {
   "title": "SMB I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_total{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{instance}}.{{operation}}"
    }
   ]
  },
  {
   "title": "SMB latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{instance}}.{{operation}}"
    }
   ]
  }
 ]
}