# Tests for various assorted utility functions found within cephadm
#
from unittest import mock

import functools
import io
import os
import sys

import pytest

from tests.fixtures import (
    import_cephadm,
    mock_docker,
    mock_podman,
    with_cephadm_ctx,
)

from cephadmlib import context
from cephadmlib import systemd_unit
from cephadmlib.constants import CGROUPS_SPLIT_PODMAN_VERSION
from cephadmlib.daemon_identity import DaemonIdentity

_cephadm = import_cephadm()


def _get_unit_file(ctx, fsid):
    return str(systemd_unit._get_unit_file(ctx, fsid))


def test_docker_engine_wants_docker():
    ctx = context.CephadmContext()
    ctx.container_engine = mock_docker()
    r = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert 'Wants=docker.service' in r


def test_podman_engine_does_not_req_docker():
    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    r = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert 'Requires=docker.service' not in r


def test_podman_engine_forking_service():
    # verity that the podman service uses the forking service type
    # and related parameters
    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    r = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert 'Type=forking' in r
    assert 'PIDFile=' in r
    assert 'ExecStartPre' in r
    assert 'ExecStopPost' in r


def test_podman_with_split_cgroups_sets_delegate():
    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    ctx.container_engine.version = CGROUPS_SPLIT_PODMAN_VERSION
    r = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert 'Type=forking' in r
    assert 'Delegate=yes' in r


def _ignore_blank_lines(value):
    return [v for v in value.splitlines() if v]


def test_new_docker():
    ctx = context.CephadmContext()
    ctx.container_engine = mock_docker()
    ru = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert _ignore_blank_lines(ru) == [
        '# generated by cephadm',
        '[Unit]',
        'Description=Ceph %i for 9b9d7609-f4d5-4aba-94c8-effa764d96c9',
        '# According to:',
        '#   http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget',
        '# these can be removed once ceph-mon will dynamically change network',
        '# configuration.',
        'After=network-online.target local-fs.target time-sync.target docker.service',
        'Wants=network-online.target local-fs.target time-sync.target',
        'Wants=docker.service',
        'PartOf=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
        'Before=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
        '[Service]',
        'LimitNOFILE=1048576',
        'LimitNPROC=1048576',
        'EnvironmentFile=-/etc/environment',
        'ExecStart=/bin/bash '
        '/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.run %t/%n-pid',
        "ExecStop=-/bin/bash -c 'bash "
        "/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.stop'",
        'ExecStopPost=-/bin/bash '
        '/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.poststop',
        'KillMode=none',
        'RestartSec=10s',
        'TimeoutStartSec=200',
        'TimeoutStopSec=120',
        'StartLimitInterval=30min',
        'StartLimitBurst=5',
        'Type=forking',
        'PIDFile=%t/%n-pid',
        'Restart=always',
        'ExecStartPre=-/bin/rm -f %t/%n-pid',
        '[Install]',
        'WantedBy=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
    ]


def test_new_podman():
    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    ctx.container_engine.version = CGROUPS_SPLIT_PODMAN_VERSION
    ru = _get_unit_file(ctx, '9b9d7609-f4d5-4aba-94c8-effa764d96c9')
    assert _ignore_blank_lines(ru) == [
        '# generated by cephadm',
        '[Unit]',
        'Description=Ceph %i for 9b9d7609-f4d5-4aba-94c8-effa764d96c9',
        '# According to:',
        '#   http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget',
        '# these can be removed once ceph-mon will dynamically change network',
        '# configuration.',
        'After=network-online.target local-fs.target time-sync.target',
        'Wants=network-online.target local-fs.target time-sync.target',
        'PartOf=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
        'Before=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
        '[Service]',
        'LimitNOFILE=1048576',
        'LimitNPROC=1048576',
        'EnvironmentFile=-/etc/environment',
        'ExecStart=/bin/bash '
        '/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.run',
        "ExecStop=-/bin/bash -c 'bash "
        "/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.stop'",
        'ExecStopPost=-/bin/bash '
        '/var/lib/ceph/9b9d7609-f4d5-4aba-94c8-effa764d96c9/%i/unit.poststop',
        'KillMode=none',
        'RestartSec=10s',
        'TimeoutStartSec=200',
        'TimeoutStopSec=120',
        'StartLimitInterval=30min',
        'StartLimitBurst=5',
        'Restart=on-failure',
        'ExecStartPre=-/bin/rm -f %t/%n-pid %t/%n-cid',
        'ExecStopPost=-/bin/rm -f %t/%n-pid %t/%n-cid',
        'Type=forking',
        'PIDFile=%t/%n-pid',
        'Delegate=yes',
        '[Install]',
        'WantedBy=ceph-9b9d7609-f4d5-4aba-94c8-effa764d96c9.target',
    ]


_FSID = '9b9d7609-f4d5-4aba-94c8-effa764d96c9'


def test_success_exit_status_drop_in_written(tmp_path):
    """When exit codes are provided, a drop-in with SuccessExitStatus is
    written into the service's .d/ directory."""
    ident = DaemonIdentity(_FSID, 'node-exporter', 'ceph-node-00')
    pinfo = systemd_unit.PathInfo(tmp_path, ident)
    systemd_unit._install_success_exit_status_drop_in(
        pinfo, ident, [143]
    )
    fname = systemd_unit._SUCCESS_EXIT_STATUS_DROP_IN_FMT.format(
        daemon_type='node-exporter'
    )
    drop_in = pinfo.drop_in_file.parent / fname
    assert drop_in.exists()
    assert fname == '90-cephadm-node-exporter.conf'
    content = drop_in.read_text()
    assert '[Service]' in content
    assert 'SuccessExitStatus=143' in content


def test_success_exit_status_drop_in_not_written_for_empty_list(tmp_path):
    """When exit codes list is empty, no drop-in is created."""
    ident = DaemonIdentity(_FSID, 'mgr', 'host1')
    pinfo = systemd_unit.PathInfo(tmp_path, ident)
    systemd_unit._install_success_exit_status_drop_in(
        pinfo, ident, []
    )
    fname = systemd_unit._SUCCESS_EXIT_STATUS_DROP_IN_FMT.format(
        daemon_type='mgr'
    )
    drop_in = pinfo.drop_in_file.parent / fname
    assert not drop_in.exists()


@mock.patch('cephadmlib.daemons.monitoring.Monitoring._prevalidate')
@mock.patch('cephadmlib.daemons.monitoring.daemon_to_container')
@mock.patch('cephadmlib.daemons.monitoring.to_deployment_container')
def test_monitoring_node_exporter_container_has_success_exit_status(
    _to_deploy, _to_ctr, _preval
):
    """Monitoring.container() sets success_exit_status=[143] for
    node-exporter."""
    from cephadmlib.daemons.monitoring import Monitoring
    from cephadmlib.container_types import CephContainer

    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    fake_ctr = mock.MagicMock(spec=CephContainer)
    fake_ctr.success_exit_status = None
    _to_deploy.return_value = fake_ctr
    ident = DaemonIdentity(_FSID, 'node-exporter', 'host1')
    daemon = Monitoring(ctx, ident)
    ctr = daemon.container(ctx)
    assert ctr.success_exit_status == [143]


@mock.patch('cephadmlib.daemons.monitoring.Monitoring._prevalidate')
@mock.patch('cephadmlib.daemons.monitoring.daemon_to_container')
@mock.patch('cephadmlib.daemons.monitoring.to_deployment_container')
@pytest.mark.parametrize(
    'daemon_type',
    ['prometheus', 'grafana', 'alertmanager', 'loki', 'promtail'],
)
def test_monitoring_other_types_no_success_exit_status(
    _to_deploy, _to_ctr, _preval, daemon_type
):
    """Monitoring.container() leaves success_exit_status as None for
    non-node-exporter types."""
    from cephadmlib.daemons.monitoring import Monitoring
    from cephadmlib.container_types import CephContainer

    ctx = context.CephadmContext()
    ctx.container_engine = mock_podman()
    fake_ctr = mock.MagicMock(spec=CephContainer)
    fake_ctr.success_exit_status = None
    _to_deploy.return_value = fake_ctr
    ident = DaemonIdentity(_FSID, daemon_type, 'host1')
    daemon = Monitoring(ctx, ident)
    ctr = daemon.container(ctx)
    assert ctr.success_exit_status is None
