overrides:
  ceph:
    log-ignorelist:
      - is full \(reached quota
      - POOL_FULL
    conf:
      mgr:
        debug client: 10

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_mirroring.TestMirroring
