overrides:
  ceph:
    log-ignorelist:
      - MIRRORING_FAILURE
    conf:
      mgr:
        debug client: 10

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_mirroring.TestMirroring
