set -e
# alertmanager.ceph-node-0
! /usr/bin/podman rm -f ceph-8d852aba-0bac-11ef-b9f3-5254000370c4-alertmanager.ceph-node-0 2> /dev/null
! /usr/bin/podman rm -f ceph-8d852aba-0bac-11ef-b9f3-5254000370c4-alertmanager-ceph-node-0 2> /dev/null
! /usr/bin/podman rm -f --storage ceph-8d852aba-0bac-11ef-b9f3-5254000370c4-alertmanager-ceph-node-0 2> /dev/null
! /usr/bin/podman rm -f --storage ceph-8d852aba-0bac-11ef-b9f3-5254000370c4-alertmanager.ceph-node-0 2> /dev/null
/usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --init --name ceph-8d852aba-0bac-11ef-b9f3-5254000370c4-alertmanager-ceph-node-0 --user 65534 -d --log-driver journald --conmon-pidfile /run/ceph-8d852aba-0bac-11ef-b9f3-5254000370c4@alertmanager.ceph-node-0.service-pid --cidfile /run/ceph-8d852aba-0bac-11ef-b9f3-5254000370c4@alertmanager.ceph-node-0.service-cid --cgroups=split -e CONTAINER_IMAGE=quay.io/prometheus/alertmanager:v0.25.0 -e NODE_NAME=ceph-node-0 -v /var/lib/ceph/8d852aba-0bac-11ef-b9f3-5254000370c4/alertmanager.ceph-node-0/etc/alertmanager:/etc/alertmanager:Z -v /etc/hosts:/etc/hosts:ro quay.io/prometheus/alertmanager:v0.25.0 --cluster.listen-address=:9094 --web.listen-address=:9093 --config.file=/etc/alertmanager/alertmanager.yml --web.external-url='http://192.168.100.100:9093/alertmanager' --web.route-prefix="/alertmanager"
