"""Canonical errorCode string values for the S3 Files API.

Mirrors src/rgw/rgw_s3files_errors.h — the C++ header is the
source of truth; this file must be kept in sync. Tests import
from here so the conformance suite asserts against the
documented set rather than scattering string literals.

The Smithy spec types each errorCode member as just a non-empty
string. The values below are RGW-defined and stable; clients
should treat the exception type (ValidationException,
ConflictException, etc.) as the primary classification and the
errorCode as an operator-debug identifier.
"""

# Validation (HTTP 400, ValidationException)
INVALID_BUCKET_ARN = "INVALID_BUCKET_ARN"
INVALID_BUCKET_REGION = "INVALID_BUCKET_REGION"
INVALID_ROLE_ARN = "INVALID_ROLE_ARN"
INVALID_PREFIX = "INVALID_PREFIX"
INVALID_KMS_KEY = "INVALID_KMS_KEY"
INVALID_ROOT_DIRECTORY = "INVALID_ROOT_DIRECTORY"
INVALID_POSIX_USER = "INVALID_POSIX_USER"
INVALID_ZONE_ID = "INVALID_ZONE_ID"
ZONE_NOT_IN_ZONEGROUP = "ZONE_NOT_IN_ZONEGROUP"
INVALID_POLICY_DOCUMENT = "INVALID_POLICY_DOCUMENT"
INVALID_TAG_KEY = "INVALID_TAG_KEY"
INVALID_TAG_VALUE = "INVALID_TAG_VALUE"
BUCKET_CONFIGURATION_WARNING = "BUCKET_CONFIGURATION_WARNING"
INVALID_MAX_RESULTS = "INVALID_MAX_RESULTS"
INVALID_SYNC_RULES = "INVALID_SYNC_RULES"

# Not-found (HTTP 404, ResourceNotFoundException)
BUCKET_NOT_FOUND = "BUCKET_NOT_FOUND"
ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
FILE_SYSTEM_NOT_FOUND = "FILE_SYSTEM_NOT_FOUND"
ACCESS_POINT_NOT_FOUND = "ACCESS_POINT_NOT_FOUND"
MOUNT_TARGET_NOT_FOUND = "MOUNT_TARGET_NOT_FOUND"
POLICY_NOT_FOUND = "POLICY_NOT_FOUND"

# Conflict (HTTP 409, ConflictException)
FILE_SYSTEM_ALREADY_EXISTS = "FILE_SYSTEM_ALREADY_EXISTS"
BUCKET_ALREADY_IN_USE = "BUCKET_ALREADY_IN_USE"
FILE_SYSTEM_HAS_CHILDREN = "FILE_SYSTEM_HAS_CHILDREN"
FILE_SYSTEM_IN_INVALID_STATE = "FILE_SYSTEM_IN_INVALID_STATE"
MOUNT_TARGET_ALREADY_IN_ZONE = "MOUNT_TARGET_ALREADY_EXISTS_IN_ZONE"
PLACEMENT_NOT_BOUND_IN_ZONE = "PLACEMENT_NOT_BOUND_IN_ZONE"
UNRESOLVED_NFS_SERVICE = "UNRESOLVED_NFS_SERVICE"

# Quota (HTTP 402, ServiceQuotaExceededException)
TOO_MANY_FILE_SYSTEMS = "TOO_MANY_FILE_SYSTEMS"
TOO_MANY_ACCESS_POINTS = "TOO_MANY_ACCESS_POINTS"
TOO_MANY_MOUNT_TARGETS = "TOO_MANY_MOUNT_TARGETS"
TOO_MANY_TAGS = "TOO_MANY_TAGS"
POLICY_TOO_LARGE = "POLICY_TOO_LARGE"

# Throttling (HTTP 429, ThrottlingException)
THROTTLED = "THROTTLED"

# Server-side (HTTP 500, InternalServerException)
INTERNAL = "INTERNAL"
BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
