#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 2, 4, 8, 16, 32, 48, 64, 80, 96],

	'cper' => 50,
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$cnode * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd' ],
	
	# parameters
	#'fs' => 'ebofs',
	'fs' => 'fakestore',

	'until' => 300,     # --syn until $n    ... when to stop clients
	'kill_after' => 400,
	'start' => 100,
	'end' => 300,
	
	'makedirs' => 1,
	'makedirs_dirs' => 10,
	'makedirs_files' => 10,
	'makedirs_depth' => 3,
		
	'custom' => '--tcp_skip_rank0 --mds_shutdown_check 60',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req' ]
	}
};
