#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 4, 16, 64, 128, 192 ],

	'cper' => [10, 50, 100, 150],
	'_dep' => [ 'cnode' => '$nummds',# > 30 ? 30:$nummds',
				'numclient' => '$nummds*$cper',
				'numosd' => '$nummds > 30 ? 30:$nummds',
				'n' => '1 + $cnode + $nummds + $numosd' ],
	
	# parameters
	'fs' => 'ebofs',

	'mds_bal_interval' => 10000,
	'mds_bal_hash_wr' => 1000,

	'until' => 120,     # --syn until $n    ... when to stop clients
	'kill_after' => 180,
	'start' => 10,
	'end' => 120,
	
	'custom' => '--tcp_skip_rank0 --debug_mds_balancer 10 --mds_shutdown_check 60 --syn only 0 --syn createshared 10 --syn sleep 5 --syn openshared 10 10000',
	
	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req', 'cl.lat' ]
	}
};
