#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 2, 4, 8, 16, 32, 48, 64, 80, 96],

	'cper' => 50,
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$cnode * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd' ],
	
	# parameters
	#'fs' => 'ebofs',
	'fs' => 'fakestore',

	'until' => 300,     # --syn until $n    ... when to stop clients
	'kill_after' => 400,
	'start' => 100,
	'end' => 550,
	
	'custom' => '--tcp_skip_rank0 --mds_shutdown_check 60 --syn only 0 --syn createshared 10 --syn sleep 5 --syn openshared 10 10000',
	
	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req' ]
	}
};
