#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 2, 4, 8, 16, 32, 48, 64, 80, 96],

	'trace' => ['make','make.lib','make.include'],

	'cper' => [ 50, 100 ],
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$cnode * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd',
				'custom' => '"--tcp_skip_rank0 --mds_shutdown_check 60 --syn only 0 --syn trace traces/openssh/untar.lib 1 --syn only 1 --syn trace traces/openssh/untar.include 1 --syn randomsleep 30 --syn trace traces/openssh/$trace 1000"' ],
	
	# parameters
	#'fs' => 'ebofs',
	'fs' => 'fakestore',

	'until' => 500,   
	'kill_after' => 600,
	'start' => 200,
	'end' => 500,
	
	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req' ]
	}
};
