#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => 1,
	'numosd' => 10,

	'cnode' => 10, 
	'cper' => [ 10, 25, 50, 100 ],

	'_dep' => [ 'numclient' => '$cper * $cnode',
				'n' => '1 + $cnode + $nummds + $numosd',
				'file_layout_osize' => '$writefile_size' ],
	
	# parameters
	'fs' => 'ebofs',
	#'fs' => 'fakestore',
	
	'until' => 160,     # --syn until $n    ... when to stop clients
	'kill_after' => 200,
	'start' => 100,
	'end' => 160,
	
	'writefile' => 1,
	'writefile_size' => [ 
#						  4*1024*1024,
						  1024*1024 ],
#						  256*1024,
#						  64*1024 
	'writefile_mb' => 100000,

		'osd_pg_bits' => 10,#16,
		#'osd_pg_bits' => [ 16, 20 ],
	
		#'osd_object_layout' => [ 'hash', 'hashino', 'linear' ],
	'osd_pg_layout' => [ 'crush', 
#						 'hash', 
						 'linear' ],

	'custom' => '--tcp_skip_rank0 --file_layout_num_rep 1 --mds_shutdown_check 60',
	
	'comb' => {
		'x' => 'cper',#writefile_size',
		'vars' => [ 'osd.c_wrb', 'osd.c_wr' ],
	}
};
