#!/usr/bin/perl

# hi there
{
	#'_psub' => 'jobs/alc.tp',
	'sleep' => 3,

	'nummds' => 1,
	'numclient' => [5, 10, 15, 25, 50, 100, 200, 300, 400],
	#'numclient' => [ 50, 100, 200 ],
	'numosd' => [2,4],#[ 4, 8, 12, 16, 20, 24 ], 
	'n' => 12,

	# parameters
	'fs' => 'fakestore',#['fakestore','obfs'],
	#'fs' => 'ebofs',
	#'osd_maxthreads' => [ 0, 1, 2, 4, 8 ],

	'until' => 100,     # --syn until $n    ... when to stop clients
	'kill_after' => 300,
	'start' => 20,
	'end' => 90,
	
	'makedirs' => 1,
	'makedirs_dirs' => 10,
	'makedirs_files' => 10,
	'makedirs_depth' => 3,
		

	#'meta_log_layout_ssize' => [256, 512, 1024, 4096, 16384, 65536, 262400],
	#'meta_log_layout_scount' => [2, 4, 8],
	#'meta_log_layout_num_rep' => [1, 2],
	#'meta_log_layout_num_rep' => 1,

	'custom' => '--tcp_skip_rank0 --mds_shutdown_check 60',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	'comb' => {
		'x' => 'numclient',#'meta_log_layout_ssize',
		'vars' => [ 'mds.req' ]
	}
};
