#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => 1,
	'numosd' => [12],
	'numclient' => [1],#, 40, 80, 160 ],
	'n' => 16,

	'fs' => 'ebofs',

	'start' => 10,
	'end' => 40,
	'until' => 40,  
	'kill_after' => 90,
	
	'writefile' => 1,
	'writefile_size' => [4096, 
						 8*1024,
						 16*1024, 
						 32*1024,
						 64*1024,
						 128*1024,
						 256*1024,
						 512*1024,
						 1024*1024],
	'writefile_mb' => 10000,

	#'tcp_multi_out' => [0,1],

#		'mds_local_osd' => [ 0, 1 ],
	'file_layout_num_rep' => [1,2,3],#, 2, 3, 4],

	'client_oc' => [0,1],
		
	'custom' => '--tcp_skip_rank0',

	'comb' => {
		'x' => 'writefile_size',#'file_layout_num_rep',
		'vars' => [ 'osd.c_wrb','cl.wrlat' ]
	}
};
