#!/usr/bin/perl
# hi there
{
	# startup
	'n' => 30,          # mpi nodes
	'sleep' => 3,      # seconds between runs
	'nummds' => 1,
	'numosd' => 6,
	'numclient' => 100,#[25,50,100,300],#100,#[10, 50, 100, 200, 400],
	
	'until' => 100,     # --syn until $n    ... when to stop clients
	'kill_after' => 300,

	# parameters
	'fs' => [ 
#			  'obfs',
			  'fakestore',
#			  'ebofs' 
			  ],
	'writefile' => 1,
	'writefile_size' => [ 
#						  2048*1024,
						  1024*1024,
						  512*1024,
						  256*1024,
						  128*1024,
						  64*1024,
						  48*1024,
						  32*1024,
						  28*1024,
						  24*1024,
						  16*1024,
						  12*1024,
						  8*1024,
						  4096,
#						  256,
#						  16,
#						  1
						  ],
	'writefile_mb' => 1000,
	
	'file_layout_num_rep'=> 1,#[1,2],

	'custom' => '--debug_after 110 --debug_mds 15 --debug 5 --mds_shutdown_check 60',

	# for final summation (script/sum.pl)
	'start' => 30,
	'end' => 90,

	'comb' => {
		'x' => 'writefile_size',
		'vars' => [ 'osd.c_wrb' ],
#			'maptitle' => { 'osd_object_layout=' => '',
#							',osd_pg_layout=' => ' + '}
	}
};
