export enum rgwEncryptionConfigKeys {
  auth = 'Authentication Method',
  encryption_type = 'Encryption Type',
  backend = 'Backend',
  prefix = 'Prefix',
  namespace = 'Namespace',
  secret_engine = 'Secret Engine',
  addr = 'Address',
  token_file = 'Token File',
  ssl_cacert = 'SSL CA Certificate',
  ssl_clientcert = 'SSL Client Certificate',
  ssl_clientkey = 'SSL Client Key',
  verify_ssl = 'Verify SSL',
  ca_path = 'CA Path',
  client_cert = 'Client Certificate',
  client_key = 'Client Key',
  kms_key_template = 'KMS Key Template',
  password = 'Password',
  s3_key_template = 'S3 Key Template',
  username = 'Username'
}
