# vi: set ft=ruby :

NUM_DAEMONS = ENV["NUM_DAEMONS"] ? ENV["NUM_DAEMONS"].to_i : 1

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", type: "dhcp"
  # config.vm.box = "centos/7"
  config.vm.box = "opensuse/Tumbleweed.x86_64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = "1024"
  end

  (0..NUM_DAEMONS - 1).each do |i|
    config.vm.define "mon#{i}" do |mon|
      mon.vm.hostname = "mon#{i}"
    end
    config.vm.define "mgr#{i}" do |mgr|
      mgr.vm.hostname = "mgr#{i}"
    end
    config.vm.define "osd#{i}" do |osd|
      osd.vm.hostname = "osd#{i}"
      osd.vm.provider :libvirt do |libvirt|
        libvirt.storage :file, :size => '5G'
        libvirt.storage :file, :size => '5G'
      end
    end
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    sudo cp -r /home/vagrant/.ssh /root/.ssh
  SHELL

  if config.vm.box == "centos/7"
    config.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y yum-utils
      sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      sudo rpm --import 'https://download.ceph.com/keys/release.asc'
      curl -L https://shaman.ceph.com/api/repos/ceph/master/latest/centos/7/repo/ | sudo tee /etc/yum.repos.d/shaman.repo
      sudo yum install -y python36 podman ceph
      sudo ln -s /usr/bin/python36 /usr/bin/python3 || true
    SHELL
  end

  if config.vm.box == "opensuse/Tumbleweed.x86_64"
    config.vm.provision "shell", inline: <<-SHELL
      sudo systemctl restart systemd-timesyncd.service
      sudo systemctl enable systemd-timesyncd.service
      sudo zypper addrepo https://download.opensuse.org/repositories/filesystems:ceph:master:upstream/openSUSE_Tumbleweed/filesystems:ceph:master:upstream.repo
      sudo zypper --non-interactive --gpg-auto-import-keys refresh
      sudo zypper --non-interactive install -y nano podman ceph salt-minion || true
      sudo echo "master: mgr0" > /etc/salt/minion
      sudo systemctl restart salt-minion
      sudo systemctl enable salt-minion
    SHELL

    config.vm.define "mgr0" do |mgr|
      mgr.vm.provision "shell", inline: <<-SHELL
        sudo zypper --non-interactive install -y ceph-bootstrap || true
        sudo systemctl restart salt-master
        sudo systemctl enable salt-master
        sleep 20
        sudo salt-key -y -A || true
        sleep 5
        sudo ceph-bootstrap config /Cluster/Minions add \*
        sudo ceph-bootstrap config /Cluster/Roles/Mon add mon\*
        sudo ceph-bootstrap config /Cluster/Roles/Mgr add mgr\*
        sudo ceph-bootstrap deploy
      SHELL
    end
  end
end
