# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_pb2 as mainServer__pb2


class GeneralStub(object):
  """-------------------------- General -------------------------------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GeneralHeartbeat = channel.unary_unary(
        '/proto.General/GeneralHeartbeat',
        request_serializer=mainServer__pb2.Empty.SerializeToString,
        response_deserializer=mainServer__pb2.GeneralHeartbeatOutput.FromString,
        )
    self.Ping = channel.unary_unary(
        '/proto.General/Ping',
        request_serializer=mainServer__pb2.Empty.SerializeToString,
        response_deserializer=mainServer__pb2.PingOutout.FromString,
        )
    self.Test = channel.unary_unary(
        '/proto.General/Test',
        request_serializer=mainServer__pb2.TestInput.SerializeToString,
        response_deserializer=mainServer__pb2.TestOutput.FromString,
        )


class GeneralServicer(object):
  """-------------------------- General -------------------------------------
  """

  def GeneralHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GeneralServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GeneralHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.GeneralHeartbeat,
          request_deserializer=mainServer__pb2.Empty.FromString,
          response_serializer=mainServer__pb2.GeneralHeartbeatOutput.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=mainServer__pb2.Empty.FromString,
          response_serializer=mainServer__pb2.PingOutout.SerializeToString,
      ),
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=mainServer__pb2.TestInput.FromString,
          response_serializer=mainServer__pb2.TestOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.General', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AccountStub(object):
  """-------------------------- SERVER ACCOUNT ------------------------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AccountHeartbeat = channel.unary_unary(
        '/proto.Account/AccountHeartbeat',
        request_serializer=mainServer__pb2.Empty.SerializeToString,
        response_deserializer=mainServer__pb2.AccountHeartbeatOutput.FromString,
        )
    self.Login = channel.unary_unary(
        '/proto.Account/Login',
        request_serializer=mainServer__pb2.LoginInput.SerializeToString,
        response_deserializer=mainServer__pb2.UserOutput.FromString,
        )
    self.Signup = channel.unary_unary(
        '/proto.Account/Signup',
        request_serializer=mainServer__pb2.SingupInput.SerializeToString,
        response_deserializer=mainServer__pb2.SingupOutput.FromString,
        )
    self.ResendConfirmCode = channel.unary_unary(
        '/proto.Account/ResendConfirmCode',
        request_serializer=mainServer__pb2.ResendConfirmCodeInput.SerializeToString,
        response_deserializer=mainServer__pb2.GeneralMsgOutput.FromString,
        )
    self.Confirm = channel.unary_unary(
        '/proto.Account/Confirm',
        request_serializer=mainServer__pb2.ConfirmInput.SerializeToString,
        response_deserializer=mainServer__pb2.GeneralMsgOutput.FromString,
        )
    self.GetUsersByStatus = channel.unary_unary(
        '/proto.Account/GetUsersByStatus',
        request_serializer=mainServer__pb2.GetUsersByStatusInput.SerializeToString,
        response_deserializer=mainServer__pb2.GetUsersByStatusOutput.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/proto.Account/DeleteUser',
        request_serializer=mainServer__pb2.DeleteUserInput.SerializeToString,
        response_deserializer=mainServer__pb2.GeneralMsgOutput.FromString,
        )
    self.UpdateUserStatus = channel.unary_unary(
        '/proto.Account/UpdateUserStatus',
        request_serializer=mainServer__pb2.UpdateUserStatusInput.SerializeToString,
        response_deserializer=mainServer__pb2.GeneralMsgOutput.FromString,
        )


class AccountServicer(object):
  """-------------------------- SERVER ACCOUNT ------------------------------
  """

  def AccountHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Signup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResendConfirmCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Confirm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsersByStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AccountHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.AccountHeartbeat,
          request_deserializer=mainServer__pb2.Empty.FromString,
          response_serializer=mainServer__pb2.AccountHeartbeatOutput.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=mainServer__pb2.LoginInput.FromString,
          response_serializer=mainServer__pb2.UserOutput.SerializeToString,
      ),
      'Signup': grpc.unary_unary_rpc_method_handler(
          servicer.Signup,
          request_deserializer=mainServer__pb2.SingupInput.FromString,
          response_serializer=mainServer__pb2.SingupOutput.SerializeToString,
      ),
      'ResendConfirmCode': grpc.unary_unary_rpc_method_handler(
          servicer.ResendConfirmCode,
          request_deserializer=mainServer__pb2.ResendConfirmCodeInput.FromString,
          response_serializer=mainServer__pb2.GeneralMsgOutput.SerializeToString,
      ),
      'Confirm': grpc.unary_unary_rpc_method_handler(
          servicer.Confirm,
          request_deserializer=mainServer__pb2.ConfirmInput.FromString,
          response_serializer=mainServer__pb2.GeneralMsgOutput.SerializeToString,
      ),
      'GetUsersByStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsersByStatus,
          request_deserializer=mainServer__pb2.GetUsersByStatusInput.FromString,
          response_serializer=mainServer__pb2.GetUsersByStatusOutput.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=mainServer__pb2.DeleteUserInput.FromString,
          response_serializer=mainServer__pb2.GeneralMsgOutput.SerializeToString,
      ),
      'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserStatus,
          request_deserializer=mainServer__pb2.UpdateUserStatusInput.FromString,
          response_serializer=mainServer__pb2.GeneralMsgOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Account', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DiskprophetStub(object):
  """------------------------ SERVER DISKPROPHET ---------------------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DPHeartbeat = channel.unary_unary(
        '/proto.Diskprophet/DPHeartbeat',
        request_serializer=mainServer__pb2.Empty.SerializeToString,
        response_deserializer=mainServer__pb2.DPHeartbeatOutput.FromString,
        )
    self.DPGetPhysicalDisks = channel.unary_unary(
        '/proto.Diskprophet/DPGetPhysicalDisks',
        request_serializer=mainServer__pb2.DPGetPhysicalDisksInput.SerializeToString,
        response_deserializer=mainServer__pb2.DPBinaryOutput.FromString,
        )
    self.DPGetDisksPrediction = channel.unary_unary(
        '/proto.Diskprophet/DPGetDisksPrediction',
        request_serializer=mainServer__pb2.DPGetDisksPredictionInput.SerializeToString,
        response_deserializer=mainServer__pb2.DPBinaryOutput.FromString,
        )


class DiskprophetServicer(object):
  """------------------------ SERVER DISKPROPHET ---------------------------
  """

  def DPHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DPGetPhysicalDisks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DPGetDisksPrediction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiskprophetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DPHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.DPHeartbeat,
          request_deserializer=mainServer__pb2.Empty.FromString,
          response_serializer=mainServer__pb2.DPHeartbeatOutput.SerializeToString,
      ),
      'DPGetPhysicalDisks': grpc.unary_unary_rpc_method_handler(
          servicer.DPGetPhysicalDisks,
          request_deserializer=mainServer__pb2.DPGetPhysicalDisksInput.FromString,
          response_serializer=mainServer__pb2.DPBinaryOutput.SerializeToString,
      ),
      'DPGetDisksPrediction': grpc.unary_unary_rpc_method_handler(
          servicer.DPGetDisksPrediction,
          request_deserializer=mainServer__pb2.DPGetDisksPredictionInput.FromString,
          response_serializer=mainServer__pb2.DPBinaryOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Diskprophet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CollectionStub(object):
  """------------------------ SERVER Collection ---------------------------

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectionHeartbeat = channel.unary_unary(
        '/proto.Collection/CollectionHeartbeat',
        request_serializer=mainServer__pb2.Empty.SerializeToString,
        response_deserializer=mainServer__pb2.CollectionHeartbeatOutput.FromString,
        )
    self.PostDBRelay = channel.unary_unary(
        '/proto.Collection/PostDBRelay',
        request_serializer=mainServer__pb2.PostDBRelayInput.SerializeToString,
        response_deserializer=mainServer__pb2.CollectionMessageOutput.FromString,
        )
    self.PostMetrics = channel.unary_unary(
        '/proto.Collection/PostMetrics',
        request_serializer=mainServer__pb2.PostMetricsInput.SerializeToString,
        response_deserializer=mainServer__pb2.CollectionMessageOutput.FromString,
        )


class CollectionServicer(object):
  """------------------------ SERVER Collection ---------------------------

  """

  def CollectionHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostDBRelay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CollectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectionHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.CollectionHeartbeat,
          request_deserializer=mainServer__pb2.Empty.FromString,
          response_serializer=mainServer__pb2.CollectionHeartbeatOutput.SerializeToString,
      ),
      'PostDBRelay': grpc.unary_unary_rpc_method_handler(
          servicer.PostDBRelay,
          request_deserializer=mainServer__pb2.PostDBRelayInput.FromString,
          response_serializer=mainServer__pb2.CollectionMessageOutput.SerializeToString,
      ),
      'PostMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.PostMetrics,
          request_deserializer=mainServer__pb2.PostMetricsInput.FromString,
          response_serializer=mainServer__pb2.CollectionMessageOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Collection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
