#!/bin/sh -e

branch="$1"
if [ -z "$branch" ]; then branch="master"; fi

export COVDIR="$HOME/cov-analysis"
if [ ! -d "$COVDIR" ]; then
    echo "missing $COVDIR; get that from coverity!"
    exit 1
fi
if [ ! -e "$HOME/coverity_rsa" ]; then
    echo "missing ssh key for results upload"
    exit 1
fi
if [ ! -e "$HOME/coverity.build.pass.txt" ]; then
    echo "missing $HOME/coverity.build.pass.txt"
    exit 1
fi

export PATH="$COVDIR/bin:$PATH"

git fetch
git reset --hard origin/$branch
cd ..
git submodule update
cd src
rm -f project.tgz
make project.tgz

version=`git describe`
token=`cat ~/coverity.build.pass.txt`
curl --form token=$token \
  --form email=sage@newdream.net \
  --form file=@project.tgz \
  --form version="$version" \
  --form description="Automated Ceph build from `hostname`" \
  https://scan.coverity.com/builds?project=ceph

echo done.
