export const ICON_TYPE = {
  add: 'add',
  addFilled: 'add--filled',
  analytics: 'analytics',
  arrowDown: 'arrow--down',
  arrowLeft: 'arrow--left',
  arrowRight: 'arrow--right',
  arrowUp: 'arrow--up',
  arrowUpRight: 'arrow--up-right',
  arrowsHorizontal: 'arrows--horizontal',
  calendar: 'calendar',
  caretDown: 'caret--down',
  caretLeft: 'caret--left',
  caretRight: 'caret--right',
  chartArea: 'chart--area',
  checkbox: 'checkbox',
  checkmark: 'checkmark',
  checkmarkFilled: 'checkmark--filled',
  checkmarkOutline: 'checkmark--outline',
  chevronDown: 'chevron--down',
  chevronLeft: 'chevron--left',
  chevronRight: 'chevron--right',
  chip: 'chip',
  circleDash: 'circle-dash',
  close: 'close',
  closeFilled: 'close--filled',
  cloudMonitoring: 'cloud--monitoring',
  code: 'code',
  connect: 'connect',
  copy: 'copy',
  copyFile: 'copy--file',
  cube: 'cube',
  dataCenter: 'data--center',
  dataEnrichment: 'data-enrichment',
  dataTable: 'data-table',
  dataViewAlt: 'data--view--alt',
  datastore: 'datastore',
  document: 'document',
  dotMark: 'dot-mark',
  download: 'download',
  edit: 'edit',
  erase: 'erase',
  error: 'error--filled',
  filter: 'filter',
  flag: 'flag',
  hardDrive: 'hard--drive',
  help: 'help',
  hourglass: 'hourglass',
  ibmCloudBareMetalServer: 'ibm-cloud--bare-metal-server',
  ibmCloudDedicatedHost: 'ibm-cloud--dedicated-host',
  ibmStreamSets: 'ibm--streamsets',
  idea: 'idea',
  inProgress: 'in-progress',
  incidentReporter: 'incident-reporter',
  information: 'information',
  informationFilled: 'information--filled',
  launch: 'launch',
  loading: 'loading',
  locked: 'locked',
  login: 'login',
  logout: 'logout',
  magicWand: 'magic-wand',
  maximize: 'maximize',
  menu: 'menu',
  network1: 'network--1',
  network3: 'network--3',
  notification: 'notification',
  notificationNew: 'notification--new',
  notificationOff: 'notification--off',
  password: 'password',
  play: 'play',
  plug: 'plug',
  questionCircle: 'help',
  renew: 'renew',
  scales: 'scales',
  search: 'search',
  serverRack: 'server--rack',
  settings: 'settings',
  settingsAdjust: 'settings--adjust',
  share: 'share',
  stethoscope: 'stethoscope',
  stopFilledAlt: 'stop--filled--alt',
  subtractAlt: 'subtract--alt',
  target: 'target',
  temperature: 'temperature',
  terminal: 'terminal',
  textAlignLeft: 'text-align-left',
  tools: 'tools',
  trashCan: 'trash-can',
  undo: 'undo',
  unlink: 'unlink',
  unlocked: 'unlocked',
  upgrade: 'upgrade',
  upload: 'upload',
  user: 'user',
  userAccessLocked: 'user--access-locked',
  userMultiple: 'user--multiple',
  view: 'view',
  vmdkDisk: 'vmdk-disk',
  warningAlt: 'warning--alt',
  warningAltFilled: 'warning--alt--filled',
  warningFilled: 'warning--filled',
  webServicesCluster: 'web-services--cluster'
} as const;

export enum IconSize {
  size16 = '16',
  size20 = '20',
  size24 = '24',
  size32 = '32'
}

export const EMPTY_STATE_IMAGE = {
  default: 'assets/empty-state.png',
  search: 'assets/empty-state-search.png',
  locked: 'assets/locked.png'
} as const;
