tasks:
- parallel:
   - user-workload
   - kclient-workload
user-workload:
  sequential:
  - exec:
      client.0:
        - "sudo ceph auth caps client.0 mds 'allow all' mgr 'allow r' mon 'allow rw' osd 'allow rwx'"
  - ceph-fuse: [client.0]
  - workunit:
      subdir: fscrypt-fuse
      clients:
        client.0:
          - fs/fscrypt_cli_setup.sh
          - fs/fscrypt_kclient_fuse.sh fuse
      timeout: 4h
kclient-workload:
  sequential:
  - exec:
      client.1:
        - "sudo ceph auth caps client.1 mds 'allow all' mgr 'allow r' mon 'allow rw' osd 'allow rwx'"
  - kclient: [client.1]
  - workunit:
      subdir: fscrypt-kclient
      clients:
        client.1:
          - fs/fscrypt_cli_setup.sh
          - fs/fscrypt_kclient_fuse.sh kclient
      timeout: 4h
