#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => 1,
	'numosd' => 8, #[6],
	'numclient' => 1,#, 40, 80, 160 ],
	'n' => 10,

	'fs' => 'ebofs',

	'start' => 10,
	'end' => 40,
	'until' => 40,  
	'kill_after' => 45,
	
	'writefile' => 1,
	'writefile_size' => [4096, 
#						 8*1024,
#						 16*1024, 
#						 32*1024,
						 64*1024,
#						 128*1024,
#						 256*1024,
#						 512*1024,
#						 1024*1024
],
	'writefile_mb' => 10000,

	'osd_rep' => [0,1,2],

	'file_layout_num_rep' => [1,2,3,4,5,6],#, 2, 3, 4],

	'osd_pg_bits' => 4,
	'custom' => '--osd_max_rep 8',

	'comb' => {
		'x' => 'file_layout_num_rep',
		'vars' => [ 'cl.wrlat' ]
	}
};
