{
 "title": "RGW Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_req, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Overview - All Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average GET/PUT Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_rgw_get_initial_lat_sum[30s]) / rate(ceph_rgw_get_initial_lat_count[30s]))",
     "legendFormat": "GET AVG"
    },
    {
     "expr": "avg(rate(ceph_rgw_put_initial_lat_sum[30s]) / rate(ceph_rgw_put_initial_lat_count[30s]))",
     "legendFormat": "PUT AVG"
    }
   ]
  },
  {
   "title": "Total Requests/sec by RGW Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(rgw_host) (label_replace(rate(ceph_rgw_req[30s]), \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"))",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "GET Latencies by RGW Instance",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of GET latency imbalance across RGW hosts",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_get_initial_lat_sum[30s]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\") / \nlabel_replace(rate(ceph_rgw_get_initial_lat_count[30s]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\")",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "Bandwidth Consumed by Type",
   "type": "graph",
   "description": "Total bytes transferred in/out of all radosgw instances within the cluster",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(rate(ceph_rgw_get_b[30s]))", "legendFormat": "GETs" },
    { "expr": "sum(rate(ceph_rgw_put_b[30s]))", "legendFormat": "PUTs" }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "graph",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(rgw_host) (\n  (label_replace(rate(ceph_rgw_get_b[30s]), \"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\")) + \n  (label_replace(rate(ceph_rgw_put_b[30s]), \"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\"))\n)",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "PUT Latencies by RGW Instance",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of PUT latency imbalance across RGW hosts",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(rate(ceph_rgw_put_initial_lat_sum[30s]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\") / \nlabel_replace(rate(ceph_rgw_put_initial_lat_count[30s]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\")",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  }
 ]
}