{
 "title": "RBD Details",
 "description": "Detailed Performance of RBD Images (IOPS/Throughput/Latency)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(ceph_rbd_read_bytes{instance=~\"$instance.*\"}, pool)"
   },
   {
    "name": "image",
    "label": "Image",
    "query": "label_values(ceph_rbd_read_bytes{instance=~\"$instance.*\"}, image)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ceph_health_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rbd_write_ops{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s]) * -1",
     "legendFormat": "Write {{image}}"
    },
    {
     "expr": "irate(ceph_rbd_read_ops{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s])",
     "legendFormat": "Read {{image}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rbd_write_bytes{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s]) * -1",
     "legendFormat": "Write {{image}}"
    },
    {
     "expr": "irate(ceph_rbd_read_bytes{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s])",
     "legendFormat": "Read {{image}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "(irate(ceph_rbd_write_latency_sum{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s]) / irate(ceph_rbd_write_latency_count{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s])) * -1",
     "legendFormat": "Write {{image}}"
    },
    {
     "expr": "irate(ceph_rbd_read_latency_sum{pool=~\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s]) / irate(ceph_rbd_read_latency_count{pool=\"$pool\", image=~\"$image\", instance=~\"$instance.*\"}[30s])",
     "legendFormat": "Read {{image}}"
    }
   ]
  }
 ]
}