tasks:
- install:
- ceph:
- openssl_keys:
- rgw:
    client.0:

overrides:
  install:
    ceph:
      extra_system_packages:
        rpm:
        - java-21-openjdk-headless
        deb:
        - openjdk-21-jre-headless
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
