FROM quay.io/ceph/daemon-base:latest-reef
COPY ./tmp_build/orchestrator /usr/share/ceph/mgr/orchestrator
COPY ./tmp_build/rook /usr/share/ceph/mgr/rook
COPY ./tmp_build/ceph/ /usr/lib/python3.6/site-packages/ceph/
