/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_fs_ceph_CephFileSystem_CephStat */

#ifndef _Included_org_apache_hadoop_fs_ceph_CephFileSystem_CephStat
#define _Included_org_apache_hadoop_fs_ceph_CephFileSystem_CephStat
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
