#!/bin/sh
# vim: set noet ts=8:

set -e

case "$1" in
    remove)
	invoke-rc.d ceph-all stop || {
	    RESULT=$?
	    # Ignore if ceph-all upstart config does not
	    # exist or upstart is not in use
	    if [ $RESULT != 100 ]; then
		exit $RESULT
	    fi
	}
	invoke-rc.d ceph stop || {
	    RESULT=$?
	    if [ $RESULT != 100 ]; then
		exit $RESULT
	    fi
	}
	;;

    *)
	;;
esac

#DEBHELPER#

exit 0
