Document: ceph
Title: Debian ceph Manual
Author: <insert document author here>
Abstract: This manual describes what ceph is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ceph/ceph.sgml.gz

Format: postscript
Files: /usr/share/doc/ceph/ceph.ps.gz

Format: text
Files: /usr/share/doc/ceph/ceph.text.gz

Format: HTML
Index: /usr/share/doc/ceph/html/index.html
Files: /usr/share/doc/ceph/html/*.html

  
