#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => 1,
	'numosd' => 4,
	'numclient' => [ 1, 5, 10, 15, 40, 80, 160],#, 40, 80, 160 ],
	'n' => 6,

	'fs' => 'ebofs',

	'start' => 0,
	'end' => 40,
	'until' => 40,  
	'kill_after' => 60,
	
	#'makedirs' => 1,
	'writefile' => 1,
	#'makedirs_dirs' => 10,
	'writefile_size' => 4096,
	#'makedirs_files' => 10,
	'writefile_mb' => 1,
	'fs' => 'ebofs',
	'secure_io' => [ 0, 1],
	#'makedirs_depth' => 5,

	#'mds_local_osd' => [ 0, 1 ],
	#'meta_log_layout_num_rep' => [ 0, 1, 2, 3, 4],
		
	#'custom' => '--tcp_skip_rank0',

	'comb' => {
		'x' => 'meta_log_layout_num_rep',
		'vars' => [ 'mds.log.lat', 'cl.lat', 'osd.rlat' ]
	}
};
