[DEFAULT]
host = 127.0.0.1
port = 9080
is_secure = False
ssl_verify = False

[fixtures]
bucket prefix = s3t-{random}-

[s3 main]
display_name = test
user_id = test
access_key = test
secret_key = test
email = test@test.com

[s3 alt]
display_name = altuser
user_id = altuser
access_key = altuser
secret_key = altpass
email = alt@test.com

[s3 tenant]
display_name = test
user_id = test
access_key = test
secret_key = test
email = test@test.com
tenant = test

[iam]
display_name = test
user_id = test
access_key = test
secret_key = test
email = test@test.com

[iam root]
display_name = test
user_id = test
access_key = test
secret_key = test
email = test@test.com

[iam alt root]
display_name = altuser
user_id = altuser
access_key = altuser
secret_key = altpass
email = alt@test.com
