tasks:
- cephadm.shell:
    mon.a:
    - |
      set -ex
      for f in osd.0 osd.1 osd.2 osd.3 osd.4 osd.5 osd.6 osd.7 mgr.y mgr.x
      do
          echo "rotating key for $f"
          K=$(ceph auth get-key $f)
          ceph auth rotate $f >/dev/null
          NK=$(ceph auth get-key $f)
          test "$K" != "$NK"
          ceph orch daemon redeploy $f
          sleep 60
      done

      osd_started=$(ceph orch ps --daemon-type osd --refresh -f json | jq -cS 'sort_by(.daemon_name) | map({daemon_name, started})')
      ceph orch daemon reconfig osd.0
      sleep 120
      new_osd_started=$(ceph orch ps --daemon-type osd --refresh -f json | jq -cS 'sort_by(.daemon_name) | map({daemon_name, started})')
      test "$osd_started" = "$new_osd_started"
