tasks:
- cephadm.shell:
    mon.a:
    - |
      set -ex
      for f in osd.0 osd.1 osd.2 osd.3 osd.4 osd.5 osd.6 osd.7 mgr.y mgr.x
      do
          echo "rotating key for $f"
          K=$(ceph auth get-key $f)
          NK="$K"
          ceph auth rotate --entity=$f --key-type=aes256k
          ceph orch daemon redeploy $f
          while [ "$K" == "$NK" ]; do
              sleep 5
              NK=$(ceph auth get-key $f)
          done
          
          if [[ "$f" == mgr* ]]; then
              # Waiting for active/standby MGR ($f) redeploy to fully complete
              ceph orch ps --refresh
              sleep 60
          fi
      done
