#!/usr/bin/perl

# hi there
{
	'sleep' => 3,
	'kill_after' => 300,

	'nummds' => [2, 4, 6, 8, 10, 12],

	'cper' => 50,
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$cnode * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd' ],
	
	# parameters
	'fs' => 'ebofs',
	'until' => 100,     # --syn until $n    ... when to stop clients
	
	'makedirs' => 1,
	'makedirs_dirs' => 10,
	'makedirs_files' => 10,
	'makedirs_depth' => 3,
		
	'custom' => '--tcp_skip_rank0',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	# for final summation (script/sum.pl)
	'start' => 30,
	'end' => 90,

	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.op' ]
	}
};
