#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 2, 4, 6, 8, 12, 16, 24, 32, 40, 48, 64],

	'cper' => 50,
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$cnode * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd' ],
	
	# parameters
	#'fs' => 'ebofs',
	'fs' => 'fakestore',

	'until' => 400,     # --syn until $n    ... when to stop clients
	'kill_after' => 600,
	'start' => 200,
	'end' => 400,
	
	#	'makedirs' => 1,
	#'makedirs_dirs' => 10,
	#'makedirs_files' => 10,
	#'makedirs_depth' => 3,
		
	'custom' => '--tcp_skip_rank0 --syn only 0 --syn trace traces/trace.lib 1 --sleep 10 --randomsleep 60 --syn trace traces/trace.openssh.lib',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	# for final summation (script/sum.pl)

	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req' ]
	}
};
