#!/bin/sh

# This is the script that runs inside Jenkins.
# http://jenkins.ceph.com/job/teuthology-pull-requests/

set -x
set -e

virtualenv --version
virtualenv --system-site-packages --distribute venv
. venv/bin/activate
venv/bin/pip install tox
tox -rv
