teuthology:
  postmerge:
  - |
    -- Tracker #76780: Drop this entire branch. 
    -- FUSE upgrade testing is being moved to a separate dedicated job.
    reject()
tasks:
- ceph-fuse:
- print: "**** done client"
