overrides:
  install:
    extra_system_packages:
      rpm:
        - python3-pytest
      deb:
        - python3-pytest
  check-counter:
    dry_run: true
  ceph:
    log-ignorelist:
      - evicting unresponsive client
      - RECENT_CRASH

tasks:
- exec:
    mon.a:
      - ceph config set mgr mgr/crash/warn_recent_interval 0
- cephfs_test_runner:
    fail_on_skip: false
    modules:
      # TODO: for dev phase only, remove before merging the PR
      - tasks.cephfs.test_snapshots.TestMultiMDS
      - tasks.cephfs.test_snapshots
