import docopt

import teuthology.suite

doc = """
usage: teuthology-suite [-h]
       teuthology-suite --name <name> --suite <suite> [options]
       teuthology-suite -n <name> -s <suite> [options] [<config_yaml>...]

Run a suite of ceph integration tests. A suite is a directory containing
facets. A facet is a directory containing config snippets. Running a suite
means running teuthology for every configuration combination generated by
taking one config snippet from each facet. Any config files passed on the
command line will be used for every combination, and will override anything in
the suite.

positional arguments:
  <config_yaml>          Optional extra job yaml to include

optional arguments:
  -h, --help             Show this help message and exit
  -v, --verbose          Be more verbose
  --dry-run              Do a dry run; do not schedule anything
  -n, --name <name>      Name for this suite
  --base <base>          Base directory for the suite
                         e.g. ~/src/ceph-qa-suite/suites
  -s <suite>, --suite <suite>
                         The suite to run
  --owner <owner>        Job owner
  --email <email>        When tests finish or time out, send an email to this
                         address.
  --timeout <timeout>    How long, in seconds, to wait for jobs to finish
                         before sending email. This does not kill jobs.
                         [default: 21600]
  -p <priority>, --priority <priority>
                         Job priority (lower is sooner)
                         [default: 1000]
  -N <num>, --num <num>  Number of times to run/queue the job
                         [default: 1]
  -l <limit>, --limit <limit>
                         Queue at most this many jobs
                         [default: 0]
  -w <worker>, --worker <worker>
                         Which worker to use (type of machine)
                         [default: plana]

"""


def main():
    args = docopt.docopt(doc)
    teuthology.suite.main(args)
