tasks:
- install:
- ceph:
- exec:
    client.0:
      - sudo ceph config set client rgw_crypt_sse_algorithm aes-256-cbc
- rgw: [client.0]
- workunit:
    clients:
      client.0:
        - rgw/run-copy-reencrypt.sh
    env:
      COPY_REENCRYPT_PHASE: put
- exec:
    client.0:
      - sudo ceph config set client rgw_crypt_sse_algorithm aes-256-gcm
- ceph.restart:
    daemons: [rgw.*]
- workunit:
    clients:
      client.0:
        - rgw/run-copy-reencrypt.sh
    env:
      COPY_REENCRYPT_PHASE: copy
