overrides:
  ceph:
    cephfs:
      pool_types:
        data_pool:
          - type=replicated
        metadata_pool:
          - type=replicated
    conf:
      client:
        client_fscrypt_dummy_encryption: true
  ceph-fuse:
