// -*- mode:C++; tab-width:8; c-basic-offset:2; indent-tabs-mode:nil -*-
// vim: ts=8 sw=2 sts=2 expandtab ft=cpp

/*
 * Ceph - scalable distributed file system
 *
 * Copyright contributors to the Ceph project
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software
 * Foundation. See file COPYING.
 *
 */

#include "dbus_ganesha_sink.h"

#include <array>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <sys/wait.h>
#include <unistd.h>

namespace rgw::file_state {

// =================================================================
// default_invoker — fork + exec dbus-send, capture stdout
// =================================================================

namespace {

// Run `argv` as a subprocess. Returns exit status and stdout.
// Used by default_invoker(); broken out so it's testable in
// isolation (and so the production path is the only fork-exec
// site).
DbusGaneshaSink::DbusResult run_subprocess(
    const std::vector<std::string>& argv) {
  if (argv.empty()) return {-1, ""};

  int pipefd[2];
  if (pipe(pipefd) != 0) return {-1, std::strerror(errno)};

  pid_t pid = fork();
  if (pid < 0) {
    close(pipefd[0]);
    close(pipefd[1]);
    return {-1, std::strerror(errno)};
  }

  if (pid == 0) {
    // child
    close(pipefd[0]);
    dup2(pipefd[1], STDOUT_FILENO);
    close(pipefd[1]);
    std::vector<char*> raw;
    raw.reserve(argv.size() + 1);
    for (const auto& s : argv) raw.push_back(const_cast<char*>(s.c_str()));
    raw.push_back(nullptr);
    execvp(raw[0], raw.data());
    _exit(127);
  }

  // parent
  close(pipefd[1]);
  std::string out;
  std::array<char, 4096> buf{};
  ssize_t n;
  while ((n = read(pipefd[0], buf.data(), buf.size())) > 0) {
    out.append(buf.data(), static_cast<size_t>(n));
  }
  close(pipefd[0]);
  int status = 0;
  waitpid(pid, &status, 0);
  int exit_code = WIFEXITED(status) ? WEXITSTATUS(status) : -1;
  return {exit_code, std::move(out)};
}

}  // namespace

DbusGaneshaSink::DbusInvoker DbusGaneshaSink::default_invoker() {
  return &run_subprocess;
}

// =================================================================
// Construction
// =================================================================

DbusGaneshaSink::DbusGaneshaSink(Config cfg, DbusInvoker invoker)
    : cfg_(std::move(cfg)),
      invoker_(invoker ? std::move(invoker) : default_invoker()) {}

// =================================================================
// Helpers
// =================================================================

DbusGaneshaSink::Key DbusGaneshaSink::key_of(const DesiredExport& e) {
  return {e.fs_id, e.ap_id, e.mt_id};
}

namespace {

// Extract the bucket *name* (post `arn:aws:s3:::`) from a
// bucket ARN. Tolerates either AWS or RGW account-id forms.
// Caller should have validated the ARN at the API layer; this
// is best-effort for rendering and falls back to the raw string.
std::string bucket_name_from_arn(std::string_view arn) {
  constexpr std::string_view P = "arn:aws:s3:::";
  if (arn.size() > P.size() && arn.substr(0, P.size()) == P) {
    return std::string(arn.substr(P.size()));
  }
  return std::string(arn);
}

}  // namespace

std::string DbusGaneshaSink::render_export_block(
    std::uint16_t export_id, const DesiredExport& e) const {
  std::ostringstream o;
  o << "# Auto-generated by rgw s3files reconciler. Do not edit.\n"
    << "# fs="  << e.fs_id  << " ap=" << e.ap_id
    << " mt=" << e.mt_id << "\n"
    << "# roleArn=" << e.role_arn
    << " (assumed per-session post-mount-auth)\n"
    << "EXPORT {\n"
    << "    Export_ID = " << export_id << ";\n"
    << "    Path = \"/" << e.composed_prefix << "\";\n"
    // Pseudo path is what NFS clients actually mount. Keep it
    // human-readable: /<fs_id>/<ap_id>. Stable across reconciler
    // runs for a given (fs, ap) pair.
    << "    Pseudo = \"/" << e.fs_id << "/" << e.ap_id << "\";\n"
    << "    Access_Type = RW;\n"
    // Squash defaults to Root_Squash. ClientRootAccess at the
    // mount-auth layer would lift this per-session via the
    // session policy; since mount-auth isn't built yet, the
    // export is statically Root_Squash.
    << "    Squash = Root_Squash;\n"
    << "    SecType = sys;\n"
    << "    Filesystem_Id = " << (export_id & 0xffff) << "."
                              << (export_id & 0xffff) << ";\n"
    << "    Protocols = 4;\n"
    << "    Transports = TCP;\n";
  if (e.posix_user) {
    o << "    Anonymous_Uid = " << e.posix_user->uid << ";\n"
      << "    Anonymous_Gid = " << e.posix_user->gid << ";\n";
  }
  o << "    FSAL {\n"
    << "        Name = RGW;\n"
    << "        User_ID = \""    << cfg_.rgw_user_id    << "\";\n"
    << "        Access_Key_ID = \"" << cfg_.rgw_access_key << "\";\n"
    << "        Secret_Access_Key = \"" << cfg_.rgw_secret_key << "\";\n"
    // RGW FSAL takes the bucket name (not full ARN) as the
    // export root.
    << "        bucket = \"" << bucket_name_from_arn(e.bucket_arn) << "\";\n"
    << "    }\n"
    << "}\n";
  return o.str();
}

std::string DbusGaneshaSink::write_config_file(
    std::uint16_t export_id, const DesiredExport& e) {
  std::string path = cfg_.export_config_dir;
  if (path.empty() || path.back() != '/') path.push_back('/');
  path += std::to_string(export_id);
  path += ".conf";
  std::string body = render_export_block(export_id, e);

  // Atomic write: tempfile + rename so a partial write can never
  // be picked up by Ganesha mid-AddExport.
  std::string tmp = path + ".tmp";
  std::ofstream out(tmp);
  out << body;
  out.close();
  if (out.fail()) return {};  // caller logs and aborts the apply
  if (std::rename(tmp.c_str(), path.c_str()) != 0) return {};
  return path;
}

std::vector<std::string> DbusGaneshaSink::base_dbus_args(
    const std::string& method) const {
  std::vector<std::string> args = {
      "dbus-send",
      cfg_.system_bus ? "--system" : "--session",
      "--print-reply",
      "--type=method_call",
      "--dest=" + cfg_.dbus_dest,
      cfg_.dbus_object,
      cfg_.dbus_iface + "." + method,
  };
  return args;
}

// Note: AddExport's reply *does* carry the assigned export_id
// in a "uint16 N" line, but we don't consume it — the EXPORT
// block in the rendered config file already specifies our
// chosen Export_ID, and Ganesha's AddExport validates that the
// id is unique. If a future iteration wants to delegate ID
// assignment to Ganesha instead, parse the reply with
// `static const std::regex re(R"(uint16\s+(\d+))")`.

bool DbusGaneshaSink::dbus_add_export(const std::string& config_path) {
  auto args = base_dbus_args("AddExport");
  args.push_back("string:" + config_path);
  args.push_back("string:");          // empty options
  auto r = invoker_(args);
  return r.exit_status == 0;
}

bool DbusGaneshaSink::dbus_remove_export(std::uint16_t export_id) {
  auto args = base_dbus_args("RemoveExport");
  args.push_back("uint16:" + std::to_string(export_id));
  auto r = invoker_(args);
  return r.exit_status == 0;
}

bool DbusGaneshaSink::dbus_update_export(
    const std::string& config_path, std::uint16_t export_id) {
  auto args = base_dbus_args("UpdateExport");
  args.push_back("string:" + config_path);
  args.push_back("string:");          // empty options
  // UpdateExport in Ganesha is keyed by the EXPORT block in the
  // file; the export_id within the block must match. We pass
  // it implicitly via the rendered file.
  (void)export_id;
  auto r = invoker_(args);
  return r.exit_status == 0;
}

// =================================================================
// apply: diff and dispatch
// =================================================================

void DbusGaneshaSink::apply(std::vector<DesiredExport> desired) {
  std::map<Key, DesiredExport> next;
  for (auto& e : desired) {
    next.emplace(key_of(e), std::move(e));
  }

  // Removals first: anything in last_applied_ that's not in
  // `next`.
  for (auto it = last_applied_.begin(); it != last_applied_.end();) {
    if (next.find(it->first) == next.end()) {
      auto m = mapping_.find(it->first);
      if (m != mapping_.end()) {
        if (dbus_remove_export(m->second)) {
          // Best-effort: remove the on-disk config file.
          std::string path = cfg_.export_config_dir;
          if (path.empty() || path.back() != '/') path.push_back('/');
          path += std::to_string(m->second);
          path += ".conf";
          std::remove(path.c_str());
          mapping_.erase(m);
        }
      }
      it = last_applied_.erase(it);
    } else {
      ++it;
    }
  }

  // Adds + updates.
  for (auto& [key, e] : next) {
    auto prev_it = last_applied_.find(key);
    if (prev_it == last_applied_.end()) {
      // New: assign id, render, AddExport.
      std::uint16_t id = cfg_.next_export_id++;
      std::string path = write_config_file(id, e);
      if (path.empty()) continue;  // I/O failure; retry next cycle
      if (dbus_add_export(path)) {
        mapping_[key] = id;
        last_applied_[key] = e;
      }
    } else if (!(prev_it->second == e)) {
      // Changed: re-render, UpdateExport.
      auto m = mapping_.find(key);
      if (m == mapping_.end()) continue;  // shouldn't happen
      std::string path = write_config_file(m->second, e);
      if (path.empty()) continue;
      if (dbus_update_export(path, m->second)) {
        prev_it->second = e;
      }
    }
    // else: unchanged, no work
  }
}

std::optional<std::uint16_t> DbusGaneshaSink::export_id_for(
    std::string_view fs_id, std::string_view ap_id,
    std::string_view mt_id) const {
  auto it = mapping_.find(Key{std::string(fs_id), std::string(ap_id),
                              std::string(mt_id)});
  if (it == mapping_.end()) return std::nullopt;
  return it->second;
}

}  // namespace rgw::file_state
