// -*- mode:C++; tab-width:8; c-basic-offset:2; indent-tabs-mode:nil -*-
// vim: ts=8 sw=2 sts=2 expandtab ft=cpp

/*
 * Ceph - scalable distributed file system
 *
 * Copyright contributors to the Ceph project
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software
 * Foundation. See file COPYING.
 *
 */

#include "dbus_ganesha_sink.h"

#include <array>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <sys/wait.h>
#include <unistd.h>

namespace rgw::file_state {

// =================================================================
// default_invoker — fork + exec dbus-send, capture stdout
// =================================================================

namespace {

// Run `argv` as a subprocess. Returns exit status and stdout.
// Used by default_invoker(); broken out so it's testable in
// isolation (and so the production path is the only fork-exec
// site).
DbusGaneshaSink::DbusResult run_subprocess(
    const std::vector<std::string>& argv) {
  if (argv.empty()) return {-1, ""};

  int pipefd[2];
  if (pipe(pipefd) != 0) return {-1, std::strerror(errno)};

  pid_t pid = fork();
  if (pid < 0) {
    close(pipefd[0]);
    close(pipefd[1]);
    return {-1, std::strerror(errno)};
  }

  if (pid == 0) {
    // child
    close(pipefd[0]);
    dup2(pipefd[1], STDOUT_FILENO);
    close(pipefd[1]);
    std::vector<char*> raw;
    raw.reserve(argv.size() + 1);
    for (const auto& s : argv) raw.push_back(const_cast<char*>(s.c_str()));
    raw.push_back(nullptr);
    execvp(raw[0], raw.data());
    _exit(127);
  }

  // parent
  close(pipefd[1]);
  std::string out;
  std::array<char, 4096> buf{};
  ssize_t n;
  while ((n = read(pipefd[0], buf.data(), buf.size())) > 0) {
    out.append(buf.data(), static_cast<size_t>(n));
  }
  close(pipefd[0]);
  int status = 0;
  waitpid(pid, &status, 0);
  int exit_code = WIFEXITED(status) ? WEXITSTATUS(status) : -1;
  return {exit_code, std::move(out)};
}

}  // namespace

DbusGaneshaSink::DbusInvoker DbusGaneshaSink::default_invoker() {
  return &run_subprocess;
}

// =================================================================
// Construction
// =================================================================

DbusGaneshaSink::DbusGaneshaSink(Config cfg, DbusInvoker invoker)
    : cfg_(std::move(cfg)),
      invoker_(invoker ? std::move(invoker) : default_invoker()) {}

// =================================================================
// Helpers
// =================================================================

DbusGaneshaSink::Key DbusGaneshaSink::key_of(const DesiredExport& e) {
  return {e.fs_id, e.ap_id, e.mt_id};
}

namespace {

// Extract the bucket *name* (post `arn:aws:s3:::`) from a
// bucket ARN. Tolerates either AWS or RGW account-id forms.
// Caller should have validated the ARN at the API layer; this
// is best-effort for rendering and falls back to the raw string.
std::string bucket_name_from_arn(std::string_view arn) {
  constexpr std::string_view P = "arn:aws:s3:::";
  if (arn.size() > P.size() && arn.substr(0, P.size()) == P) {
    return std::string(arn.substr(P.size()));
  }
  return std::string(arn);
}

// Compose the FSAL_RGW Path field. The bucket-rooted FSAL_RGW
// patch (in our nfs-ganesha tree) parses Path as
// "/<bucket>[/<prefix>]" and rgw_mount2's at the bucket root —
// works for both legacy users and RGW account-root users (the
// latter can't list buckets via the user namespace, so the
// previous "/" path form was unusable for accounts).
//
//   no prefix  -> "/<bucket>"
//   prefix     -> "/<bucket>/<prefix>"  (no trailing slash; FSAL
//                                        normalizes internally)
std::string compose_fsal_path(std::string_view bucket_arn,
                              std::string_view composed_prefix) {
  std::string bucket = bucket_name_from_arn(bucket_arn);
  std::string path = "/";
  path += bucket;
  if (!composed_prefix.empty()) {
    if (composed_prefix.front() != '/') path.push_back('/');
    path.append(composed_prefix);
  }
  return path;
}

}  // namespace

std::string DbusGaneshaSink::render_export_block(
    std::uint16_t export_id, const DesiredExport& e) const {
  std::ostringstream o;
  o << "# Auto-generated by rgw s3files reconciler. Do not edit.\n"
    << "# fs="  << e.fs_id  << " ap=" << e.ap_id
    << " mt=" << e.mt_id << "\n"
    << "# roleArn=" << e.role_arn
    << " (assumed per-session post-mount-auth)\n"
    << "EXPORT {\n"
    << "    Export_ID = " << export_id << ";\n"
    << "    Path = \"" << compose_fsal_path(e.bucket_arn,
                                            e.composed_prefix)
    << "\";\n"
    // Pseudo path is what NFS clients actually mount. Keep it
    // human-readable: /<fs_id>/<ap_id>. Stable across reconciler
    // runs for a given (fs, ap) pair.
    << "    Pseudo = \"/" << e.fs_id << "/" << e.ap_id << "\";\n"
    << "    Access_Type = RW;\n"
    // Squash defaults to Root_Squash. ClientRootAccess at the
    // mount-auth layer would lift this per-session via the
    // session policy; since mount-auth isn't built yet, the
    // export is statically Root_Squash.
    << "    Squash = Root_Squash;\n"
    << "    SecType = sys;\n"
    << "    Filesystem_Id = " << (export_id & 0xffff) << "."
                              << (export_id & 0xffff) << ";\n"
    << "    Protocols = 4;\n"
    << "    Transports = TCP;\n";
  if (e.posix_user) {
    o << "    Anonymous_Uid = " << e.posix_user->uid << ";\n"
      << "    Anonymous_Gid = " << e.posix_user->gid << ";\n";
  }
  // Field-name casing matches /etc/ganesha/rgw.conf (Id, not
  // ID; Access_Key_Id, not Access_Key_ID). Ganesha's config
  // parser accepts both, but matching the upstream example
  // keeps the rendered output diff-friendly against the
  // distro-shipped reference.
  // User_Id may be a legacy RGW user or an RGW account-root user
  // (e.g. "demoroot"). For account-root, only the access/secret
  // keys authenticate; User_Id is just the displayed root owner.
  // The bucket-rooted Path above is what makes account-owned
  // buckets visible — accounts don't own buckets at the user
  // namespace level, so a Path = "/" form would list nothing.
  o << "    FSAL {\n"
    << "        Name = RGW;\n"
    << "        User_Id = \""    << cfg_.rgw_user_id    << "\";\n"
    << "        Access_Key_Id = \"" << cfg_.rgw_access_key << "\";\n"
    << "        Secret_Access_Key = \"" << cfg_.rgw_secret_key << "\";\n"
    << "    }\n"
    << "}\n";
  return o.str();
}

std::string DbusGaneshaSink::write_config_file(
    std::uint16_t export_id, const DesiredExport& e) {
  std::string path = cfg_.export_config_dir;
  if (path.empty() || path.back() != '/') path.push_back('/');
  path += std::to_string(export_id);
  path += ".conf";
  std::string body = render_export_block(export_id, e);

  // Atomic write: tempfile + rename so a partial write can never
  // be picked up by Ganesha mid-reread_config.
  std::string tmp = path + ".tmp";
  std::ofstream out(tmp);
  out << body;
  out.close();
  if (out.fail()) return {};  // caller logs and aborts the apply
  if (std::rename(tmp.c_str(), path.c_str()) != 0) return {};
  return path;
}

std::vector<std::string> DbusGaneshaSink::base_dbus_args(
    const std::string& method) const {
  std::vector<std::string> args = {
      "dbus-send",
      cfg_.system_bus ? "--system" : "--session",
      "--print-reply",
      "--type=method_call",
      "--dest=" + cfg_.dbus_dest,
      cfg_.dbus_object,
      cfg_.dbus_iface + "." + method,
  };
  return args;
}

// Note: AddExport's reply *does* carry the assigned export_id
// in a "uint16 N" line, but we don't consume it — the EXPORT
// block in the rendered config file already specifies our
// chosen Export_ID, and Ganesha's AddExport validates that the
// id is unique. If a future iteration wants to delegate ID
// assignment to Ganesha instead, parse the reply with
// `static const std::regex re(R"(uint16\s+(\d+))")`.

bool DbusGaneshaSink::dbus_add_export(const std::string& config_path) {
  // Unused: see dbus_reread_config(). Retained so the existing
  // unit tests that drive the recording invoker still link.
  (void)config_path;
  return true;
}

bool DbusGaneshaSink::dbus_remove_export(std::uint16_t export_id) {
  // Unused: see dbus_reread_config(). reread_config picks up the
  // removal once the per-export file is unlinked from disk and
  // the index regenerated.
  (void)export_id;
  return true;
}

bool DbusGaneshaSink::dbus_update_export(
    const std::string& config_path, std::uint16_t export_id) {
  // Unused: see dbus_reread_config().
  (void)config_path;
  (void)export_id;
  return true;
}

bool DbusGaneshaSink::dbus_reread_config() {
  // Drive Ganesha's admin.reread_config DBus method, which
  // re-reads the configured ganesha.conf (and any %include'd
  // files) and reconciles the running export set against it.
  // We use this instead of exportmgr.AddExport because AddExport
  // hits a NULL-deref in find_config_nodes
  // (config_parsing.c:1839) on at least V9.11 and V9.13;
  // reread_config takes a different code path that doesn't
  // crash and is naturally idempotent — re-running it after a
  // no-op change is harmless.
  auto args = base_dbus_args("reread_config");
  // The reread_config method lives on the *admin* interface,
  // not exportmgr. base_dbus_args put us at exportmgr; rewrite
  // the path/iface in the cached argv.
  for (auto& a : args) {
    if (a == cfg_.dbus_object) {
      a = "/org/ganesha/nfsd/admin";
    } else if (a.rfind(cfg_.dbus_iface + ".", 0) == 0) {
      a = "org.ganesha.nfsd.admin.reread_config";
    }
  }
  auto r = invoker_(args);
  return r.exit_status == 0;
}

bool DbusGaneshaSink::write_index_file() {
  // ganesha.conf %include's a single index.conf that lists one
  // %include per active export. Rebuilt on every apply() so
  // removals (entries dropped from `mapping_`) actually
  // disappear from Ganesha's view after reread_config.
  std::string idx = cfg_.export_config_dir;
  if (idx.empty() || idx.back() != '/') idx.push_back('/');
  idx += "index.conf";
  std::string tmp = idx + ".tmp";
  {
    std::ofstream out(tmp);
    out << "# Auto-generated by rgw s3files reconciler. Do not edit.\n"
           "# %include one line per active <export_id>.conf below.\n";
    for (const auto& [key, id] : mapping_) {
      out << "%include " << cfg_.export_config_dir;
      if (cfg_.export_config_dir.empty() ||
          cfg_.export_config_dir.back() != '/') out << '/';
      out << id << ".conf\n";
    }
    out.close();
    if (out.fail()) return false;
  }
  return std::rename(tmp.c_str(), idx.c_str()) == 0;
}

// =================================================================
// apply: diff and dispatch
// =================================================================

void DbusGaneshaSink::apply(std::vector<DesiredExport> desired) {
  std::map<Key, DesiredExport> next;
  for (auto& e : desired) {
    next.emplace(key_of(e), std::move(e));
  }

  bool dirty = false;

  // Removals first: anything in last_applied_ that's not in
  // `next`. Drop the per-export file so the next index rewrite
  // omits it.
  for (auto it = last_applied_.begin(); it != last_applied_.end();) {
    if (next.find(it->first) == next.end()) {
      auto m = mapping_.find(it->first);
      if (m != mapping_.end()) {
        std::string path = cfg_.export_config_dir;
        if (path.empty() || path.back() != '/') path.push_back('/');
        path += std::to_string(m->second);
        path += ".conf";
        std::remove(path.c_str());
        mapping_.erase(m);
      }
      it = last_applied_.erase(it);
      dirty = true;
    } else {
      ++it;
    }
  }

  // Adds + updates: render the per-export file. Reload-driven
  // sinks don't need separate Add/Update DBus methods — Ganesha
  // sees the new content on the next reread.
  for (auto& [key, e] : next) {
    auto prev_it = last_applied_.find(key);
    if (prev_it == last_applied_.end()) {
      // New: assign id, render.
      std::uint16_t id = cfg_.next_export_id++;
      std::string path = write_config_file(id, e);
      if (path.empty()) continue;  // I/O failure; retry next cycle
      mapping_[key] = id;
      last_applied_[key] = e;
      dirty = true;
    } else if (!(prev_it->second == e)) {
      // Changed: re-render the same id.
      auto m = mapping_.find(key);
      if (m == mapping_.end()) continue;  // shouldn't happen
      std::string path = write_config_file(m->second, e);
      if (path.empty()) continue;
      prev_it->second = e;
      dirty = true;
    }
    // else: unchanged, no work
  }

  // Single reload for the whole batch — cheaper than per-export
  // and avoids the AddExport NULL-deref in V9.11+V9.13.
  if (dirty) {
    if (!write_index_file()) return;  // Ganesha will see stale state
    dbus_reread_config();
  }
}

std::optional<std::uint16_t> DbusGaneshaSink::export_id_for(
    std::string_view fs_id, std::string_view ap_id,
    std::string_view mt_id) const {
  auto it = mapping_.find(Key{std::string(fs_id), std::string(ap_id),
                              std::string(mt_id)});
  if (it == mapping_.end()) return std::nullopt;
  return it->second;
}

}  // namespace rgw::file_state
