#! /bin/bash -e

mount () { :; }
umount () { :; }

list="\
abiword.control
abiword.list
abiword-plugin-latex.control
abiword-plugin-latex.list
abiword-plugin-opendocument.control
abiword-plugin-opendocument.list
abiword-plugin-openxml.control
abiword-plugin-openxml.list
abiword-plugin-pdf.control
abiword-plugin-pdf.list
abiword-plugin-wikipedia.control
abiword-plugin-wikipedia.list
abiword.postinst
aceofpenguins.control
aceofpenguins-launcher.control
aceofpenguins-launcher.list
aceofpenguins.list
aceofpenguins.postinst
alsa-conf-base.control
alsa-conf-base.list
alsa-scenarii-shr.conffiles
alsa-scenarii-shr.control
alsa-scenarii-shr.list
alsa-utils-alsactl.control
alsa-utils-alsactl.list
alsa-utils-alsamixer.control
alsa-utils-alsamixer.list
alsa-utils-amixer.control
alsa-utils-amixer.list
alsa-utils-aplay.control
alsa-utils-aplay.list
angstrom-libc-fixup-hack.control
angstrom-libc-fixup-hack.list
angstrom-libc-fixup-hack.postinst
apmd.control
apmd.list
apmd.postinst
apmd.postrm
apmd.prerm
aspell.control
aspell.list
atd-over-fso.control
atd-over-fso.list
atd-over-fso.postinst
atd-over-fso.postrm
atd-over-fso.prerm
base-files.conffiles
base-files.control
base-files.list
base-passwd.control
base-passwd.list
base-passwd.postinst
bash.control
bash.list
bash.postinst
bluez4.control
bluez4.list
bluez4.postinst
bluez4.postrm
bluez4.prerm
boost-signals.control
boost-signals.list
boost-signals.postinst
busybox.control
busybox.list
busybox-mountall.control
busybox-mountall.list
busybox-mountall.postinst
busybox-mountall.prerm
busybox.postinst
busybox.prerm
busybox-syslog.conffiles
busybox-syslog.control
busybox-syslog.list
busybox-syslog.postinst
busybox-syslog.postrm
busybox-syslog.prerm
ca-certificates.conffiles
ca-certificates.control
ca-certificates.list
ca-certificates.postinst
calc.control
calc.list
connman.control
connman.list
connman-plugin-udhcp.control
connman-plugin-udhcp.list
connman-plugin-wifi.control
connman-plugin-wifi.list
connman.postinst
connman.postrm
connman.prerm
connman-scripts.control
connman-scripts.list
cpio.control
cpio.list
cpio.postinst
cpio.prerm
cpp.control
cpp.list
cpp-symlinks.control
cpp-symlinks.list
cron.control
cron.list
cron.postinst
cron.postrm
cron.prerm
curl.control
curl.list
dbus.conffiles
dbus.control
dbus-daemon-proxy.control
dbus-daemon-proxy.list
dbus-hlid.control
dbus-hlid.list
dbus.list
dbus.postinst
dbus.postrm
dbus.prerm
dbus-x11.control
dbus-x11.list
devmem2.control
devmem2.list
distro-feed-configs.conffiles
distro-feed-configs.control
distro-feed-configs.list
dosfstools.control
dosfstools.list
e2fsprogs-badblocks.control
e2fsprogs-badblocks.list
e2fsprogs.control
e2fsprogs-e2fsck.control
e2fsprogs-e2fsck.list
e2fsprogs-e2fsck.postinst
e2fsprogs-e2fsck.prerm
e2fsprogs.list
e2fsprogs-mke2fs.control
e2fsprogs-mke2fs.list
e2fsprogs-mke2fs.postinst
e2fsprogs-mke2fs.prerm
e2fsprogs.postinst
e2fsprogs.prerm
ecore-con.control
ecore-con.list
ecore-con.postinst
ecore.control
ecore-evas.control
ecore-evas.list
ecore-evas.postinst
ecore-fb.control
ecore-fb.list
ecore-fb.postinst
ecore-file.control
ecore-file.list
ecore-file.postinst
ecore-imf.control
ecore-imf-evas.control
ecore-imf-evas.list
ecore-imf-evas.postinst
ecore-imf.list
ecore-imf.postinst
ecore-input.control
ecore-input.list
ecore-input.postinst
ecore-ipc.control
ecore-ipc.list
ecore-ipc.postinst
ecore.list
ecore.postinst
ecore-x.control
ecore-x.list
ecore-x.postinst
edbus.control
edbus.list
edbus.postinst
edje.control
edje.list
edje.postinst
edje-utils.control
edje-utils.list
efreet.control
efreet.list
efreet.postinst
eggdbus.control
eggdbus.list
eggdbus.postinst
eglibc-binary-localedata-en-us.control
eglibc-binary-localedata-en-us.list
eglibc-charmap-utf-8.control
eglibc-charmap-utf-8.list
eglibc-gconv.control
eglibc-gconv-cp1252.control
eglibc-gconv-cp1252.list
eglibc-gconv-ibm850.control
eglibc-gconv-ibm850.list
eglibc-gconv-iso8859-15.control
eglibc-gconv-iso8859-15.list
eglibc-gconv-iso8859-1.control
eglibc-gconv-iso8859-1.list
eglibc-gconv.list
eglibc-localedata-i18n.control
eglibc-localedata-i18n.list
eglibc-localedata-iso14651-t1-common.control
eglibc-localedata-iso14651-t1-common.list
eglibc-localedata-iso14651-t1.control
eglibc-localedata-iso14651-t1.list
eglibc-localedata-translit-circle.control
eglibc-localedata-translit-circle.list
eglibc-localedata-translit-cjk-compat.control
eglibc-localedata-translit-cjk-compat.list
eglibc-localedata-translit-compat.control
eglibc-localedata-translit-compat.list
eglibc-localedata-translit-font.control
eglibc-localedata-translit-font.list
eglibc-localedata-translit-fraction.control
eglibc-localedata-translit-fraction.list
eglibc-localedata-translit-narrow.control
eglibc-localedata-translit-narrow.list
eglibc-localedata-translit-neutral.control
eglibc-localedata-translit-neutral.list
eglibc-localedata-translit-small.control
eglibc-localedata-translit-small.list
eglibc-localedata-translit-wide.control
eglibc-localedata-translit-wide.list
eglibc-utils.control
eglibc-utils.list
eina.control
eina.list
eina.postinst
eject.control
eject.list
elementary-theme-gry.control
elementary-theme-gry.list
emacs-x11.control
emacs-x11.list
embryo.control
embryo.list
embryo.postinst
embryo-tests.control
embryo-tests.list
enchant.control
enchant.list
enchant.postinst
epdfview.control
epdfview.list
espeak.control
espeak.list
espeak.postinst
evas.control
evas-engine-buffer.control
evas-engine-buffer.list
evas-engine-fb.control
evas-engine-fb.list
evas-engine-software-16.control
evas-engine-software-16.list
evas-engine-software-16-x11.control
evas-engine-software-16-x11.list
evas-engine-software-generic.control
evas-engine-software-generic.list
evas-engine-software-x11.control
evas-engine-software-x11.list
evas-engine-xrender-x11.control
evas-engine-xrender-x11.list
evas.list
evas-loader-eet.control
evas-loader-eet.list
evas-loader-jpeg.control
evas-loader-jpeg.list
evas-loader-png.control
evas-loader-png.list
evas.postinst
evas-saver-eet.control
evas-saver-eet.list
evas-saver-jpeg.control
evas-saver-jpeg.list
evas-saver-png.control
evas-saver-png.list
evtest.control
evtest.list
e-wm-config-default.control
e-wm-config-default.list
e-wm-config-illume2-shr.control
e-wm-config-illume2-shr.list
e-wm-config-illume-shr.control
e-wm-config-illume-shr.list
e-wm.control
e-wm-icons.control
e-wm-icons.list
e-wm-images.control
e-wm-images.list
e-wm-input-methods.control
e-wm-input-methods.list
e-wm.list
e-wm-menu-shr.control
e-wm-menu-shr.list
e-wm-other.control
e-wm-other.list
e-wm.postinst
e-wm.postrm
e-wm-sysactions-shr.control
e-wm-sysactions-shr.list
e-wm-theme-default.control
e-wm-theme-default.list
e-wm-theme-illume-gry.control
e-wm-theme-illume-gry.list
e-wm-theme-illume-shr.control
e-wm-theme-illume-shr.list
e-wm-utils.control
e-wm-utils.list
fbreader.control
fbreader.list
fbreader.postinst
fbset.control
fbset.list
fbset-modes.conffiles
fbset-modes.control
fbset-modes.list
fbset.postinst
fbset.postrm
ffalarms.control
ffalarms.list
file.control
file.list
file.postinst
findutils.control
findutils.list
findutils.postinst
findutils.prerm
flac.control
flac.list
flite.control
flite.list
fontconfig-utils.control
fontconfig-utils.list
font-update-common.control
font-update-common.list
frameworkd-config-shr.conffiles
frameworkd-config-shr.control
frameworkd-config-shr.list
frameworkd.control
frameworkd.list
frameworkd.postinst
frameworkd.postrm
frameworkd.prerm
fso-abyss-config.conffiles
fso-abyss-config.control
fso-abyss-config.list
fso-abyss.control
fso-abyss.list
fso-apm.control
fso-apm.list
fsodatad.control
fsodatad.list
fsodatad.postinst
fsodeviced.control
fsodeviced.list
fsodeviced.postinst
fsodeviced.postrm
fsodeviced.prerm
fso-gpsd.control
fso-gpsd.list
fso-gpsd.postinst
fso-gpsd.postrm
fso-gpsd.prerm
fsogsmd.control
fsogsmd.list
fsogsmd.postinst
fsonetworkd.control
fsonetworkd.list
fsonetworkd.postinst
fsoraw.control
fsoraw.list
fsotdld.control
fsotdld.list
fsotdld.postinst
fsousaged.control
fsousaged.list
fsousaged.postinst
gcc.control
gcc.list
gconf.control
gconf.list
gconf.postinst
g++.control
gdb.control
gdb.list
gdk-pixbuf-loader-gif.control
gdk-pixbuf-loader-gif.list
gdk-pixbuf-loader-gif.postinst
gdk-pixbuf-loader-jpeg.control
gdk-pixbuf-loader-jpeg.list
gdk-pixbuf-loader-jpeg.postinst
gdk-pixbuf-loader-png.control
gdk-pixbuf-loader-png.list
gdk-pixbuf-loader-png.postinst
gdk-pixbuf-loader-xpm.control
gdk-pixbuf-loader-xpm.list
gdk-pixbuf-loader-xpm.postinst
git.control
git.list
g++.list
gnome-pty-helper.control
gnome-pty-helper.list
gnome-vfs.control
gnome-vfs.list
gnome-vfs-plugin-file.control
gnome-vfs-plugin-file.list
gnome-vfs.postinst
gnome-vfs.prerm
gnupg.control
gnupg.list
gpe-icons.control
gpe-icons.list
gpe-icons.postinst
gpe-icons.postrm
gpe-scap.control
gpe-scap.list
gpe-sketchbook.control
gpe-sketchbook.list
gpgv.control
gpgv.list
gridpad.control
gridpad.list
gst-plugin-alsa.control
gst-plugin-alsa.list
gst-plugin-audioconvert.control
gst-plugin-audioconvert.list
gst-plugin-autodetect.control
gst-plugin-autodetect.list
gst-plugin-gconfelements.control
gst-plugin-gconfelements.list
gst-plugin-gconfelements.postinst
gst-plugin-gconfelements.prerm
gst-plugin-mad.control
gst-plugin-mad.list
gstreamer.control
gstreamer.list
gstreamer.postinst
gtk+.control
gtk+.list
gtk+.postinst
hal.control
hal-info.control
hal-info.list
hal.list
hal.postinst
hal.postrm
hdparm.control
hdparm.list
hdparm.postinst
hdparm.prerm
hicolor-icon-theme.control
hicolor-icon-theme.list
hicolor-icon-theme.postinst
hicolor-icon-theme.postrm
htop.control
htop.list
i2c-tools.control
i2c-tools.list
id3lib.control
id3lib.list
id3lib.postinst
iliwi.control
iliwi.list
illume-keyboard-default-alpha.control
illume-keyboard-default-alpha.list
illume-keyboard-default-terminal.control
illume-keyboard-default-terminal.list
illume-keyboard-numeric-alt.control
illume-keyboard-numeric-alt.list
imagemagick.control
imagemagick.list
imagemagick.postinst
initscripts-shr.control
initscripts-shr.list
intone.control
intone.list
iptables.control
iptables.list
iptables.postinst
kernel-2.6.29-rc3.control
kernel-2.6.29-rc3.list
kernel.control
kernel-image-2.6.29-rc3.control
kernel-image-2.6.29-rc3.list
kernel-image-2.6.29-rc3.postinst
kernel.list
kernel-module-ar6000.control
kernel-module-ar6000.list
kernel-module-ar6000.postinst
kernel-module-ar6000.postrm
kernel-module-arc4.control
kernel-module-arc4.list
kernel-module-arc4.postinst
kernel-module-arc4.postrm
kernel-module-asix.control
kernel-module-asix.list
kernel-module-asix.postinst
kernel-module-asix.postrm
kernel-module-bluetooth.control
kernel-module-bluetooth.list
kernel-module-bluetooth.postinst
kernel-module-bluetooth.postrm
kernel-module-bnep.control
kernel-module-bnep.list
kernel-module-bnep.postinst
kernel-module-bnep.postrm
kernel-module-btusb.control
kernel-module-btusb.list
kernel-module-btusb.postinst
kernel-module-btusb.postrm
kernel-module-crc-ccitt.control
kernel-module-crc-ccitt.list
kernel-module-crc-ccitt.postinst
kernel-module-crc-ccitt.postrm
kernel-module-ecb.control
kernel-module-ecb.list
kernel-module-ecb.postinst
kernel-module-ecb.postrm
kernel-module-exportfs.control
kernel-module-exportfs.list
kernel-module-exportfs.postinst
kernel-module-exportfs.postrm
kernel-module-gadgetfs.control
kernel-module-gadgetfs.list
kernel-module-gadgetfs.postinst
kernel-module-gadgetfs.postrm
kernel-module-g-ether.control
kernel-module-g-ether.list
kernel-module-g-ether.postinst
kernel-module-g-ether.postrm
kernel-module-g-file-storage.control
kernel-module-g-file-storage.list
kernel-module-g-file-storage.postinst
kernel-module-g-file-storage.postrm
kernel-module-g-serial.control
kernel-module-g-serial.list
kernel-module-g-serial.postinst
kernel-module-g-serial.postrm
kernel-module-hidp.control
kernel-module-hidp.list
kernel-module-hidp.postinst
kernel-module-hidp.postrm
kernel-module-iptable-filter.control
kernel-module-iptable-filter.list
kernel-module-iptable-filter.postinst
kernel-module-iptable-filter.postrm
kernel-module-iptable-nat.control
kernel-module-iptable-nat.list
kernel-module-iptable-nat.postinst
kernel-module-iptable-nat.postrm
kernel-module-ip-tables.control
kernel-module-ip-tables.list
kernel-module-ip-tables.postinst
kernel-module-ip-tables.postrm
kernel-module-ipt-masquerade.control
kernel-module-ipt-masquerade.list
kernel-module-ipt-masquerade.postinst
kernel-module-ipt-masquerade.postrm
kernel-module-l2cap.control
kernel-module-l2cap.list
kernel-module-l2cap.postinst
kernel-module-l2cap.postrm
kernel-module-lockd.control
kernel-module-lockd.list
kernel-module-lockd.postinst
kernel-module-lockd.postrm
kernel-module-michael-mic.control
kernel-module-michael-mic.list
kernel-module-michael-mic.postinst
kernel-module-michael-mic.postrm
kernel-module-nf-conntrack.control
kernel-module-nf-conntrack-ipv4.control
kernel-module-nf-conntrack-ipv4.list
kernel-module-nf-conntrack-ipv4.postinst
kernel-module-nf-conntrack-ipv4.postrm
kernel-module-nf-conntrack.list
kernel-module-nf-conntrack.postinst
kernel-module-nf-conntrack.postrm
kernel-module-nf-defrag-ipv4.control
kernel-module-nf-defrag-ipv4.list
kernel-module-nf-defrag-ipv4.postinst
kernel-module-nf-defrag-ipv4.postrm
kernel-module-nf-nat.control
kernel-module-nf-nat.list
kernel-module-nf-nat.postinst
kernel-module-nf-nat.postrm
kernel-module-nfs-acl.control
kernel-module-nfs-acl.list
kernel-module-nfs-acl.postinst
kernel-module-nfs-acl.postrm
kernel-module-nfsd.control
kernel-module-nfsd.list
kernel-module-nfsd.postinst
kernel-module-nfsd.postrm
kernel-module-nls-utf8.control
kernel-module-nls-utf8.list
kernel-module-nls-utf8.postinst
kernel-module-nls-utf8.postrm
kernel-module-ohci-hcd.control
kernel-module-ohci-hcd.list
kernel-module-ohci-hcd.postinst
kernel-module-ohci-hcd.postrm
kernel-module-pegasus.control
kernel-module-pegasus.list
kernel-module-pegasus.postinst
kernel-module-pegasus.postrm
kernel-module-ppp-async.control
kernel-module-ppp-async.list
kernel-module-ppp-async.postinst
kernel-module-ppp-async.postrm
kernel-module-ppp-deflate.control
kernel-module-ppp-deflate.list
kernel-module-ppp-deflate.postinst
kernel-module-ppp-deflate.postrm
kernel-module-ppp-generic.control
kernel-module-ppp-generic.list
kernel-module-ppp-generic.postinst
kernel-module-ppp-generic.postrm
kernel-module-ppp-mppe.control
kernel-module-ppp-mppe.list
kernel-module-ppp-mppe.postinst
kernel-module-ppp-mppe.postrm
kernel-module-rfcomm.control
kernel-module-rfcomm.list
kernel-module-rfcomm.postinst
kernel-module-rfcomm.postrm
kernel-module-s3cmci.control
kernel-module-s3cmci.list
kernel-module-s3cmci.postinst
kernel-module-s3cmci.postrm
kernel-module-sco.control
kernel-module-sco.list
kernel-module-sco.postinst
kernel-module-sco.postrm
kernel-module-scsi-mod.control
kernel-module-scsi-mod.list
kernel-module-scsi-mod.postinst
kernel-module-scsi-mod.postrm
kernel-module-sd-mod.control
kernel-module-sd-mod.list
kernel-module-sd-mod.postinst
kernel-module-sd-mod.postrm
kernel-module-slhc.control
kernel-module-slhc.list
kernel-module-slhc.postinst
kernel-module-slhc.postrm
kernel-module-snd.control
kernel-module-snd.list
kernel-module-snd-page-alloc.control
kernel-module-snd-page-alloc.list
kernel-module-snd-page-alloc.postinst
kernel-module-snd-page-alloc.postrm
kernel-module-snd-pcm.control
kernel-module-snd-pcm.list
kernel-module-snd-pcm.postinst
kernel-module-snd-pcm.postrm
kernel-module-snd.postinst
kernel-module-snd.postrm
kernel-module-snd-soc-core.control
kernel-module-snd-soc-core.list
kernel-module-snd-soc-core.postinst
kernel-module-snd-soc-core.postrm
kernel-module-snd-soc-neo1973-gta02-wm8753.control
kernel-module-snd-soc-neo1973-gta02-wm8753.list
kernel-module-snd-soc-neo1973-gta02-wm8753.postinst
kernel-module-snd-soc-neo1973-gta02-wm8753.postrm
kernel-module-snd-soc-s3c24xx.control
kernel-module-snd-soc-s3c24xx-i2s.control
kernel-module-snd-soc-s3c24xx-i2s.list
kernel-module-snd-soc-s3c24xx-i2s.postinst
kernel-module-snd-soc-s3c24xx-i2s.postrm
kernel-module-snd-soc-s3c24xx.list
kernel-module-snd-soc-s3c24xx.postinst
kernel-module-snd-soc-s3c24xx.postrm
kernel-module-snd-soc-wm8753.control
kernel-module-snd-soc-wm8753.list
kernel-module-snd-soc-wm8753.postinst
kernel-module-snd-soc-wm8753.postrm
kernel-module-snd-timer.control
kernel-module-snd-timer.list
kernel-module-snd-timer.postinst
kernel-module-snd-timer.postrm
kernel-module-sunrpc.control
kernel-module-sunrpc.list
kernel-module-sunrpc.postinst
kernel-module-sunrpc.postrm
kernel-module-tun.control
kernel-module-tun.list
kernel-module-tun.postinst
kernel-module-tun.postrm
kernel-module-uinput.control
kernel-module-uinput.list
kernel-module-uinput.postinst
kernel-module-uinput.postrm
kernel-module-usbserial.control
kernel-module-usbserial.list
kernel-module-usbserial.postinst
kernel-module-usbserial.postrm
kernel-module-usb-storage.control
kernel-module-usb-storage.list
kernel-module-usb-storage.postinst
kernel-module-usb-storage.postrm
kernel-module-x-tables.control
kernel-module-x-tables.list
kernel-module-x-tables.postinst
kernel-module-x-tables.postrm
kernel.postinst
kernel.postrm
lame.control
lame.list
liba52-0.control
liba52-0.list
liba52-0.postinst
libacl1.control
libacl1.list
libacl1.postinst
libapm1.control
libapm1.list
libapm1.postinst
libasound2.control
libasound2.list
libasound2.postinst
libaspell15.control
libaspell15.list
libaspell15.postinst
libatk-1.0-0.control
libatk-1.0-0.list
libatk-1.0-0.postinst
libattr1.control
libattr1.list
libattr1.postinst
libavahi-client3.control
libavahi-client3.list
libavahi-client3.postinst
libavahi-common3.control
libavahi-common3.list
libavahi-common3.postinst
libavahi-glib1.control
libavahi-glib1.list
libavahi-glib1.postinst
libavcodec52.control
libavcodec52.list
libavcodec52.postinst
libavformat52.control
libavformat52.list
libavformat52.postinst
libavutil50.control
libavutil50.list
libavutil50.postinst
libblkid1.control
libblkid1.list
libblkid1.postinst
libbz2-1.control
libbz2-1.list
libbz2-1.postinst
libc6.control
libc6.list
libc6.postinst
libcairo2.control
libcairo2.list
libcairo2.postinst
libcanberra0.control
libcanberra0.list
libcanberra0.postinst
libcanberra-alsa.control
libcanberra-alsa.list
libcom-err2.control
libcom-err2.list
libcom-err2.postinst
libcroco.control
libcroco.list
libcroco.postinst
libcrypto0.9.8.control
libcrypto0.9.8.list
libcrypto0.9.8.postinst
libcups2.control
libcups2.list
libcups2.postinst
libcurl4.control
libcurl4.list
libcurl4.postinst
libdbus-1-3.control
libdbus-1-3.list
libdbus-1-3.postinst
libdbus-glib-1-2.control
libdbus-glib-1-2.list
libdbus-glib-1-2.postinst
libdmx1.control
libdmx1.list
libdmx1.postinst
libdrm.control
libdrm.list
libdrm.postinst
libdvdcss2.control
libdvdcss2.list
libdvdcss2.postinst
libdvdread3.control
libdvdread3.list
libdvdread3.postinst
libeet1.control
libeet1.list
libeet1.postinst
libelementary-ver-pre-svn-05-0.control
libelementary-ver-pre-svn-05-0.list
libelementary-ver-pre-svn-05-0.postinst
libelementary-ver-pre-svn-05-themes.control
libelementary-ver-pre-svn-05-themes.list
libelf0.control
libelf0.list
libelf0.postinst
libewebkit0.control
libewebkit0.list
libewebkit0.postinst
libexif12.control
libexif12.list
libexif12.postinst
libexosip2.control
libexosip2.list
libexosip2.postinst
libexpat1.control
libexpat1.list
libexpat1.postinst
libfaac0.control
libfaac0.list
libfaac0.postinst
libfakekey0.control
libfakekey0.list
libfakekey0.postinst
libffi5.control
libffi5.list
libffi5.postinst
libflac8.control
libflac8.list
libflac8.postinst
libfontconfig1.control
libfontconfig1.list
libfontconfig1.postinst
libfontenc1.control
libfontenc1.list
libfontenc1.postinst
libframeworkd-glib0.control
libframeworkd-glib0.list
libframeworkd-glib0.postinst
libfreetype6.control
libfreetype6.list
libfreetype6.postinst
libfribidi0.control
libfribidi0.list
libfribidi0.postinst
libfsobasics0.control
libfsobasics0.list
libfsobasics0.postinst
libfsoframework0.control
libfsoframework0.list
libfsoframework0.postinst
libfso-glib0.control
libfso-glib0.list
libfso-glib0.postinst
libfsoresource0.control
libfsoresource0.list
libfsoresource0.postinst
libfsotransport0.control
libfsotransport0.list
libfsotransport0.postinst
libgcc1.control
libgcc1.list
libgcc1.postinst
libgcrypt11.control
libgcrypt11.list
libgcrypt11.postinst
libgee2.control
libgee2.list
libgee2.postinst
libgio-2.0-0.control
libgio-2.0-0.list
libgio-2.0-0.postinst
libgl1.control
libgl1.list
libgl1.postinst
libglade-2.0-0.control
libglade-2.0-0.list
libglade-2.0-0.postinst
libglib-2.0-0.control
libglib-2.0-0.list
libglib-2.0-0.postinst
libglu1.control
libglu1.list
libglu1.postinst
libgmodule-2.0-0.control
libgmodule-2.0-0.list
libgmodule-2.0-0.postinst
libgmp3.control
libgmp3.list
libgmp3.postinst
libgnt0.control
libgnt0.list
libgnt0.postinst
libgnutls26.control
libgnutls26.list
libgnutls26.postinst
libgnutls-extra26.control
libgnutls-extra26.list
libgnutls-extra26.postinst
libgobject-2.0-0.control
libgobject-2.0-0.list
libgobject-2.0-0.postinst
libgoffice-0.8-8.control
libgoffice-0.8-8.list
libgoffice-0.8-8.postinst
libgoffice-0.8-plugin-plot-barcol.control
libgoffice-0.8-plugin-plot-barcol.list
libgoffice-0.8-plugin-plot-distrib.control
libgoffice-0.8-plugin-plot-distrib.list
libgoffice-0.8-plugin-plot-pie.control
libgoffice-0.8-plugin-plot-pie.list
libgoffice-0.8-plugin-plot-radar.control
libgoffice-0.8-plugin-plot-radar.list
libgoffice-0.8-plugin-plot-surface.control
libgoffice-0.8-plugin-plot-surface.list
libgoffice-0.8-plugin-plot-xy.control
libgoffice-0.8-plugin-plot-xy.list
libgoffice-0.8-plugin-reg-linear.control
libgoffice-0.8-plugin-reg-linear.list
libgoffice-0.8-plugin-reg-logfit.control
libgoffice-0.8-plugin-reg-logfit.list
libgoffice-0.8-plugin-smoothing.control
libgoffice-0.8-plugin-smoothing.list
libgpewidget1.control
libgpewidget1.list
libgpewidget1.postinst
libgpg-error0.control
libgpg-error0.list
libgpg-error0.postinst
libgpgme11.control
libgpgme11.list
libgpgme11.postinst
libgsf.control
libgsf.list
libgsf.postinst
libgsf.prerm
libgsm0710-0.control
libgsm0710-0.list
libgsm0710-0.postinst
libgsm0710mux0.control
libgsm0710mux0.list
libgsm0710mux0.postinst
libgsm1.control
libgsm1.list
libgsm1.postinst
libgstaudio-0.10-0.control
libgstaudio-0.10-0.list
libgstaudio-0.10-0.postinst
libgstfarsight-0.10-0.control
libgstfarsight-0.10-0.list
libgstfarsight-0.10-0.postinst
libgstinterfaces-0.10-0.control
libgstinterfaces-0.10-0.list
libgstinterfaces-0.10-0.postinst
libgstnetbuffer-0.10-0.control
libgstnetbuffer-0.10-0.list
libgstnetbuffer-0.10-0.postinst
libgstpbutils-0.10-0.control
libgstpbutils-0.10-0.list
libgstpbutils-0.10-0.postinst
libgstrtp-0.10-0.control
libgstrtp-0.10-0.list
libgstrtp-0.10-0.postinst
libgsttag-0.10-0.control
libgsttag-0.10-0.list
libgsttag-0.10-0.postinst
libgstvideo-0.10-0.control
libgstvideo-0.10-0.list
libgstvideo-0.10-0.postinst
libgthread-2.0-0.control
libgthread-2.0-0.list
libgthread-2.0-0.postinst
libgypsy0.control
libgypsy0.list
libgypsy0.postinst
libical.control
libical.list
libical.postinst
libice6.control
libice6.list
libice6.postinst
libicudata36.control
libicudata36.list
libicudata36.postinst
libicui18n36.control
libicui18n36.list
libicui18n36.postinst
libicuuc36.control
libicuuc36.list
libicuuc36.postinst
libid3tag0.control
libid3tag0.list
libid3tag0.postinst
libidl-2-0.control
libidl-2-0.list
libidl-2-0.postinst
libidn.control
libidn.list
libidn.postinst
libimlib2-1.control
libimlib2-1.list
libimlib2-1.postinst
libjasper1.control
libjasper1.list
libjasper1.postinst
libjpeg62.control
libjpeg62.list
libjpeg62.postinst
liblinebreak1.control
liblinebreak1.list
liblinebreak1.postinst
liblinphone3.control
liblinphone3.list
liblinphone3.postinst
liblockfile.control
liblockfile.list
liblockfile.postinst
libltdl7.control
libltdl7.list
libltdl7.postinst
liblzo1.control
liblzo1.list
liblzo1.postinst
libmad0.control
libmad0.list
libmad0.postinst
libmediastreamer0.control
libmediastreamer0.list
libmediastreamer0.postinst
libmp3lame0.control
libmp3lame0.list
libmp3lame0.postinst
libmpfr1.control
libmpfr1.list
libmpfr1.postinst
libnice.control
libnice.list
libnice.postinst
libnl2.control
libnl2.list
libnl2.postinst
libnl-genl2.control
libnl-genl2.list
libnl-genl2.postinst
libnl-nf2.control
libnl-nf2.list
libnl-nf2.postinst
libnl-route2.control
libnl-route2.list
libnl-route2.postinst
libode0.control
libode0.list
libode0.postinst
libogg0.control
libogg0.list
libogg0.postinst
liboil.control
liboil.list
liboil.postinst
libopkg0.control
libopkg0.list
libopkg0.postinst
libortp8.control
libortp8.list
libortp8.postinst
libosip2-3.control
libosip2-3.list
libosip2-3.postinst
libpam-base-files.control
libpam-base-files.list
libpam.control
libpam.list
libpam-meta.control
libpam-meta.list
libpam.postinst
libpcap.control
libpcap.list
libpcap.postinst
libpciaccess0.control
libpciaccess0.list
libpciaccess0.postinst
libperl5.control
libperl5.list
libperl5.postinst
libphone-ui0.conffiles
libphone-ui0.control
libphone-ui0.list
libphone-ui0.postinst
libphone-ui-shr.control
libphone-ui-shr.list
libphone-utils0.conffiles
libphone-utils0.control
libphone-utils0.list
libphone-utils0.postinst
libpixman-1-0.control
libpixman-1-0.list
libpixman-1-0.postinst
libpng12-0.control
libpng12-0.list
libpng12-0.postinst
libpng.control
libpng.list
libpoppler5.control
libpoppler5.list
libpoppler5.postinst
libpoppler-glib4.control
libpoppler-glib4.list
libpoppler-glib4.postinst
libpopt0.control
libpopt0.list
libpopt0.postinst
libportaudio2.control
libportaudio2.list
libportaudio2.postinst
libpostproc51.control
libpostproc51.list
libpostproc51.postinst
libpthread-stubs0.control
libpthread-stubs0.list
libpthread-stubs0.postinst
libpurple.control
libpurple.list
libpurple-plugin-ssl.control
libpurple-plugin-ssl-gnutls.control
libpurple-plugin-ssl-gnutls.list
libpurple-plugin-ssl.list
libpurple.postinst
libpurple.prerm
libpurple-protocol-icq.control
libpurple-protocol-icq.list
libpurple-protocol-irc.control
libpurple-protocol-irc.list
libpurple-protocol-msn.control
libpurple-protocol-msn.list
libpurple-protocol-xmpp.control
libpurple-protocol-xmpp.list
libpyglib-2.0-python0.control
libpyglib-2.0-python0.list
libpyglib-2.0-python0.postinst
libpython2.6-1.0.control
libpython2.6-1.0.list
libpython2.6-1.0.postinst
libreadline5.control
libreadline5.list
libreadline5.postinst
librsvg-2-2.control
librsvg-2-2.list
librsvg-2-2.postinst
librsvg-2-gtk.control
librsvg-2-gtk.list
librsvg-2-gtk.postinst
libschroedinger-1.0-0.control
libschroedinger-1.0-0.list
libschroedinger-1.0-0.postinst
libsdl-1.2-0.control
libsdl-1.2-0.list
libsdl-1.2-0.postinst
libsdl-image-1.2-0.control
libsdl-image-1.2-0.list
libsdl-image-1.2-0.postinst
libsdl-mixer-1.2-0.control
libsdl-mixer-1.2-0.list
libsdl-mixer-1.2-0.postinst
libsdl-ttf-2.0-0.control
libsdl-ttf-2.0-0.list
libsdl-ttf-2.0-0.postinst
libsm6.control
libsm6.list
libsm6.postinst
libsoup-2.2-8.control
libsoup-2.2-8.list
libsoup-2.2-8.postinst
libsoup-2.4-1.control
libsoup-2.4-1.list
libsoup-2.4-1.postinst
libspeex1.control
libspeex1.list
libspeex1.postinst
libspeexdsp1.control
libspeexdsp1.list
libspeexdsp1.postinst
libsqlite0.control
libsqlite0.list
libsqlite0.postinst
libsqlite3-0.control
libsqlite3-0.list
libsqlite3-0.postinst
libss2.control
libss2.list
libss2.postinst
libssl0.9.8.control
libssl0.9.8.list
libssl0.9.8.postinst
libstartup-notification-1-0.control
libstartup-notification-1-0.list
libstartup-notification-1-0.postinst
libstdc++6.control
libstdc++6.list
libstdc++6.postinst
libswscale0.control
libswscale0.list
libswscale0.postinst
libsysfs2.control
libsysfs2.list
libsysfs2.postinst
libtheora0.control
libtheora0.list
libtheora0.postinst
libthread-db1.control
libthread-db1.list
libthread-db1.postinst
libtiff5.control
libtiff5.list
libtiff5.postinst
libts-1.0-0.control
libts-1.0-0.list
libts-1.0-0.postinst
libungif4.control
libungif4.list
libungif4.postinst
libusb-0.1-4.control
libusb-0.1-4.list
libusb-0.1-4.postinst
libuuid1.control
libuuid1.list
libuuid1.postinst
libvorbis0.control
libvorbis0.list
libvorbis0.postinst
libvte9.control
libvte9.list
libvte9.postinst
libwebkit-1.0-2.control
libwebkit-1.0-2.list
libwebkit-1.0-2.postinst
libwrap0.control
libwrap0.list
libwrap0.postinst
libx11-6.control
libx11-6.list
libx11-6.postinst
libx11-locale.control
libx11-locale.list
libxau6.control
libxau6.list
libxau6.postinst
libxaw7-7.control
libxaw7-7.list
libxaw7-7.postinst
libxcalibrate0.control
libxcalibrate0.list
libxcalibrate0.postinst
libxcomposite1.control
libxcomposite1.list
libxcomposite1.postinst
libxcursor1.control
libxcursor1.list
libxcursor1.postinst
libxdamage1.control
libxdamage1.list
libxdamage1.postinst
libxdmcp6.control
libxdmcp6.list
libxdmcp6.postinst
libxext6.control
libxext6.list
libxext6.postinst
libxfixes3.control
libxfixes3.list
libxfixes3.postinst
libxfont1.control
libxfont1.list
libxfont1.postinst
libxfontcache1.control
libxfontcache1.list
libxfontcache1.postinst
libxft2.control
libxft2.list
libxft2.postinst
libxi6.control
libxi6.list
libxi6.postinst
libxinerama1.control
libxinerama1.list
libxinerama1.postinst
libxkbfile1.control
libxkbfile1.list
libxkbfile1.postinst
libxml2.control
libxml2.list
libxml2.postinst
libxmu6.control
libxmu6.list
libxmu6.postinst
libxmuu1.control
libxmuu1.list
libxmuu1.postinst
libxp6.control
libxp6.list
libxp6.postinst
libxpm4.control
libxpm4.list
libxpm4.postinst
libxrandr2.control
libxrandr2.list
libxrandr2.postinst
libxrender1.control
libxrender1.list
libxrender1.postinst
libxslt.control
libxslt.list
libxslt.postinst
libxss1.control
libxss1.list
libxss1.postinst
libxt6.control
libxt6.list
libxt6.postinst
libxtst6.control
libxtst6.list
libxtst6.postinst
libxv1.control
libxv1.list
libxv1.postinst
libxxf86dga1.control
libxxf86dga1.list
libxxf86dga1.postinst
libxxf86misc1.control
libxxf86misc1.list
libxxf86misc1.postinst
libxxf86vm1.control
libxxf86vm1.list
libxxf86vm1.postinst
libyaml-0-2.control
libyaml-0-2.list
libyaml-0-2.postinst
libz1.control
libz1.list
libz1.postinst
linphone.control
linphone.list
locale-base-en-us.control
locale-base-en-us.list
logrotate.conffiles
logrotate.control
logrotate.list
logrotate.postinst
logrotate.postrm
lsof.control
lsof.list
ltrace.control
ltrace.list
make.control
make.list
matchbox-keyboard-im.control
matchbox-keyboard-im.list
matchbox-keyboard-im.postinst
matchbox-keyboard-im.postrm
mbuffer.control
mbuffer.list
mdbus2.control
mdbus2.list
mesa-dri.control
mesa-dri.list
mesa-dri.postinst
mime-support.control
mime-support.list
mioctl.control
mioctl.list
mkdump.control
mkdump.list
mobile-broadband-provider-info.control
mobile-broadband-provider-info.list
module-init-tools.control
module-init-tools-depmod.control
module-init-tools-depmod.list
module-init-tools-depmod.postinst
module-init-tools-depmod.prerm
module-init-tools.list
module-init-tools.postinst
module-init-tools.prerm
modutils-initscripts.control
modutils-initscripts.list
modutils-initscripts.postinst
modutils-initscripts.postrm
modutils-initscripts.prerm
mokomaze.control
mokomaze.list
mplayer-common.control
mplayer-common.list
mplayer.conffiles
mplayer.control
mplayer.list
mtd-utils.control
mtd-utils.list
mterm2.control
mterm2.list
nano.control
nano.list
navit.conffiles
navit.control
navit-icons.control
navit-icons.list
navit.list
ncurses.control
ncurses.list
ncurses.postinst
netbase.conffiles
netbase.control
netbase.list
netbase.postinst
netbase.postrm
netbase.prerm
nfs-utils-client.control
nfs-utils-client.list
nmon.control
nmon.list
numptyphysics.control
numptyphysics.list
openssh.control
openssh-keygen.control
openssh-keygen.list
openssh.list
openssh-scp.control
openssh-scp.list
openssh-scp.postinst
openssh-scp.postrm
openssh-sftp-server.control
openssh-sftp-server.list
openssh-ssh.conffiles
openssh-ssh.control
openssh-sshd.conffiles
openssh-sshd.control
openssh-sshd.list
openssh-sshd.postinst
openssh-sshd.postrm
openssh-ssh.list
openssh-ssh.postinst
openssh-ssh.postrm
openssl.control
openssl.list
openvpn.control
openvpn.list
opimd-utils-cli.control
opimd-utils-cli.list
opimd-utils-data.control
opimd-utils-data.list
opimd-utils-notes.control
opimd-utils-notes.list
opkg-collateral.conffiles
opkg-collateral.control
opkg-collateral.list
opkg.control
opkg.list
opkg.postinst
opkg.postrm
orbit2.control
orbit2.list
orbit2.postinst
pam-plugin-access.control
pam-plugin-access.list
pam-plugin-debug.control
pam-plugin-debug.list
pam-plugin-deny.control
pam-plugin-deny.list
pam-plugin-echo.control
pam-plugin-echo.list
pam-plugin-env.control
pam-plugin-env.list
pam-plugin-exec.control
pam-plugin-exec.list
pam-plugin-faildelay.control
pam-plugin-faildelay.list
pam-plugin-filter.control
pam-plugin-filter.list
pam-plugin-ftp.control
pam-plugin-ftp.list
pam-plugin-group.control
pam-plugin-group.list
pam-plugin-issue.control
pam-plugin-issue.list
pam-plugin-keyinit.control
pam-plugin-keyinit.list
pam-plugin-lastlog.control
pam-plugin-lastlog.list
pam-plugin-limits.control
pam-plugin-limits.list
pam-plugin-listfile.control
pam-plugin-listfile.list
pam-plugin-localuser.control
pam-plugin-localuser.list
pam-plugin-loginuid.control
pam-plugin-loginuid.list
pam-plugin-mail.control
pam-plugin-mail.list
pam-plugin-mkhomedir.control
pam-plugin-mkhomedir.list
pam-plugin-motd.control
pam-plugin-motd.list
pam-plugin-namespace.control
pam-plugin-namespace.list
pam-plugin-nologin.control
pam-plugin-nologin.list
pam-plugin-permit.control
pam-plugin-permit.list
pam-plugin-pwhistory.control
pam-plugin-pwhistory.list
pam-plugin-rhosts.control
pam-plugin-rhosts.list
pam-plugin-rootok.control
pam-plugin-rootok.list
pam-plugin-securetty.control
pam-plugin-securetty.list
pam-plugin-shells.control
pam-plugin-shells.list
pam-plugin-stress.control
pam-plugin-stress.list
pam-plugin-succeed-if.control
pam-plugin-succeed-if.list
pam-plugin-tally2.control
pam-plugin-tally2.list
pam-plugin-tally.control
pam-plugin-tally.list
pam-plugin-time.control
pam-plugin-time.list
pam-plugin-timestamp.control
pam-plugin-timestamp.list
pam-plugin-umask.control
pam-plugin-umask.list
pam-plugin-unix.control
pam-plugin-unix.list
pam-plugin-warn.control
pam-plugin-warn.list
pam-plugin-wheel.control
pam-plugin-wheel.list
pam-plugin-xauth.control
pam-plugin-xauth.list
pango.control
pango.list
pango-module-basic-fc.control
pango-module-basic-fc.list
pango-module-basic-fc.postinst
pango-module-basic-x.control
pango-module-basic-x.list
pango-module-basic-x.postinst
pango.postinst
perl.control
perl.list
perl-module-carp.control
perl-module-carp.list
perl-module-exporter.control
perl-module-exporter.list
perl-module-file-basename.control
perl-module-file-basename.list
perl-module-file-path.control
perl-module-file-path.list
perl-module-strict.control
perl-module-strict.list
perl-module-warnings.control
perl-module-warnings.list
phonefsod.conffiles
phonefsod.control
phonefsod.list
phonefsod.postinst
phonefsod.postrm
phonefsod.prerm
phoneui-apps-contacts.control
phoneui-apps-contacts.list
phoneui-apps-dialer.control
phoneui-apps-dialer.list
phoneui-apps-messages.control
phoneui-apps-messages.list
phoneui-apps-quick-settings.control
phoneui-apps-quick-settings.list
phoneuid.conffiles
phoneuid.control
phoneuid.list
pidgin.control
pidgin-data.control
pidgin-data.list
pidgin.list
pingus.control
pingus.list
pointercal.control
pointercal.list
policykit.control
policykit.list
policykit.postinst
policykit.postrm
poppler-data.control
poppler-data.list
portmap.control
portmap.list
portmap.postinst
portmap.postrm
portmap.prerm
powertop.control
powertop.list
ppp.conffiles
ppp.control
ppp-dialin.control
ppp-dialin.list
ppp-dialin.postinst
ppp-dialin.postrm
ppp.list
ppp.postinst
procps.conffiles
procps.control
procps.list
procps.postinst
procps.postrm
procps.prerm
pth.control
pth.list
pth.postinst
pxaregs.control
pxaregs.list
pyefl-sudoku.control
pyefl-sudoku.list
pyphonelog.control
pyphonelog.list
python-codecs.control
python-codecs.list
python-core.control
python-core.list
python-crypt.control
python-crypt.list
python-ctypes.control
python-ctypes.list
python-datetime.control
python-datetime.list
python-dateutil.control
python-dateutil.list
python-dbus.control
python-dbus.list
python-difflib.control
python-difflib.list
python-ecore.control
python-ecore.list
python-edbus.control
python-edbus.list
python-edje.control
python-edje.list
python-elementary.control
python-elementary.list
python-evas.control
python-evas.list
python-fcntl.control
python-fcntl.list
python-gst.control
python-gst.list
python-io.control
python-io.list
python-lang.control
python-lang.list
python-logging.control
python-logging.list
python-math.control
python-math.list
python-multiprocessing.control
python-multiprocessing.list
python-pexpect.control
python-pexpect.list
python-phoneutils.control
python-phoneutils.list
python-pickle.control
python-pickle.list
python-pprint.control
python-pprint.list
python-pyalsaaudio.control
python-pyalsaaudio.list
python-pycairo.control
python-pycairo.list
python-pygobject.control
python-pygobject.list
python-pygtk.control
python-pygtk.list
python-pyrtc.control
python-pyrtc.list
python-pyserial.control
python-pyserial.list
python-pyyaml.control
python-pyyaml.list
python-readline.control
python-readline.list
python-re.control
python-re.list
python-resource.control
python-resource.list
python-shell.control
python-shell.list
python-sqlite3.control
python-sqlite3.list
python-stringold.control
python-stringold.list
python-subprocess.control
python-subprocess.list
python-syslog.control
python-syslog.list
python-terminal.control
python-terminal.list
python-textutils.control
python-textutils.list
python-threading.control
python-threading.list
python-vobject.control
python-vobject.list
python-xml.control
python-xml.list
python-zlib.control
python-zlib.list
rgb.control
rgb.list
rsync.control
rsync.list
s3c24xx-gpio.control
s3c24xx-gpio.list
s3c64xx-gpio.control
s3c64xx-gpio.list
screen.control
screen.list
sed.control
sed.list
sed.postinst
sed.prerm
serial-forward.control
serial-forward.list
shared-mime-info.control
shared-mime-info.list
shr-settings-addons-illume.control
shr-settings-addons-illume.list
shr-settings-backup-configuration.conffiles
shr-settings-backup-configuration.control
shr-settings-backup-configuration.list
shr-settings.control
shr-settings.list
shr-splash.control
shr-splash.list
shr-splash.postinst
shr-splash.postrm
shr-splash.prerm
shr-splash-theme-simple.control
shr-splash-theme-simple.list
shr-splash-theme-simple.postinst
shr-splash-theme-simple.postrm
shr-theme.control
shr-theme-gry.control
shr-theme-gry.list
shr-theme-gtk-e17lookalike.control
shr-theme-gtk-e17lookalike.list
shr-theme-gtk-e17lookalike.postinst
shr-theme-gtk-e17lookalike.postrm
shr-theme.list
shr-wizard.control
shr-wizard.list
socat.control
socat.list
strace.control
strace.list
synergy.control
synergy.list
sysfsutils.control
sysfsutils.list
sysstat.control
sysstat.list
sysvinit.control
sysvinit-inittab.conffiles
sysvinit-inittab.control
sysvinit-inittab.list
sysvinit.list
sysvinit-pidof.control
sysvinit-pidof.list
sysvinit-pidof.postinst
sysvinit-pidof.prerm
sysvinit.postinst
sysvinit.postrm
sysvinit.prerm
sysvinit-utils.control
sysvinit-utils.list
sysvinit-utils.postinst
sysvinit-utils.prerm
tangogps.control
tangogps.list
task-base-apm.control
task-base-apm.list
task-base-bluetooth.control
task-base-bluetooth.list
task-base.control
task-base-ext2.control
task-base-ext2.list
task-base-kernel26.control
task-base-kernel26.list
task-base.list
task-base-ppp.control
task-base-ppp.list
task-base-usbgadget.control
task-base-usbgadget.list
task-base-usbhost.control
task-base-usbhost.list
task-base-vfat.control
task-base-vfat.list
task-base-wifi.control
task-base-wifi.list
task-boot.control
task-boot.list
task-cli-tools.control
task-cli-tools-debug.control
task-cli-tools-debug.list
task-cli-tools.list
task-distro-base.control
task-distro-base.list
task-fonts-truetype-core.control
task-fonts-truetype-core.list
task-fso2-compliance.control
task-fso2-compliance.list
task-machine-base.control
task-machine-base.list
task-shr-apps.control
task-shr-apps.list
task-shr-cli.control
task-shr-cli.list
task-shr-games.control
task-shr-games.list
task-shr-gtk.control
task-shr-gtk.list
task-shr-minimal-apps.control
task-shr-minimal-apps.list
task-shr-minimal-audio.control
task-shr-minimal-audio.list
task-shr-minimal-base.control
task-shr-minimal-base.list
task-shr-minimal-cli.control
task-shr-minimal-cli.list
task-shr-minimal-fso.control
task-shr-minimal-fso.list
task-shr-minimal-gtk.control
task-shr-minimal-gtk.list
task-shr-minimal-x.control
task-shr-minimal-x.list
task-x11-illume.control
task-x11-illume.list
task-x11-server.control
task-x11-server.list
task-x11-utils.control
task-x11-utils.list
tcpdump.control
tcpdump.list
tinylogin.control
tinylogin.list
tinylogin.postinst
tinylogin.prerm
tslib-calibrate.control
tslib-calibrate.list
tslib-conf.control
tslib-conf.list
ttf-dejavu-common.control
ttf-dejavu-common.list
ttf-dejavu-common.postinst
ttf-dejavu-common.postrm
ttf-dejavu-sans.control
ttf-dejavu-sans.list
ttf-dejavu-sans-mono.control
ttf-dejavu-sans-mono.list
ttf-dejavu-sans-mono.postinst
ttf-dejavu-sans-mono.postrm
ttf-dejavu-sans.postinst
ttf-dejavu-sans.postrm
ttf-liberation-mono.control
ttf-liberation-mono.list
ttf-liberation-mono.postinst
ttf-liberation-mono.postrm
tzdata-africa.control
tzdata-africa.list
tzdata-americas.control
tzdata-americas.list
tzdata-asia.control
tzdata-asia.list
tzdata-australia.control
tzdata-australia.list
tzdata.conffiles
tzdata.control
tzdata-europe.control
tzdata-europe.list
tzdata.list
udev.control
udev.list
udev.postinst
udev.postrm
udev.prerm
udev-utils.control
udev-utils.list
update-modules.control
update-modules.list
update-modules.postinst
update-rc.d.control
update-rc.d.list
usb-gadget-mode.control
usb-gadget-mode.list
usb-gadget-mode.postinst
usb-gadget-mode.postrm
usbutils.control
usbutils.list
util-linux-ng-blkid.control
util-linux-ng-blkid.list
util-linux-ng-blkid.postinst
util-linux-ng-blkid.prerm
util-linux-ng-cfdisk.control
util-linux-ng-cfdisk.list
util-linux-ng.control
util-linux-ng-fdisk.control
util-linux-ng-fdisk.list
util-linux-ng-fdisk.postinst
util-linux-ng-fdisk.prerm
util-linux-ng-fsck.control
util-linux-ng-fsck.list
util-linux-ng-fsck.postinst
util-linux-ng-fsck.prerm
util-linux-ng.list
util-linux-ng-losetup.control
util-linux-ng-losetup.list
util-linux-ng-losetup.postinst
util-linux-ng-losetup.prerm
util-linux-ng-mountall.control
util-linux-ng-mountall.list
util-linux-ng-mountall.postinst
util-linux-ng-mountall.prerm
util-linux-ng-mount.control
util-linux-ng-mount.list
util-linux-ng-mount.postinst
util-linux-ng-mount.prerm
util-linux-ng.postinst
util-linux-ng.prerm
util-linux-ng-readprofile.control
util-linux-ng-readprofile.list
util-linux-ng-readprofile.postinst
util-linux-ng-readprofile.prerm
util-linux-ng-sfdisk.control
util-linux-ng-sfdisk.list
util-linux-ng-swaponoff.control
util-linux-ng-swaponoff.list
util-linux-ng-swaponoff.postinst
util-linux-ng-swaponoff.prerm
util-linux-ng-umount.control
util-linux-ng-umount.list
util-linux-ng-umount.postinst
util-linux-ng-umount.prerm
vagalume.control
vagalume.list
vala-terminal.control
vala-terminal.list
ventura.control
ventura.list
vnc.control
vnc.list
vpnc.conffiles
vpnc.control
vpnc.list
vte-termcap.control
vte-termcap.list
wireless-tools.control
wireless-tools.list
wmiconfig.control
wmiconfig.list
wpa-supplicant.control
wpa-supplicant.list
wpa-supplicant-passphrase.control
wpa-supplicant-passphrase.list
wv.control
wv.list
wv.postinst
x11vnc.control
x11vnc.list
xauth.control
xauth.list
xcursor-transparent-theme.control
xcursor-transparent-theme.list
xdpyinfo.control
xdpyinfo.list
xf86-input-evdev.control
xf86-input-evdev.list
xf86-input-keyboard.control
xf86-input-keyboard.list
xf86-input-mouse.control
xf86-input-mouse.list
xf86-input-tslib.control
xf86-input-tslib.list
xf86-video-glamo.control
xf86-video-glamo.list
xhost.control
xhost.list
xinit.control
xinit.list
xinput-calibrator.control
xinput-calibrator.list
xinput.control
xinput.list
xkbcomp.control
xkbcomp.list
xkeyboard-config.control
xkeyboard-config.list
xmodmap.control
xmodmap.list
xorg-minimal-fonts.control
xorg-minimal-fonts.list
xrandr.control
xrandr.list
xserver-kdrive-common.control
xserver-kdrive-common.list
xserver-nodm-init.control
xserver-nodm-init.list
xserver-nodm-init.postinst
xserver-nodm-init.postrm
xserver-nodm-init.prerm
xserver-xorg-conf.conffiles
xserver-xorg-conf.control
xserver-xorg-conf.list
xserver-xorg.control
xserver-xorg-extension-dri2.control
xserver-xorg-extension-dri2.list
xserver-xorg-extension-dri.control
xserver-xorg-extension-dri.list
xserver-xorg-extension-glx.control
xserver-xorg-extension-glx.list
xserver-xorg.list
xset.control
xset.list
xtscal.control
xtscal.list"

mount /mnt/ceph-fuse
: cd /mnt/ceph-fuse

mkdir test-1774
cd test-1774
for f in $list; do
  touch $f
done

cd
umount /mnt/ceph-fuse
mount /mnt/ceph-fuse
cd -

# this worked before the 1774 fix
diff <(ls) <(echo "$list")

# but this failed, because we cached the dirlist wrong
# update-modules.postinst used to be the missing file,
# the last one in the first dirent set passed to ceph-fuse
diff <(ls) <(echo "$list")

cd ..
rm -rf test-1774

cd
umount /mnt/ceph-fuse
