function(target_create _target _lib)
  add_library(${_target} STATIC IMPORTED)
  set_target_properties(
    ${_target} PROPERTIES IMPORTED_LOCATION
                          "${opentelemetry_BINARY_DIR}/${_lib}")
endfunction()

# Attempt to locate a system gRPC installation.
#
# On RHEL/Fedora, gRPC ships a proper CMake config under
# /usr/lib64/cmake/grpc so find_package(gRPC CONFIG) just works.
# On Ubuntu, only pkg-config metadata is provided (no CMake config files)
# so find_package(gRPC CONFIG) fails and opentelemetry-cpp's cmake/grpc.cmake
# falls through to FetchContent, pulling a different gRPC version from GitHub.
#
# To solve this for both distros we:
#   1. Try find_package(gRPC CONFIG) first.
#   2. If that fails, try pkg-config for grpc++.
#   3. If pkg-config succeeds, generate a minimal gRPCConfig.cmake shim in the
#      build tree that creates the gRPC::grpc++ / gRPC::grpc_cpp_plugin targets
#      from the system shared libraries.
#   4. Pass -DgRPC_DIR=<shim dir> into the ExternalProject CMAKE_ARGS so
#      opentelemetry-cpp's find_package(gRPC CONFIG) resolves the shim and
#      never falls through to FetchContent.
function(_otel_find_system_grpc out_grpc_dir out_grpc_found)
  find_package(gRPC CONFIG QUIET)
  if(gRPC_FOUND)
    message(STATUS "gRPC: found via CMake config (${gRPC_VERSION})")
    # Already on CMAKE_PREFIX_PATH — no extra -DgRPC_DIR needed
    set(${out_grpc_dir} "" PARENT_SCOPE)
    set(${out_grpc_found} TRUE PARENT_SCOPE)
    return()
  endif()

  find_package(PkgConfig QUIET)
  if(NOT PkgConfig_FOUND)
    message(STATUS "gRPC: CMake config not found and PkgConfig unavailable — "
                   "opentelemetry-cpp will fetch gRPC from GitHub")
    set(${out_grpc_found} FALSE PARENT_SCOPE)
    return()
  endif()

  pkg_check_modules(GRPCPP_PC QUIET grpc++)
  if(NOT GRPCPP_PC_FOUND)
    message(STATUS "gRPC: CMake config not found and pkg-config has no grpc++ entry — "
                   "opentelemetry-cpp will fetch gRPC from GitHub")
    set(${out_grpc_found} FALSE PARENT_SCOPE)
    return()
  endif()

  message(STATUS "gRPC: found via pkg-config (${GRPCPP_PC_VERSION}), "
                 "generating shim gRPCConfig.cmake for opentelemetry-cpp")

  # Locate the grpc_cpp_plugin binary
  find_program(_grpc_cpp_plugin grpc_cpp_plugin
    HINTS "${GRPCPP_PC_PREFIX}"
    PATH_SUFFIXES bin)
  if(NOT _grpc_cpp_plugin)
    message(STATUS "gRPC: grpc_cpp_plugin not found — "
                   "opentelemetry-cpp will fetch gRPC from GitHub")
    set(${out_grpc_found} FALSE PARENT_SCOPE)
    return()
  endif()

  # Write a minimal gRPCConfig.cmake into the build tree.
  # opentelemetry-cpp only needs gRPC::grpc++ and gRPC::grpc_cpp_plugin.
  #
  # We bake all values in at generation time (not as CMake variables) so the
  # shim is self-contained when opentelemetry-cpp's sub-build reads it.
  # GRPCPP_PC_LINK_LIBRARIES is a CMake list (semicolon-separated); we must
  # escape the semicolons so file(WRITE) doesn't collapse them and the string
  # arrives as a proper CMake list inside the generated file.
  string(REPLACE ";" "\\;" _grpc_link_libs_escaped "${GRPCPP_PC_LINK_LIBRARIES}")

  set(_shim_dir "${CMAKE_CURRENT_BINARY_DIR}/grpc-shim")
  file(MAKE_DIRECTORY "${_shim_dir}")
  file(WRITE "${_shim_dir}/gRPCConfig.cmake"
"# Auto-generated by Ceph's BuildOpentelemetry.cmake
# Wraps the system gRPC shared libraries found via pkg-config.
set(gRPC_VERSION \"${GRPCPP_PC_VERSION}\")
set(gRPC_FOUND TRUE)

if(NOT TARGET gRPC::grpc++)
  add_library(gRPC::grpc++ SHARED IMPORTED)
  set_target_properties(gRPC::grpc++ PROPERTIES
    IMPORTED_LOCATION             \"${GRPCPP_PC_LIBDIR}/libgrpc++${CMAKE_SHARED_LIBRARY_SUFFIX}\"
    INTERFACE_INCLUDE_DIRECTORIES \"${GRPCPP_PC_INCLUDEDIR}\"
    INTERFACE_LINK_LIBRARIES      \"${_grpc_link_libs_escaped}\")
endif()

if(NOT TARGET gRPC::grpc_cpp_plugin)
  add_executable(gRPC::grpc_cpp_plugin IMPORTED)
  set_target_properties(gRPC::grpc_cpp_plugin PROPERTIES
    IMPORTED_LOCATION \"${_grpc_cpp_plugin}\")
endif()
")

  set(${out_grpc_dir} "${_shim_dir}" PARENT_SCOPE)
  set(${out_grpc_found} TRUE PARENT_SCOPE)
endfunction()

function(build_opentelemetry)
  set(opentelemetry_SOURCE_DIR "${PROJECT_SOURCE_DIR}/src/jaegertracing/opentelemetry-cpp")
  set(opentelemetry_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/opentelemetry-cpp")
  set(opentelemetry_cpp_targets opentelemetry_trace opentelemetry_exporter_otlp_grpc opentelemetry_exporter_otlp_grpc_client)
  set(opentelemetry_CMAKE_ARGS -DCMAKE_POSITION_INDEPENDENT_CODE=ON
                               -DWITH_OTLP_GRPC=ON
                               -DWITH_OTLP_HTTP=OFF
                               -DBUILD_SHARED_LIBS=OFF
                               -DBUILD_TESTING=OFF
                               -DCMAKE_BUILD_TYPE=Release
                               -DWITH_EXAMPLES=OFF)

  set(opentelemetry_libs
      ${opentelemetry_BINARY_DIR}/sdk/src/trace/libopentelemetry_trace.a
      ${opentelemetry_BINARY_DIR}/sdk/src/logs/libopentelemetry_logs.a
      ${opentelemetry_BINARY_DIR}/sdk/src/resource/libopentelemetry_resources.a
      ${opentelemetry_BINARY_DIR}/sdk/src/common/libopentelemetry_common.a
      ${opentelemetry_BINARY_DIR}/exporters/otlp/libopentelemetry_exporter_otlp_grpc.a
      ${opentelemetry_BINARY_DIR}/exporters/otlp/libopentelemetry_otlp_recordable.a
      ${opentelemetry_BINARY_DIR}/exporters/otlp/libopentelemetry_exporter_otlp_grpc_client.a
      ${opentelemetry_BINARY_DIR}/libopentelemetry_proto.a
      ${opentelemetry_BINARY_DIR}/libopentelemetry_proto_grpc.a
      #${CURL_LIBRARIES}
  )

  # Base include directories that exist in source tree
  set(opentelemetry_include_dir_base
      ${opentelemetry_SOURCE_DIR}/api/include/
      ${opentelemetry_SOURCE_DIR}/exporters/otlp/include/
      ${opentelemetry_SOURCE_DIR}/ext/include/
      ${opentelemetry_SOURCE_DIR}/sdk/include/)

  # Include directories that will be created by the build
  set(opentelemetry_include_dir_generated
      ${opentelemetry_BINARY_DIR}
      ${opentelemetry_BINARY_DIR}/generated/third_party/opentelemetry-proto)

  # Locate system gRPC (CMake config or pkg-config shim) so that
  # opentelemetry-cpp's internal find_package(gRPC CONFIG) succeeds and does
  # not fall through to FetchContent.
  _otel_find_system_grpc(_grpc_shim_dir _grpc_system_found)

  if(_grpc_system_found)
    # Tell opentelemetry-cpp's sub-build exactly where to find gRPC's config.
    if(_grpc_shim_dir)
      list(APPEND opentelemetry_CMAKE_ARGS "-DgRPC_DIR=${_grpc_shim_dir}")
    endif()
    # Also pass along Protobuf if the outer CMake already found it.
    find_package(Protobuf QUIET)
    if(Protobuf_FOUND)
      list(APPEND opentelemetry_CMAKE_ARGS
           "-DProtobuf_ROOT=${Protobuf_DIR}")
    endif()
  else()
    message(STATUS "opentelemetry-cpp: no system gRPC found — "
                   "sub-build will fetch gRPC from GitHub")
  endif()

  # Resolve include dirs for the outer (Ceph) build.
  # After the sub-build runs, generated proto headers appear under
  # opentelemetry_BINARY_DIR; gRPC headers come from the system (or will be
  # under _deps if fetched).
  set(opentelemetry_include_dir_deps "")
  if(_grpc_system_found)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
      pkg_check_modules(GRPCPP_PC QUIET grpc++)
    endif()
    if(GRPCPP_PC_FOUND)
      list(APPEND opentelemetry_include_dir_deps "${GRPCPP_PC_INCLUDEDIR}")
    elseif(gRPC_FOUND AND TARGET gRPC::grpc++)
      get_target_property(_grpc_inc gRPC::grpc++ INTERFACE_INCLUDE_DIRECTORIES)
      if(_grpc_inc)
        list(APPEND opentelemetry_include_dir_deps ${_grpc_inc})
      endif()
    endif()
    if(Protobuf_FOUND)
      list(APPEND opentelemetry_include_dir_deps ${Protobuf_INCLUDE_DIRS})
    endif()
  else()
    # Paths produced by opentelemetry-cpp's FetchContent of gRPC
    list(APPEND opentelemetry_include_dir_deps
         ${opentelemetry_BINARY_DIR}/_deps/grpc-src/include
         ${opentelemetry_BINARY_DIR}/_deps/grpc-build
         ${opentelemetry_BINARY_DIR}/_deps/grpc-src/third_party/protobuf/src
         ${opentelemetry_BINARY_DIR}/_deps/grpc-build/third_party/protobuf
         ${opentelemetry_BINARY_DIR}/_deps/grpc-src/third_party/abseil-cpp)
  endif()

  # Combine all include directories
  set(opentelemetry_include_dir
      ${opentelemetry_include_dir_base}
      ${opentelemetry_include_dir_generated}
      ${opentelemetry_include_dir_deps})

  # TODO: add target based propogation
  set(opentelemetry_deps
      opentelemetry_exporter_otlp_grpc
      opentelemetry_exporter_otlp_grpc_client
      opentelemetry_otlp_recordable
      opentelemetry_proto_grpc
      opentelemetry_proto
      opentelemetry_trace
      opentelemetry_logs
      opentelemetry_resources
      opentelemetry_common
  )

  # When using the system gRPC the opentelemetry static archives do NOT bundle
  # grpc symbols, so we must link the system shared library.
  if(_grpc_system_found)
    if(GRPCPP_PC_FOUND)
      list(APPEND opentelemetry_deps ${GRPCPP_PC_LINK_LIBRARIES})
    elseif(TARGET gRPC::grpc++)
      list(APPEND opentelemetry_deps gRPC::grpc++)
    endif()
    if(Protobuf_FOUND AND PROTOBUF_LIBRARIES)
      list(APPEND opentelemetry_deps ${PROTOBUF_LIBRARIES})
    endif()
  endif()

  if(CMAKE_MAKE_PROGRAM MATCHES "make")
    # try to inherit command line arguments passed by parent "make" job
    set(make_cmd $(MAKE) ${opentelemetry_cpp_targets})
  else()
    set(make_cmd ${CMAKE_COMMAND} --build <BINARY_DIR> --target
                 ${opentelemetry_cpp_targets})
  endif()

  if(WITH_SYSTEM_BOOST)
    list(APPEND opentelemetry_CMAKE_ARGS -DBOOST_ROOT=${BOOST_ROOT})
  else()
    list(APPEND dependencies Boost)
    list(APPEND opentelemetry_CMAKE_ARGS -DBoost_INCLUDE_DIR=${CMAKE_BINARY_DIR}/boost/include)
  endif()

  # Check if CMake version is >= 4.0.0
  if(CMAKE_VERSION VERSION_GREATER_EQUAL "4.0.0")
    # Use CMAKE_POLICY_VERSION_MINIMUM if set, otherwise default to 3.5
    if(DEFINED CMAKE_POLICY_VERSION_MINIMUM)
      list(APPEND opentelemetry_CMAKE_ARGS -DCMAKE_POLICY_VERSION_MINIMUM=${CMAKE_POLICY_VERSION_MINIMUM})
    else()
      list(APPEND opentelemetry_CMAKE_ARGS -DCMAKE_POLICY_VERSION_MINIMUM=3.5)
    endif()
  endif()

  include(ExternalProject)
  ExternalProject_Add(opentelemetry-cpp
    SOURCE_DIR ${opentelemetry_SOURCE_DIR}
    PREFIX "opentelemetry-cpp"
    CMAKE_ARGS ${opentelemetry_CMAKE_ARGS}
    BUILD_COMMAND ${make_cmd}
    BINARY_DIR ${opentelemetry_BINARY_DIR}
    INSTALL_COMMAND ""
    BUILD_BYPRODUCTS ${opentelemetry_libs}
    DEPENDS ${dependencies}
    LOG_BUILD ON)

  # CMake doesn't allow to add a list of libraries to the import property, hence
  # we create individual targets and link their libraries which finally
  # interfaces to opentelemetry target
  target_create("opentelemetry_exporter_otlp_grpc" "exporters/otlp/libopentelemetry_exporter_otlp_grpc.a")
  target_create("opentelemetry_exporter_otlp_grpc_client" "exporters/otlp/libopentelemetry_exporter_otlp_grpc_client.a")
  target_create("opentelemetry_otlp_recordable" "exporters/otlp/libopentelemetry_otlp_recordable.a")
  target_create("opentelemetry_trace" "sdk/src/trace/libopentelemetry_trace.a")
  target_create("opentelemetry_resources"
                "sdk/src/resource/libopentelemetry_resources.a")
  target_create("opentelemetry_common"
                "sdk/src/common/libopentelemetry_common.a")
  target_create("opentelemetry_logs" "sdk/src/logs/libopentelemetry_logs.a")
  target_create("opentelemetry_proto" "libopentelemetry_proto.a")
  target_create("opentelemetry_proto_grpc" "libopentelemetry_proto_grpc.a")

  # Create directories that should exist at configure time
  # (generated directories will be created by the ExternalProject build)
  file(MAKE_DIRECTORY ${opentelemetry_include_dir_generated})

  # Set up the interface library with all include directories
  add_library(opentelemetry::libopentelemetry INTERFACE IMPORTED)
  add_dependencies(opentelemetry::libopentelemetry opentelemetry-cpp)
  set_target_properties(
    opentelemetry::libopentelemetry
    PROPERTIES
      INTERFACE_LINK_LIBRARIES "${opentelemetry_deps}"
      INTERFACE_INCLUDE_DIRECTORIES "${opentelemetry_include_dir}")

  # Add include directories globally (SYSTEM to suppress warnings)
  # Note: Non-existent directories will be ignored by the compiler
  include_directories(SYSTEM ${opentelemetry_include_dir})
endfunction()
