#!/usr/bin/perl

# hi there
{
	'sleep' => 3,
	'kill_after' => 300,

	'nummds' => 1,
	'numosd' => 8,
	'numclient' => 100,
	'n' => 16,

	# parameters
	'fs' => ['fakestore'],
	'meta_log_ssize' => [ 128, 256, 1024, 1 << 15, 1 << 20 ],
	'meta_log_scount' => 4,#[ 1, 2, 4, 8 ],

	'until' => 200,     # --syn until $n    ... when to stop clients
	
	'makedirs' => 1,
	'makedirs_dirs' => 10,
	'makedirs_files' => 10,
	'makedirs_depth' => 4,
		
	'custom' => '--tcp_skip_rank0',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	# for final summation (script/sum.pl)
	'start' => 100,
	'end' => 550,

	'comb' => {
		'x' => 'nummds',
		'vars' => [ 'mds.req' ]
	}
};
