#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'nummds' => [1, 2, 4, 7], # googoo
	#'nummds' => [1, 2, 4, 6, 8, 12, 16, 24, 32, 40, 48, 64], # alc

	
	# parameters
	'fs' => 'ebofs',
	#'fs' => 'fakestore',

	'until' => 300,     # --syn until $n    ... when to stop clients
	'kill_after' => 400,
	'start' => 150,
	'end' => 300,
	
	'mds_bal_interval' => 90,#[60, 90],
	#'mds_bal_max' => [3,4,5],
	'mds_bal_max' => 4,
	'mds_decay_halflife' => 30,#[15, 25, 30, 45, 60],
	'mds_bal_rep' => 1500,#[1000, 1500, 2000],

	'decay_hl' => 100,#[ 25, 50, 100, 150 ],

	'cper' => 100, #[50, 75, 100, 125, 150, 200],
	'_dep' => [ 'cnode' => '$nummds',
				'numclient' => '$nummds * $cper',
				'numosd' => '$nummds * 2',
				'n' => '1 + $cnode + $nummds + $numosd',
				'mds_bal_rep' => '$mds_decay_halflife * $decay_hl'],
		
	'custom' => '--tcp_skip_rank0 --syn only 0 --syn trace traces/openssh/untar.lib 1 --syn sleep 10 --syn randomsleep 30 --syn trace traces/openssh/make.lib 100 --debug_mds_balancer 1 --mds_shutdown_check 60',
	#'custom' => '--debug_after 110 --debug_osd 15 --debug_filer 15 --debug 5',
	
	# for final summation (script/sum.pl)

	'comb' => {
		'x' => 'nummds',#decay_hl',#'nummds',
		'vars' => [ 'mds.req' ]
	}
};
