"""
Task for dnsmasq configuration
"""
import contextlib
import logging
import re

from teuthology import misc
from teuthology.exceptions import ConfigError
from teuthology import contextutil
from teuthology import packaging
from tasks.util import get_remote_for_role

log = logging.getLogger(__name__)

@contextlib.contextmanager
def install_dnsmasq(remote):
    """
    If dnsmasq is not installed, install it for the duration of the task.
    """
    try:
        existing = packaging.get_package_version(remote, 'dnsmasq')
    except:
        existing = None

    if existing is None:
        packaging.install_package('dnsmasq', remote)
    try:
        yield
    finally:
        if existing is None:
            packaging.remove_package('dnsmasq', remote)

@contextlib.contextmanager
def backup_resolv(remote, path, table):
    """
    Store a backup of resolv.conf in the testdir and restore it after the task.
    Reserve 'nameserver' values per remote name in lookup 'table' for future use.
    """
    resolv_conf = remote.sh(f"cat /etc/resolv.conf | tee {path}")
    nameserver_re = re.compile(r'\s*nameserver\s+([^\s]*)')
    for line in resolv_conf.split('\n'):
        if m := nameserver_re.match(line):
            table.setdefault(remote.name, {}).setdefault('nameserver', []).append(m[1])
    try:
        yield
    finally:
        # restore with 'cp' to avoid overwriting its security context
        remote.run(args=['sudo', 'cp', path, '/etc/resolv.conf'])
        remote.run(args=['rm', path])

@contextlib.contextmanager
def replace_resolv(remote, path, table):
    """
    Update resolv.conf to point the nameserver at localhost.
    """
    remote.write_file(path, "nameserver 127.0.0.1\n")
    try:
        # install it
        if remote.os.package_type == "rpm":
            # for centos ovh resolv.conf has immutable attribute set
            remote.run(args=['sudo', 'chattr', '-i', '/etc/resolv.conf'], check_status=False)
        remote.run(args=['sudo', 'cp', path, '/etc/resolv.conf'])
        yield
    finally:
        remote.run(args=['rm', path])

@contextlib.contextmanager
def configure_dnsmasq(remote, path, cnames):
    """
    configure dnsmasq on the given remote, adding each cname given
    """
    data = """# This file is generated by dnsmasq teuthology task
"""
    for cname, ip_address in cnames.items():
        data += f"address=/.{cname}/{ip_address}\n"

    remote.sudo_write_file(path, data)
    remote.run(args=['sudo', 'restorecon', path], check_status=False)
    remote.sh(f'cat {path}')
    try:
        yield
    finally:
        remote.run(args=['sudo', 'rm', path])

@contextlib.contextmanager
def configure_network_manager(remote):
    """
    enable NetworkManager's dnsmasq plugin
    """
    path = '/etc/NetworkManager/conf.d/dnsmasq.conf'
    data = """# This file is generated by dnsmasq teuthology task
[main]
dns=dnsmasq
"""
    remote.sudo_write_file(path, data)
    remote.run(args=['sudo', 'restorecon', path], check_status=False)
    remote.run(args=['sudo', 'systemctl', 'restart', 'NetworkManager'])
    remote.sh(f'cat {path}')
    try:
        yield
    finally:
        remote.run(args=['sudo', 'rm', path])
        remote.run(args=['sudo', 'systemctl', 'restart', 'NetworkManager'])

@contextlib.contextmanager
def configure_systemd_resolved(remote, cnames):
    """
    configure systemd-resolved to search for listed cnames through dnsmasq at 127.0.0.1
    """
    dir = '/etc/systemd/resolved.conf.d'
    remote.sh(f'sudo mkdir {dir}')

    path = dir + '/dnsmasq.conf'
    domains = ' '.join([f'~{cname}' for cname in cnames.keys()])
    data = f"""# This file is generated by dnsmasq teuthology task
[Resolve]
DNS=127.0.0.1
Domains={domains}
"""
    remote.sudo_write_file(path, data)
    remote.run(args=['sudo', 'restorecon', path], check_status=False)
    remote.run(args=['sudo', 'systemctl', 'restart', 'dnsmasq'])
    remote.run(args=['sudo', 'systemctl', 'restart', 'systemd-resolved'])
    remote.sh(f'cat {path}')
    try:
        yield
    finally:
        remote.run(args=['sudo', 'rm', path])
        remote.run(args=['sudo', 'systemctl', 'restart', 'systemd-resolved'])

@contextlib.contextmanager
def test_dns_names(remote, cnames):
    """ verify that ping can resolve the configured names """
    for cname in cnames.keys():
        remote.run(args=['ping', '-c', '4', cname])
    yield

@contextlib.contextmanager
def task(ctx, config):
    """
    Configures dnsmasq to add cnames for teuthology remotes. The task expects a
    dictionary, where each key is a role. If all cnames for that role use the
    same address as that role, the cnames can be given as a list. For example,
    this entry configures dnsmasq on the remote associated with client.0, adding
    two cnames for the ip address associated with client.0:

        - dnsmasq:
            client.0:
            - client0.example.com
            - c0.example.com

    If the addresses do not all match the given role, a dictionary can be given
    to specify the ip address by its target role. For example:

        - dnsmasq:
            client.0:
              client.0.example.com: client.0
              client.1.example.com: client.1

    Cnames that end with a . are treated as prefix for the existing hostname.
    For example, if the remote for client.0 has a hostname of 'example.com',
    this task will add cnames for dev.example.com and test.example.com:

        - dnsmasq:
            client.0: [dev., test.]
    """
    # apply overrides
    overrides = config.get('overrides', {})
    misc.deep_merge(config, overrides.get('dnsmasq', {}))

    # multiple roles may map to the same remote, so collect names by remote
    remote_names = {}
    for role, cnames in config.items():
        remote = get_remote_for_role(ctx, role)
        if remote is None:
            raise ConfigError('no remote for role %s' % role)

        names = remote_names.get(remote, {})

        if isinstance(cnames, list):
            # when given a list of cnames, point to local ip
            for cname in cnames:
                if cname.endswith('.'):
                    cname += remote.hostname
                names[cname] = remote.ip_address
        elif isinstance(cnames, dict):
            # when given a dict, look up the remote ip for each
            for cname, client in cnames.items():
                r = get_remote_for_role(ctx, client)
                if r is None:
                    raise ConfigError('no remote for role %s' % client)
                if cname.endswith('.'):
                    cname += r.hostname
                names[cname] = r.ip_address

        remote_names[remote] = names

    # run subtasks for each unique remote
    subtasks = []
    for remote, cnames in remote_names.items():
        subtasks.extend([ lambda r=remote: install_dnsmasq(r) ])
        if remote.os.package_type == 'rpm':
            path = '/etc/NetworkManager/dnsmasq.d/ceph.conf'
            subtasks.extend([ lambda r=remote, p=path, cn=cnames: configure_dnsmasq(r, p, cn) ])
            subtasks.extend([ lambda r=remote: configure_network_manager(r) ])
        else:
            path = '/etc/dnsmasq.d/ceph.conf'
            subtasks.extend([ lambda r=remote, p=path, cn=cnames: configure_dnsmasq(r, p, cn) ])
            subtasks.extend([ lambda r=remote, cn=cnames: configure_systemd_resolved(r, cn) ])
        subtasks.extend([ lambda r=remote, cn=cnames: test_dns_names(r, cn) ])

    with contextutil.nested(*subtasks):
        yield
