#!/bin/sh

DEV=$1
NUM=`echo $DEV | sed 's#p.*##g; s#[a-z]##g'`
POOL=`cat /sys/devices/rbd/$NUM/pool 2>/dev/null` || exit 1
if [ -f /sys/devices/rbd/$NUM/pool_ns ]; then
    NAMESPACE=`cat /sys/devices/rbd/$NUM/pool_ns 2>/dev/null`
else
    NAMESPACE=""
fi
IMAGE=`cat /sys/devices/rbd/$NUM/name 2>/dev/null` || exit 1
SNAP=`cat /sys/devices/rbd/$NUM/current_snap 2>/dev/null`

# the device may disappear between reads: refuse to print a partial name
if [ -z "$POOL" ] || [ -z "$IMAGE" ]; then
    exit 1
fi

echo -n "$POOL"
if [ -n "$NAMESPACE" ]; then
    echo -n "/$NAMESPACE"
fi
echo -n "/$IMAGE"
if [ -n "$SNAP" ] && [ "$SNAP" != "-" ]; then
    echo -n "@$SNAP"
fi
