#!/bin/sh

DEV=$1
NUM=`echo $DEV | sed 's#p.*##g' | tr -d 'a-z'`
POOL=`cat /sys/devices/rbd/$NUM/pool`
IMAGE=`cat /sys/devices/rbd/$NUM/name`
SNAP=`cat /sys/devices/rbd/$NUM/current_snap`
if [ "$SNAP" = "-" ]; then
	echo -n "$POOL $IMAGE"
else
	echo -n "$POOL $IMAGE@$SNAP"
fi
