#ifndef CEPH_RELEASE_H
#define CEPH_RELEASE_H

#define CEPH_RELEASE @CEPH_RELEASE@
#define CEPH_RELEASE_NAME "@CEPH_RELEASE_NAME@"
#define CEPH_RELEASE_TYPE "@CEPH_RELEASE_TYPE@"
#define CEPH_BUILD_TYPE "@CEPH_BUILD_TYPE@"

#endif
