#!/bin/bash

dname=`dirname $0`
cur=`git rev-parse HEAD 2>/dev/null`
[ -e $1 ] && old=`cat $1`

if [ "$cur" != "$old" ]; then
    echo regenerating $1 with $cur
    echo $cur > $1
else
    echo $1 is up to date.
fi

