#!/bin/sh

daemon=0
valgrind=""

# explicit -n/--norestart?
while [ $# -ge 1 ]; do
    case $1 in
	-n | --norestart )
	    daemon=1
	    shift
	    ;;
	--valgrind )
	    valgrind="valgrind"
	    daemon=1
	    shift
	    ;;
	* )
	    break
    esac
done

orig_args=$*

# implicit from any -d?
while [ $# -ge 1 ]; do
       case $1 in
               -d | --daemon )
               daemon=1
       esac
       shift
done

while [ true ]; do
	$valgrind $orig_args
	[ $daemon -eq 1 ] && exit
done
