#!/bin/sh -e

# libtool and yasm do not get along.
# filter out any crap that libtool feeds us that yasm does not understand.
new=""
touch=""
while [ -n "$*" ]; do
    case "$1" in
	-f )
	    shift
	    new="-f $1"
	    shift
	    ;;
	-g* | -f* | -W* | -MD | -MP | -fPIC | -c | -D* | --param* | -O* | -I* | -m* | -pipe )
	    shift
	    ;;
	-MT )
	    shift
	    shift
	    ;;
	-MF )
	    shift
	    touch="$1"
	    shift
	    ;;
	* )
	    new="$new $1"
	    shift
	    ;;
    esac
done

echo $0: yasm $new
yasm $new

[ -n "$touch" ] && touch $touch

true