#!/bin/sh -e

# libtool and yasm do not get along.
# filter out any crap that libtool feeds us that yasm does not understand.
#echo $0: got $*
new=""
touch=""
while [ -n "$*" ]; do
    case "$1" in
	-f )
	    shift
	    new="$new -f $1"
	    shift
	    ;;
	-c | --param* | -m* | -pipe | -thread )
	    # unknown options under both yasm & nasm
	    shift
	    ;;
	-D* )
	    # ignore define Macro option
	    shift
	    ;;
	-g* )
	    # ignore debug format
	    shift
	    ;;
	-W* )
	    # Warning/error option
	    shift
	    ;;
	-MD | -MP | -E | -O* )
	    # ignore option: nasm support, yasm not support
	    shift
	    ;;
	-MT )
	    # ignore option: nasm support, yasm not support
	    shift
	    shift
	    ;;
	-MF )
	    shift
	    touch="$1"
	    shift
	    ;;
	-f* )
	    shift
	    ;;
	-I | -isystem )
	    shift
	    new="$new -i $1"
	    shift
	    ;;
	* )
	    # Keep other options
	    new="$new $1"
	    shift
	    ;;
    esac
done

#echo $0: yasm $new
yasm $new

[ -n "$touch" ] && touch $touch

true
