#!/bin/sh

# libtool and yasm do not get along.
# filter out any crap that libtool feeds us that yasm does not understand.
#echo $0: got $*
new=""
touch=""
object=""
while [ -n "$*" ]; do
    case "$1" in
	-f )
	    shift
	    new="$new -f $1"
	    shift
	    ;;
	-g* | -f* | -W* | -MD | -MP | -fPIC | -c | -D* | -E | --param* | -O* | -m* | -pipe | ggc-min* | -pthread )
	    shift
	    ;;
	-I | -isystem )
	    shift
	    new="$new -i $1"
	    shift
	    ;;
	-MT )
	    shift
	    shift
	    ;;
	-MF )
	    shift
	    touch="$1"
	    shift
	    ;;
	-o )
	    shift
	    object="$1"
	    new="$new -o $1"
	    shift
	    ;;
	* )
	    new="$new $1"
	    shift
	    ;;
    esac
done

#echo ${0}: yasm ${new}
yasm ${new}

echo ${new} | grep -- "crc32c_intel_fast*asm\.s"
if [ $? -ne 0 ]; then
    ld -r -z ibt -z shstk -z noexecstack -o ${object}.tmp ${object}
    mv ${object}.tmp ${object}
fi

[ -n "$touch" ] && touch $touch

true
