# CMake generated Testfile for 
# Source directory: /home/sh3ll/ceph/ceph/src/test/crush
# Build directory: /home/sh3ll/ceph/ceph/src/test/crush
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unittest_crush_wrapper "/home/sh3ll/ceph/ceph/bin/unittest_crush_wrapper")
set_tests_properties(unittest_crush_wrapper PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/sh3ll/ceph/ceph;CEPH_BIN=/home/sh3ll/ceph/ceph/bin;CEPH_LIB=/home/sh3ll/ceph/ceph/lib;CEPH_BUILD_DIR=/home/sh3ll/ceph/ceph;LD_LIBRARY_PATH=/home/sh3ll/ceph/ceph/lib;PATH=/home/sh3ll/ceph/ceph/bin:/home/sh3ll/ceph/ceph/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/sh3ll/ceph/ceph/lib/cython_modules/lib.3:/home/sh3ll/ceph/ceph/src/pybind;CEPH_BUILD_VIRTUALENV=/home/sh3ll/ceph/ceph" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/sh3ll/ceph/ceph/cmake/modules/AddCephTest.cmake;5;add_test;/home/sh3ll/ceph/ceph/cmake/modules/AddCephTest.cmake;54;add_ceph_test;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;4;add_ceph_unittest;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;0;")
add_test(unittest_crush "/home/sh3ll/ceph/ceph/bin/unittest_crush")
set_tests_properties(unittest_crush PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/sh3ll/ceph/ceph;CEPH_BIN=/home/sh3ll/ceph/ceph/bin;CEPH_LIB=/home/sh3ll/ceph/ceph/lib;CEPH_BUILD_DIR=/home/sh3ll/ceph/ceph;LD_LIBRARY_PATH=/home/sh3ll/ceph/ceph/lib;PATH=/home/sh3ll/ceph/ceph/bin:/home/sh3ll/ceph/ceph/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/sh3ll/ceph/ceph/lib/cython_modules/lib.3:/home/sh3ll/ceph/ceph/src/pybind;CEPH_BUILD_VIRTUALENV=/home/sh3ll/ceph/ceph" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/sh3ll/ceph/ceph/cmake/modules/AddCephTest.cmake;5;add_test;/home/sh3ll/ceph/ceph/cmake/modules/AddCephTest.cmake;54;add_ceph_test;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;10;add_ceph_unittest;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;0;")
add_test(crush_weights.sh "/home/sh3ll/ceph/ceph/src/test/crush/crush_weights.sh")
set_tests_properties(crush_weights.sh PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/sh3ll/ceph/ceph;CEPH_BIN=/home/sh3ll/ceph/ceph/bin;CEPH_LIB=/home/sh3ll/ceph/ceph/lib;CEPH_BUILD_DIR=/home/sh3ll/ceph/ceph;LD_LIBRARY_PATH=/home/sh3ll/ceph/ceph/lib;PATH=/home/sh3ll/ceph/ceph/bin:/home/sh3ll/ceph/ceph/src:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/sh3ll/ceph/ceph/lib/cython_modules/lib.3:/home/sh3ll/ceph/ceph/src/pybind;CEPH_BUILD_VIRTUALENV=/home/sh3ll/ceph/ceph" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/sh3ll/ceph/ceph/cmake/modules/AddCephTest.cmake;5;add_test;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;13;add_ceph_test;/home/sh3ll/ceph/ceph/src/test/crush/CMakeLists.txt;0;")
