#!/usr/bin/perl

# hi there
{
	'sleep' => 3,

	'osdbits' => [6,7,8],#,9],10,11],
	'pgperbits' => [3],#,4,5],#[4,6,8],

	'nummds' => 1,

	'_dep' => [ 'numosd' => '1 << $osdbits',
				'osd_pg_bits' => '$pgperbits + $osdbits',
				'n' => '3 + $numosd / 32'],
	'numclient' => 0,

	'fake_osdmap_updates' => [30],

	'fs' => 'ebofs',

	'start' => 30,
	'end' => 300,
	'kill_after' => 300,
	
	'custom' => '--bdev_lock 0 --ms_stripe_osds --osd_maxthreads 0',
	#'custom' => '--tcp_skip_rank0',

	'comb' => {
		'x' => 'osdbits',
		'vars' => [ 'osd.sum=mapi', 'osd.sum=mapidup', 'osd.numpg', 'osd.pingset' ]
	}
};
