---
name: "Check for Incompatible Licenses"
on:
  pull_request_target:
    branches:
      - main
      - umbrella
      - tentacle
      - squid

permissions:
  contents: read
  pull-requests: read

jobs:
  pull_request:
    name: "Check for Incompatible Licenses"
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Diff for License
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_number=${{ github.event.pull_request.number }}
        repo=${{ github.repository }}

        gh api "repos/$repo/pulls/$pr_number/files" --paginate --jq \
          '.[] | select(.filename != ".github/workflows/check-license.yml") | .patch' |
          grep -qi "GNU General Public License" && {
            echo "Error: Incompatible license 'GNU General Public License' found in PR changes."
            exit 1
          } || true
