---
name: "Check for Incompatible Licenses"
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  pull_request:
    name: "Check for Incompatible Licenses"
    runs-on: ubuntu-latest
    steps:
    - name: Check Pull Request
      uses: JJ/github-pr-contains-action@ea09c8a108fe34a2c1bbd81c261cc3a6aa0717f2 # releases/v14.1.1
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: "GNU General Public License"
