name: Check PR dependencies
on: [pull_request_target]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@a8cccab69814b9b985496cf97cbfe154c96c03c7 # v1.4.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
