---
name: "Pull Request Triage"
on: pull_request_target
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels based on modified files
        # https://github.com/marketplace/actions/labeler?version=v7.0.0
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13
        with:
          sync-labels: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Assign to Dashboard project
        # https://github.com/marketplace/actions/add-to-github-projects?version=v2.0.0
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd
        with:
          project-url: https://github.com/orgs/ceph/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: dashboard
      - name: Assign milestone based on target brach name
        # https://github.com/marketplace/actions/pull-request-milestone?version=v1.4.0
        uses: iyu/actions-milestone@d3a96497d18f333d0419641cc3fcfbd02939a2aa
        with:
          configuration-path: .github/milestone.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
