---
name: "Check for missing .qa links"
on:
  pull_request:
    # Run CI check only for branches which are active and a target for a PR
    branches:
      - main
      - umbrella
      - tentacle
      - squid
    types:
      - opened
      - synchronize
      - edited
      - reopened
permissions:
  contents: read
jobs:
  check-qa-links:
    name: "Check for missing .qa links"
    runs-on: ubuntu-latest
    if: github.repository == 'ceph/ceph'
    steps:
      - name: Checkout verify-qa script from main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: 'refs/heads/main'
          path: main
          sparse-checkout: |
            src/script/verify-qa
          sparse-checkout-cone-mode: false

      - name: Checkout PR HEAD
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pull_request

      - name: verify .qa links
        run: ../main/src/script/verify-qa
        working-directory: pull_request/
